### ISSUE TITLE
Add specificity to the "name" property of a request

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1025]
As a user, I'm confused when the CLI gives me an error message that `Request name is required because the request has query parameters`. Just saying **name** isn't specific enough. `request-name` or another identifier would help me understand that I need this:

```diff
endpoints:
        listAll:
          display-name: List all subscriptions
          docs: Returns a list of subscriptions. The subscriptions returned are sorted by creation date, with the most recently created subscriptions appearing first.
          path: /subscriptions
          request:
+          name: ListAllSubscriptionsRequest
            query-parameters:
              after: 
                docs: A cursor for use in pagination. The after parameter takes an object ID that defines the position in the list, only items immediately following the item with that ID will be returned.
                type: optional<string>
```

<img width="966" alt="Screenshot 2022-12-19 at 4 07 40 PM" src="https://user-images.githubusercontent.com/83524670/208551623-7733b947-1ab1-45c9-9380-c9c99d4450ef.png">

**Comment by dsinghvi** [comment]
Deprioritizing
