### ISSUE TITLE
Support for regex

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1026]
Example:
Possible values: 1 ≤ length ≤ 16, Value must match regular expression ^[a-zA-Z0-9](?:[a-zA-Z0-9]-?)+[a-zA-Z0-9]$

![Screenshot 2022-12-19 at 6 32 25 PM](https://user-images.githubusercontent.com/83524670/208568245-0c6c2aac-6196-41e5-8506-5c9a322d5a2d.png)

**Comment by dsinghvi** [comment]
Closing this issue because this is something we wont be working on.
