### ISSUE TITLE
Inline request migration defaults `name`

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1031]
When migrating to inline request we should default the `name` to something like `<PLACEHOLDER_NAME_CHANGE_ME>`. This makes it obvious where `name` should go whereas currently it is hard to figure out. 

`fern check` should still fail on the placeholder names because we don't want anyone to run `fern generate` and use the place holders in their SDKs/docs.

**Comment by zachkirsch** [comment]
makes sense, easy thing is to make the placeholder invalid so we don't have to hardcode the placeholder in the validator

**Comment by dsinghvi** [comment]
this migration is pretty old now, no longer relevant
