### ISSUE TITLE
I can't specify standard codes for countries

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1042]
countries is an list of string `ISO 3166-1 alpha-2` which is a 
```
List of countries in ISO 3166-1 alpha-2 format covered by this coverage configuration.
```

Example:
`["DE","FR","US"]`

Today in Fern, the most specific I can get is `string`.

Context: OpenAPI supports this and renders it in Stoplight docs. (Example https://developers.gigs.com/docs/api/bc5c988e713ed-list-all-plans#response-body )

**Comment by dsinghvi** [comment]
<img width="633" alt="Screen Shot 2022-12-24 at 1 34 21 AM" src="https://user-images.githubusercontent.com/10870189/209424579-2f4fe93a-2edc-4ee6-96bf-5e9ab260349d.png">

i think its totally fine to just have it in docs and if someone wants to be more specific then i think its worth just creating the enum

**Comment by dsinghvi** [comment]
Closing because we think docs is enough to communicate the relevant information.
