### ISSUE TITLE
I can't specify a currency code

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1043]
I have a property that is a `currency`. I'm using the ISO 4217 three-letter standard (e.g. USD, EUR) and would like to be able to specify that in my Fern Definition.

**Comment by dsinghvi** [comment]
can you explain the motivation behind wanting it in your fern definition? why isn't adding this info in docs enough?

**Comment by dsinghvi** [comment]
Closing because we think docs is enough to communicate the relevant information.
