### ISSUE TITLE
Sync to Stoplight for API docs

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1044]
As a user, I want to update my Stoplight API docs when I release my API.

**Thoughts**
1. I'd like to configure Stoplight in `generators.yml`. Could be part of `fern-openapi` or `fern-stoplight`. 
2. I'd like Fern (Fiddle) to generate the `ci.yml` file into `{company}-openapi` repo. [Example](https://github.com/fern-gigs/gigs-openapi/blob/main/.github/workflows/ci.yml)
3. Once built, we should add instructions to our docs.

**Comment by dsinghvi** [comment]
Stale
