### ISSUE TITLE
Add an endpoint example of an error

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1045]
I'm looking for how to model an error with a body for an endpoint, and don't see it in the Docs.

**Comment by dannysheridan** [comment]
Where I'm looking: https://www.buildwithfern.com/docs/definition/services#examples

**Comment by dsinghvi** [comment]
Relevant snippet to unblock you:
https://github.com/fern-api/fern/blob/56c969580f2507a37dccde6a04ee83838f8c703b/packages/cli/ete-tests/src/tests/ir/fixtures/simple/fern/api/definition/imdb.yml#L100-L106
