### ISSUE TITLE
fern-release didn't run correctly, but didn't throw an error

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1060]
https://github.com/fern-primer/primer-api/actions/runs/3783614880/jobs/6432301003

I was surprised when it seemed like `fern release` ran, but it didn't.

**Comment by dannysheridan** [comment]
Root cause: https://github.com/fern-primer/primer-api/commit/f3cafc53748a6967319e915ef23912d5e9b0a1f8

**Comment by dsinghvi** [comment]
https://github.com/fern-api/fern/pull/1046 fix merged
