### ISSUE TITLE
I lost a commonly referenced type during a migration

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1065]
https://github.com/ravenappdev/raven-api/pull/31/commits/b1db4aba4dda30a9e89883ebcff211e04123f273

The migration moved `Device` in-line for a request. I reference that type multiple times in the API definition and thus failed `fern check` now. It feels like the migration caused me a headache to go figure out how to fix this.

**Comment by dsinghvi** [comment]
Similar issue here: https://github.com/fern-api/fern/issues/1032 (closing that one)

**Comment by dsinghvi** [comment]
Stale
