### ISSUE TITLE
Support a date-time primitive in Java

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#107]
created_at_utc: "1981-11-30T10:44:38.567Z"

https://birchsolutions.slack.com/archives/C0222UL3XS9/p1651200517793859?thread_ts=1651199301.661399&cid=C0222UL3XS9

**Comment by dannysheridan** [comment]
added to types.yml. has it been implemented in codegen?

**Comment by dsinghvi** [comment]
moved issue: https://github.com/fern-api/fern-java/issues/128
