### ISSUE TITLE
I want to see an example of an error on the Errors documentation page

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1073]
On https://www.buildwithfern.com/docs/definition/errors I'd like to see how to add an example. While this may also be in another part of our docs, I'd expect it to be accessible on this page.

**Comment by zachkirsch** [comment]
We don’t have error examples

**Comment by dannysheridan** [comment]
For my reference:

```
# error
         examples:
            - response:
                error: EventNotFoundError
                body: 
                  success: false
                  error: event not found
```

**Comment by zachkirsch** [comment]
Ahh got it 🤙

**Comment by zachkirsch** [comment]
Not sure if that’s the right page for this- that page is around declaring errors, and your snippet is a failed endpoint call. Maybe there’s some hyperlinking we can do?

**Comment by dannysheridan** [comment]
Problem: I want to see an example of how I can configure an `example` of an `error`. 
Flexible on the solution.

**Comment by zachkirsch** [comment]
Yep makes sense. There’s an example here that can be more fleshed out https://www.buildwithfern.com/docs/definition/endpoints#examples

**Comment by dannysheridan** [comment]
+1 for this request

**Comment by dannysheridan** [comment]
Learning: if the CLI gives you the message `Error is not defined.` it is because you may not be referencing the type from an import.

```diff
response: 
-  error: PaymentsRequestValidationError
+  error: commons.PaymentsRequestValidationError
    body: 
      errorId: RequestValidationError
      description: Invalid type for `currencyCode` 
      recoverySuggestion: The currency code must be a valid value
      diagnosticsId: '1234567898'
```

**Comment by dannysheridan** [comment]
It would also be helpful to see an example of a `query-parameter`:

```
examples: 
  # success
  - query-parameters:
      clientToken: my-client-token
    response:
      body: #etc.
```
