### ISSUE TITLE
Fern upgrade didn't exit after running

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1076]
After running `fern upgrade`, the CLI didn't give me back my terminal. I had to manually exit, ran the command again, and learned that it had successfully completed the first time.

<img width="559" alt="Screenshot 2022-12-28 at 2 13 32 PM" src="https://user-images.githubusercontent.com/83524670/209872769-77eca3d4-c4ae-4ca5-b3dc-0c96c5b5c81c.png">

**Comment by dsinghvi** [comment]
how long did you give it to manually exit? sometimes it takes a second

**Comment by dannysheridan** [comment]
~10 seconds

**Comment by dsinghvi** [comment]
hasn't reproed for me -- are you consistently getting this issue?

**Comment by dannysheridan** [comment]
Negative. Just once.

**Comment by dsinghvi** [comment]
Got it -- then i think we should close this issue since there is no clear action.
