### ISSUE TITLE
Support independently releasing SDKs

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1097]
If I only upgrade the `postman` generator, then I shouldn't have to release all my SDKs. Fern should have a way of independently managing artifacts.

**Comment by zachkirsch** [comment]
It's like "rerun from failed" vs "rerun" on Circle

**Comment by dsinghvi** [comment]
But also if I only upgrade my postman generator, then I don't need to release a new version of the java sdk

**Comment by zachkirsch** [comment]
oh yep makes sense - run one workflow as opposed to a whole group

**Comment by dsinghvi** [comment]
Closing because requires another repo (backend)
