### ISSUE TITLE
Silence a fern check warning

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1102]
I have a type called `petId` that’s a UUID. I want to show an example where someone provides an incorrect ID. My example is `az123456789`. I fail `fern check` because this isn’t a UUID, which is the point of the example. Is there a way around this?

**Comment by zachkirsch** [comment]
One issue here is that you won't be able to construct a valid example. If you send a non-UUID, then the server will reject the reject because it's malformed. It won't throw any of the errors you've defined in Fern.

**Comment by dannysheridan** [comment]
Closing this out given that context.
