### ISSUE TITLE
[Feature Request] Generate fake implementation

### ISSUE THREAD

**Issue by adamsuskin** [fern-api/fern#1116]
It would be really cool if Fern could auto-generate a fake HTTP service that I can easily access from a client (whether it actually runs on the server or is mocked on the client) that returns notional data based on the response shape types.

To me, this would be valuable for front-end (client) development where when working with a BE counter-part, we start with Fern definitions and from the get-go, I have endpoints I can hit that 200 and give me data (albeit they may not be perfect/semantically correct). Alternatively, if I can "just use Fern" and specify "fake" mode and Fern handles not actually sending any HTTP requests but resolving local promises with notional data.

This saves me time as I don't spend tens of minutes/hours to create a fake data service in my client / probably also useful for writing unit or integration tests.

EDIT: it could even be based on the examples that a developer provides in the documentation

**Comment by zachkirsch** [comment]
+1 this would be sick

**Comment by johnwiseheart** [comment]
Yeah I could imagine some extra metadata attached to fields in the yaml explaining that `first_name` is a `name` type, etc. That way it could do clever semantically correct fake data. Might be more work on the backend, but wouldn't be that bad. Then that can also build into the examples in docs too.
