### ISSUE TITLE
Fern check errors within examples should include breadcrumbs

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1143]
![Screenshot 2023-01-12 at 11 22 45 PM](https://user-images.githubusercontent.com/83524670/212261229-07c99032-21ca-4514-bf69-6feb9f497bdb.png)

As a user, I'm not sure where to fix my API Definition to fix this error. It takes more sleuthing than I would like.

Code: https://github.com/fern-corrily/corrily-api/tree/ea241bcb9be27c25ba3a2600cb579a6d5ff45dfb

**Comment by dannysheridan** [comment]
In this case, this fixed it:

```diff
         examples:
            - request:
                user_id: string
                features:
                  source: youtube
+             response: 
+              body: 
+                 status: ok
```

**Comment by dsinghvi** [comment]
Deprioritizing till it is requested from the community
