### ISSUE TITLE
`fern generate` is too slow

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#1168]
`fern generate` can take a while.

In cases where `fern generate` is run in CI to publish SDKs, this isn't a huge deal. People are generally not blocked on that.

In cases where `fern generate` is run locally for server-side development, this is a much bigger deal. The long runtime increases iteration times and reduces productivity.

**Comment by dsinghvi** [comment]
Will need to solve on a case by case basis at the generator level, this issue doesn't mean much
