### ISSUE TITLE
Set expectation about wait time for fern generate

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1238]
When the user runs `fern generate` and has an SDK in `generators.yml` it can take 1-2 minutes to complete the command. We should let the user know that it will take a bit of time. Waiting on a spinning CLI is not a positive emotion; communication of expectations would be appreciated
 
<img width="609" alt="Screenshot 2023-01-28 at 10 25 19 PM" src="https://user-images.githubusercontent.com/83524670/215309067-37d54002-f54e-4ce3-9bb5-3a20603cef2d.png">

**Comment by dsinghvi** [comment]
Deprioritizing
