### ISSUE TITLE
Unable to re-run a migration after it fails

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1257]
I failed a migration while upgrading the Fern CLI. Then I figured out what I manually overrode, undid the change, and ran `fern upgrade` again. The CLI version was already upgraded so no migration ran. 

I was able to `git stash` and then run the migration again, but that feels like a workaround.

![ ](https://user-images.githubusercontent.com/83524670/215992802-8cd40e99-2444-436f-8473-3dc78de8df94.png)

**Comment by dsinghvi** [comment]
Deprioritizing
