### ISSUE TITLE
Compare Fern YAML with OpenAPI YAML in the code snippets in docs

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1306]
Comparing Fern's YAML to OpenAPI's YAML seems more reasonable to Marsh and me. (right now OpenAPI is in JSON)

**Comment by earth2marsh** [comment]
Indeed! JSON will use more lines and need braces agreement, so it seems like a better comparison to show YAML vs YAML in order to drive home the differences.

**Comment by zachkirsch** [comment]
Fixed with https://github.com/fern-api/fern/pull/1307!

**Comment by dannysheridan** [comment]
Thanks again for the suggestion @earth2marsh
