### ISSUE TITLE
Enforce similar naming conventions (snake_case, camelCase)

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1333]

**Comment by zachkirsch** [comment]
Ofc this is a little tricky for existing APIs that come into fern

**Comment by dsinghvi** [comment]
I think we should warn ? i think we need to be able to turn on and off rules in fern as well eventually

**Comment by zachkirsch** [comment]
Yeah agreed, the one `warn` we added is super annoying in repos where the violation is intentional IMO

**Comment by dsinghvi** [comment]
Deprioritizing
