### ISSUE TITLE
Can't differentiate between "unknown" and "unsupported by fern"

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#1415]
Right now, it feels like there's two cases: unknown and unsupported. unknown means "server doesn't know" (e.g. user supplied custom config) and unsupported means "server knows, but fern doesn't support it"

Right now we use `unknown` for both. In a docs context, we'd probably want to differentiate between the two

**Comment by dsinghvi** [comment]
Deprioritizing
