### ISSUE TITLE
Support global path parameters for a fern package

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1430]
All the endpoints in a given package may require a path parameter. In this case, the user should only have to specify that path parameter once and not in every single endpoint call. 

This would allow us to generate: 
- resource based SDKs: `client.workbook(workbookId).sheet(sheetId).getField()`
- initialize sdks with a path parameter `client = new Client({appId: "my-app-id"});`

**Comment by zachkirsch** [comment]
How does creating a workbook / sheet work?

**Comment by dsinghvi** [comment]
hmm thats interesting, the ideal sdk experiences would be: 

``ts
client.workbook.create();
client.workbook(workbookId).sheet.create()
client.workkbook(workbookId).sheet(sheetId).getField()
```

**Comment by dsinghvi** [comment]
this is now supported in `api.yml`
