### ISSUE TITLE
[Feature] Add `nullable` container

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#1464]
We currently have the `optional<>` container, which means "not required."

There are some use cases for `nullable<>`, which means "this is still required, but it may be null"

**Comment by dannysheridan** [comment]
When `null` is supported, we can tackle this related issue: https://github.com/fern-api/fern/issues/2772

**Comment by dannysheridan** [comment]
Closing as we haven't gotten requests from a user so far this year. If that changes, will reopen!
