### ISSUE TITLE
Generated Python SDK request failure with httpx

### ISSUE THREAD

**Issue by Jacsarge** [fern-api/fern#1478]
I have a generated Fast API endpoint that responds to curl requests as well as python `requests.get` calls, but fails when using the generated python SDK that by default uses `httpx.request`. Switching that to `requests.get` fixes the problem and calls using the generated package work fine.

**Comment by dsinghvi** [comment]
If you upgrade the version in your `generators.yml` to the latest release ([0.3.2]([0.3.2](https://github.com/fern-api/fern-python/releases/tag/0.3.2))) does that work?

**Comment by dsinghvi** [comment]
Also if you can share a stacktrace that would be useful as well.

**Comment by Jacsarge** [comment]
Upgraded version in generators works. Didn't know what the latest version was
