### ISSUE TITLE
[openapi one-time-import] Endpoint definitions are missing names for requests that need them

### ISSUE THREAD

**Issue by lucasdellabella** [fern-api/fern#1496]
The one-time importer generates endpoint definitions that don't have a name in the request object, even when it is clear that the request will need a name field. suggestion: [endpointName]Request

```
[api]: providers.yml -> service -> endpoints -> getProviders
       Request name is required because request has query parameters
```

Resolution: `name: getProvidersRequest`

**Comment by dsinghvi** [comment]
Yup this makes sense to me @lucasdellabella -- the only failure case is when `{operationId}Request` overlap but `fern check` will alert on that

**Comment by dsinghvi** [comment]
Will close when released!

**Comment by dsinghvi** [comment]
This is solved on the latest version of fern CLI
