### ISSUE TITLE
Support for reusing query parameters

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#16]
@dannysheridan  encountered a case where a set of endpoints take the same 10 query-params. It's annoying to copy paste them everywhere and changing one things requires you to make edits in n different places. 

Should we have a concept of grouped query params?

**Comment by zachkirsch** [comment]
Idea: You can supply a `type` as the query-params. We'll have to runtime validate that all the value-types are primitives.

**Comment by dannysheridan** [comment]
+1

**Comment by zachkirsch** [comment]
Or maybe a concept of "groups" of query parameters that can be reused

**Comment by dannysheridan** [comment]
+1

**Comment by dsinghvi** [comment]
Closing because we are moving Github issues to be largely community-filed issues.
