### ISSUE TITLE
RequestId/MessageId

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#160]
@zachkirsch i think every wire message should have an id that makes it very easy to trace through your api while debugging. The IDs have been invaluable in my experience and fern is in a great position to bake them in. 

Can see us building a self-hostable analytics tool on top that can track those IDs and make it very easy for PMs + Devs to understand metrics/filter.

**Comment by dannysheridan** [comment]
+1 for RequestId

**Comment by dannysheridan** [comment]
I'd like to break these down into separate issues.

Are Error Instance, Request, or Message IDs supported today? Is there work to do on each generator for each ID?

**Comment by dsinghvi** [comment]
Closing this issue because it isn't being heavily requested by the community.
