### ISSUE TITLE
[Feature] Deprecation Date

### ISSUE THREAD

**Issue by vanhooser** [fern-api/fern#1638]
Hey folks 👋 

It would be super nice if we could mark an endpoint / service with a deprecation date for some point in the future, which would allow the following: 

1.  When generating a client it would warn the user explicitly that certain endpoints / services will be deprecated 
2. When generating server code, responses could automatically include a response header to indicate the endpoint's imminent deprecation 
3. Generated documentation would also include big warning visuals of deprecation dates

I have the suspicion that consumers of an API will need warnings at every possible level to make them less cranky

**Comment by dsinghvi** [comment]
@vanhooser that sounds like a great idea. at the spec level i think this would involve making the `availability` field more of a union. 

```yaml
availablity: 
  status: to-be-deprecated
  date: 11/24/23
```

**Comment by vanhooser** [comment]
That would be an awesome pattern! 

Separately, I'd love to see some kind of rolled up dataset as well that lists off all the endpoints and their availability status / deprecation date, this way I could reach out to the appropriate users periodically and remind them of upcoming deprecations and any relevant changes to them (could do this myself using data collection on usage of endpoints, but I'd need to have a list of endpoints soon to be deprecated)

**Comment by dsinghvi** [comment]
Makes a lot of sense -- we are seeing a lot of features that will necessitate having a fern portal where you can see all your apis/endpoints/sdk usage, etc. I think being able to see your endpoints against their availability and audiences will make a lot of sense on that portal.

**Comment by dannysheridan** [comment]
haven't gotten this request since. going to close this but encourage folks to re-engage if needed.
