### ISSUE TITLE
Improve error message when organization name is invalid

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#1655]
We should:
1. Say why it's invalid
2. Suggest the `fern init --organization <org name>` command

**Comment by ff137** [comment]
Thanks for following up!

As a minor mention (not worth creating an issue/PR just for a link fix) - the following link at:https://docs.buildwithfern.com/spec/openapi
> you can run [fern generate](https://docs.buildwithfern.com/compiler/generate).

The link should point to https://docs.buildwithfern.com/compiler/fern-generate

**Comment by shashank40** [comment]
Hello @zachkirsch can you please assign this issue to me? 

Also to get an idea of how specific the message should be when we return an error saying 'Why is it invalid'?

**Comment by zachkirsch** [comment]
I think the message can say something like “organization name must start with a letter contain only lowercase letters, numbers, and dashes”

**Comment by shashank40** [comment]
Hello @zachkirsch. Here is the PR for the same. https://github.com/fern-api/fern/pull/1792

**Comment by dsinghvi** [comment]
Closing since this is no longer a bug
