### ISSUE TITLE
Add backdrop blur to header

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1703]
When we scroll the docs they should blur behind the navbar using [Backdrop Blur](https://tailwindcss.com/docs/backdrop-blur#blurring-behind-an-element). 

Today the navbar has no blur: 

![Image](https://github.com/fern-api/fern/assets/10870189/66fafa4a-be7e-410e-b707-cc0f9089ccbe)

**Comment by shashank40** [comment]
Hello @dsinghvi can you explain this issue a bit more? Maybe with an image?

**Comment by kafkas** [comment]
I think we can rename this to something like "Add backdrop blur to header"

**Comment by dsinghvi** [comment]
Replaced by this [linear](https://linear.app/fern-api/issue/FER-20/navbar-blur) ticket
