### ISSUE TITLE
AWS API Gateway Integration - out of the box

### ISSUE THREAD

**Issue by hatemelseidy** [fern-api/fern#1721]
I'm looking to define my APIs in fern, generate SDKs and deploy APIs to AWS API Gateway.

API Gateway supports import from OpenAPI definition, but that requires [x-amazon-apigateway-integration object](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html). Which in turn requires the backend.

### Approach 1

One way to get around that is if API_GATEWAY flag is enabled in API definition, fern would generate an OpenAPI template with something like the below, then the user would replace the `{PLACEHOLDER}` on their own during deployment with the actual backend uri.

```
"x-amazon-apigateway-integration" : {
  "httpMethod" : "...",
  "uri" : "{PLACEHOLDER}",
  "passthroughBehavior" : "...",
  "type" : "..."
}
```

### Approach 2

Some kind of direct integration with AWS CDK and/or Cloud Formation (something like [this](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_apigateway/LambdaRestApi.html) but called FernRestApi), not sure how this exactly would work. As an end user, what makes perfect sense to me is a CDK construct that takes the fern definition files and allow additional API gateway methods like Lambda integration.

### Key requirements (for me personally)
1. Easy out of the box integration.
2. CI/CD friendly.
3. IaC friendly (CDK and/or terraform).

**Comment by dsinghvi** [comment]
@hatemelseidy our OpenAPI generators is open source (see here: https://github.com/fern-api/fern-openapi). One route could be to use that as a base and publish another generator that outputs an OpenAPI specifically for AWS API Gateway. The generator could be called something like `aws-api-gateway-openapi`. 

Here's a link to my [calendly](https://calendly.com/deep-singhvi/30min) if a video call may be better!

**Comment by hatemelseidy** [comment]
@dsinghvi Thanks will send an invitation soon.

**Comment by dsinghvi** [comment]
@hatemelseidy im going to close this issue since its stale -- i think the best option here is to either:  
- script on your own
- fork the `OpenAPI generator` and create a AWS API Gateway generator
