### ISSUE TITLE
[CLI] `fern generate` local run

### ISSUE THREAD

**Issue by marvin-kolja** [fern-api/fern#1755]
Hey, first of all, thanks for this awesome toolset!

### Problem

1. Unclarity about whether `fern generate` runs locally or in the cloud.
2. There is no documentation on how to run it locally.

### Context

I couldn't stop wondering why `fern generate` needed an internet connection. In addition, it took longer than expected and didn't stress my CPU.

I checked what the command was doing and discovered it was downloading data from S3.

So I went back to your [documentation](https://buildwithfern.com/docs/comparison-with-openapi#cloud-based-code-generation-and-publishing) where it claims that _"[f]ern can run your code generation in the cloud"_. If I would have kept reading the first time, it would have made it clear that running `fern generate` would run in the cloud. **However**, the _"can"_ in the first sentence makes it unclear!

The `yarn generate` command has `--local` as optional ([source](https://github.com/fern-api/fern/blob/main/packages/cli/cli/src/cli.ts#LL236C10-L236C28)), but it's hidden. I'm unsure if this is intended, but it conflicts with your documentation.  If you're saying `fern generate` _"can"_ run in the cloud, it should be clear how to run it locally.

### Suggestion

1. Rewriting the first sentence to something like:
_"Fern runs your code generation in the cloud by default."_

3. If running Fern locally is an intended feature:
	1. Enhance the CLI documentation in regard to how to run `yarn generate` locally
	2. Unhide options like `local`, `keepDocker`, `printZipUrl`

If you're fond of these suggestions I could take the time and create a PR ;)

**Comment by dsinghvi** [comment]
@marvin-kolja thanks for pointing out the confusion here. Definitely happy to take a PR to updated the documentation + unhide the `local` and `keepDocker` options.
