### ISSUE TITLE
Support `.fernignore` when generating locally

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1780]
Currently when we run `fern generate` locally this deletes the generated directory and rewrites all the files. This is problematic for users that want to modify certain files / or add utilities so we should support `.fernignore` in this directory. 

Specifically we shouldn't `rm` the generated directory like we do here: https://github.com/fern-api/fern/blob/a332d7363fa6a4de5b3a44f885ec7c0aa21c0e1b/packages/cli/generation/local-generation/local-workspace-runner/src/runLocalGenerationForWorkspace.ts#L122. 

Instead we should check if a `.fernignore` is present in the directory and do: 
1. Read the `.fernignore` and store all paths in a list
2. `git init` the directory
3. Run `git rm -rf .` to stage deletes of all files
4. Copy all generated files to the directory
5. Unstage all paths that match the `.fernignore` by running `git reset <list of paths> && git restore .` 
6. Delete the newly created `.git` folder and we should be good

**Comment by SlamChillz** [comment]
Hi @dsinghvi, I am very much interested in implementing this feature. Please kindly assign it to me, Thank You.

**Comment by dsinghvi** [comment]
@SlamChillz  feel free to make a PR!

**Comment by SlamChillz** [comment]
Will do, thank you @dsinghvi. I will be in touch if I need clarifications.
