### ISSUE TITLE
Generated python code with various errors

### ISSUE THREAD

**Issue by estahn** [fern-api/fern#1796]
Using the generated code:
```
Traceback (most recent call last):
  File "/Users/estahn/src/clipsal/sungrow-python-sdk/test.py", line 5, in <module>
    from generated.sungrow_python_sdk.client import EstahnApi
  File "/Users/estahn/src/clipsal/sungrow-python-sdk/generated/sungrow_python_sdk/client.py", line 23
    def (self, *, appkey: str, lang: typing.Optional[str] = OMIT, sys_code: typing.Optional[str] = OMIT, user_account: str, user_password: str) -> Response:
        ^
SyntaxError: invalid syntax
```

Generated code:
```
class EstahnApi:
    def __init__(self, *, environment: EstahnApiEnvironment = EstahnApiEnvironment.DEFAULT
    , content_type: str):
        self._environment = environment
        self.content_type = content_type
    def (self, *, appkey: str, lang: typing.Optional[str] = OMIT, sys_code: typing.Optional[str] = OMIT, user_account: str, user_password: str) -> Response:
```

^^ Missing function name for example.

**Comment by estahn** [comment]
RTFM: https://buildwithfern.com/docs/spec/extensions#sdk-method-names

**Comment by dsinghvi** [comment]
@estahn thanks for making this issue -- the fern cli should validate that all endpoints have names. Would you be up to share the OpenAPI spec that you used to generate this invalid code?

**Comment by estahn** [comment]
@dsinghvi Seems this was resolved in 0.11, or at least I can't reproduce it anymore. Thanks though!

**Comment by estahn** [comment]
@dsinghvi I was just about to move on, but here we go.

The schema in question has `operationId: ''` on one of the methods. This was generated by Stoplight Studio. Adding a value to this will fix the issue. Nonetheless code in being generate either way, just that the code doesn't work.

**Comment by dsinghvi** [comment]
Thanks! If the `operationId is ""` then we should default to using the url.

**Comment by dsinghvi** [comment]
@estahn this should be fixed in the latest version of the CLI. If the operationId is `''` then we rely on the path of the endpoint to generate the method name (even if its ugly)
