### ISSUE TITLE
Default values in OpenAPI are not being used

### ISSUE THREAD

**Issue by estahn** [fern-api/fern#1799]
I have set default values on several attributes which don't end up being used in the code.

**Comment by dsinghvi** [comment]
@estahn how would you expect the default values to be used for the SDK? Usually the server handles adding those defaults if you don't provide them.

**Comment by estahn** [comment]
If I instantiate one of the types, it should have the default values if I don't pass anything.

Pydantic provides that already I believe.

https://docs.pydantic.dev/latest/usage/models/#basic-model-usage

**Comment by dannysheridan** [comment]
Closing as we don't plan to support default values in the Fern Definition YAML format
