### ISSUE TITLE
Support showing docs for each "resource" or subpackage

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1806]
If a user adds `docs` to a Fern Definition YAML File then those docs are not shown in the generated fern documentation. 

For example, if i had a file `agents.yml` with the contents 

```yaml
docs: | 
  The agents API allows you to ... 
```

then I would expect that those docs would be injected in the fern definition. 

<img width="1669" alt="Screen Shot 2023-06-25 at 1 40 39 AM" src="https://github.com/fern-api/fern/assets/10870189/1149ff47-0c33-46ee-9e56-1ae0df76880c">

**Comment by dsinghvi** [comment]
The docs field is available in the [backend](https://github.com/fern-api/fern-definition-registry/blob/d453892deaf2e63576f5252c48e7718db50ec4ec/fern/api/definition/api/v1/read/__package__.yml#L30) in the fern-definition-registry APIs.

**Comment by kafkas** [comment]
This is done.
