### ISSUE TITLE
Support searching in API Docs

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1817]
Fern documentation doesn't have search support. Adding search support means 1/ updating the backend to index information, 2/ exposing APIs for search, 3/ implementing the mocks to show search. 

Link to mocks [here](https://www.figma.com/file/sJfDzjYITYFQO5D7qNri2y/Fern?type=design&node-id=629-14508&mode=design&t=exZjKHE3eQE0kFWv-0): 

![Image](https://github.com/fern-api/fern/assets/10870189/3d1e405b-cb7e-4469-ad65-af71e65398b9)

**Comment by kafkas** [comment]
Done.
