### ISSUE TITLE
Add documentation for how to generate an OpenAPI spec from a backend

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1818]
In the Fern documentation, we should have a description of how to go from code to an OpenAPI definition for different server frameworks. I imagine this would go under the "Using OpenAPI" section of our docs.

For example:
FastAPI -> built-in
Django -> DRF Spectacular
Flask -> flask-rest-api

Express, Ruby on Rails, Go

**Comment by dannysheridan** [comment]
One company that uses Ruby uses ChatGPT to pass in a JSON Schema and get an OpenAPI spec

**Comment by AlgoDame** [comment]
Hi 👋 @dannysheridan, I would like to pick up this issue.

**Comment by dannysheridan** [comment]
Great, good to pick it up. Let me know if you have any questions! Excited to review the PR when ready.

**Comment by AlgoDame** [comment]
@dannysheridan, I just created a [PR](https://github.com/fern-api/fern/pull/1888) for this issue. Please can you review and let me know if this pr meets the expectation? If not, do let me know what you'll want improved.

**Comment by aevitas** [comment]
Closing via #1888
