### ISSUE TITLE
[Bug] Methods return void if the media type is backslash /

### ISSUE THREAD

**Issue by Norbo11** [fern-api/fern#1833]
When an OpenAPI spec contains a `*/*` response type for some endpoint, the generated client function does not return the model returned by the endpoint. It returns void instead.

For example, this spec:
```yaml
  /ledger/{id}/balance:
    get:
      tags:
      - ledger-api
      operationId: getLedgerBalance
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BalancePoint'
```

Generates this client method:

```typescript
    getLedgerBalance(id: number): Promise<void>;
```

Changing the `*/*` key nested under the `content` part of the response to `application/json` will generate the correct client method:

```typescript
    getLedgerBalance(id: number): Promise<FinanceApi.BalancePoint[]>;
```

`fern` should warn about such cases and maybe default to JSON so that it can attempt to do something useful if the OpenAPI spec is badly-behaved.

**Comment by dannysheridan** [comment]
We've done a lot of work on the OpenAPI importer since this was reported. Closing as stale. Open to re-engaging if this is blocking anyone.
