### ISSUE TITLE
Support linking to homepage in docs

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1836]
This feature is an end-to-end docs feature: 

1/ FDR (the docs backend) should support taking in homepage link
2/ Update the `docs-config` fern definition to take homepage link
2a/ Make sure you register the homepage link with fdr using the SDK 
3/ Consume homepage link on the frontend so that when a user clicks on the logo, they are redirected to homepage

**Comment by kafkas** [comment]
Done.
