### ISSUE TITLE
Change the yellow highlight color in search results

### ISSUE THREAD

**Issue by kafkas** [fern-api/fern#1839]
The `Highlight` component provided by Algolia's `react-instantsearch-hooks-web` package doesn't seem to allow configuring this color. We may want to try editing the underlying CSS.

https://github.com/fern-api/fern/blob/c76b12f0ad21b042f9feadb4256d0070caab79b3/packages/ui/app/src/search/SearchHit.tsx#L52-L56

What the new color should be is more of a design question, but we probably don't wanna be limited to yellow.

<img width="1038" alt="Screenshot 2023-07-05 at 1 00 24 AM" src="https://github.com/fern-api/fern/assets/36949216/3c80e072-6189-4210-9749-95f17d47ace6">

**Comment by dsinghvi** [comment]
@kafkas lets make the issues a bit more detailed (screenshot) + possibly linking to relevant code + potential ideas for fix (i.e. what should the highlight color be)

**Comment by kafkas** [comment]
It looks like this can be done natively with CSS with a pseudo-element called `::highlight()` but the API is very new and it is currently not supported by all browsers.

https://css-tricks.com/css-custom-highlight-api-early-look/#aa-browser-support
https://www.w3.org/TR/css-highlight-api-1/#custom-highlight-pseudo

**Comment by kafkas** [comment]
Closing as changing the highlight color is not possible and we've already disabled highlighting.
