### ISSUE TITLE
Use a single Algolia index for search

### ISSUE THREAD

**Issue by kafkas** [fern-api/fern#1846]
Algolia's index count limitation forces us to make a few adjustments to both our frontend and backend and switch to a structure where we maintain a single index for all customers. The current plan is:

**Frontend Changes:**
- New env var `ALGOLIA_INDEX_ID`
- Delete the `ALGOLIA_API_KEY` env var

**Algolia record schema changes:**
```
subIndexId`: String (new field)
```

**Prisma schema changes (DocsV2 model)**
```
searchApiKey: String? (new field)
algoliaSubIndexId: String? (rename from algoliaIndex)
```

**Flow**
- User runs `fern generate` to send a request to FDR
- We generate a new ID in the same way (fernDomain+uuid) and call it `subIndexId`
- We generate the new Algolia records in the same way except they now contain a `subIndexId` field. We save them to Algolia.
- We generate a new search api key for this specific documentation. We run the following:
```ts
const searchApiKey = algoliaClient.generateSecuredApiKey(privateKey, {
   filters: `subIndexId:${subIndexId}`
})
```
- We update the `algoliaSubIndexId` and `searchApiKey` when saving the docs definition to the db
- We mark the previous index for deletion in the same way except it's now subindex
- The frontend can now retrieve the `searchApiKey` and `algoliaSubIndexId`  and can use them to query the index. Since the API key has an embedded filter on the `subIndexId` attribute they will only see the results for that specific subindex.

**Background Job:**
Nothing changes except we now call index.deleteBy({ search: `subIndexId:${subIndexId}` })  instead of index.delete() .

See: [User-restricted access to data](https://www.algolia.com/doc/guides/security/api-keys/how-to/user-restricted-access-to-data/)
See: [Filters](https://www.algolia.com/doc/api-reference/api-parameters/filters/)

**Comment by kafkas** [comment]
Might want to call it "index segment" or "segment ID" if the term "subindex" seems less appealing.

**Comment by dsinghvi** [comment]
At register time, how do we make indexing "no-downtime" aka search always works

**Comment by dsinghvi** [comment]
Replaced by this [linear](https://linear.app/fern-api/issue/FER-21/use-single-search-index-for-algolia) issue
