### ISSUE TITLE
Docs outer container shouldn't be horizontally scrollable in mobile view

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1869]
![Image](https://user-images.githubusercontent.com/36949216/248773793-f5960398-6077-4927-a86b-162ebae25926.png)

The content should fit nicely into the container as it does for Stripe.

![Image](https://user-images.githubusercontent.com/36949216/248773974-7d2de22b-4214-4195-a06c-cdc5af9602e8.png)

**Comment by kafkas** [comment]
Done.
