### ISSUE TITLE
Improve READMEs and CONTRIBUTING for generator repositories

### ISSUE THREAD

**Issue by aevitas** [fern-api/fern#1870]
In an effort to better document the generators, add or update the readmes associated with the generator repositories to better enable users to work with them.

- [x] fern-api/fern-typescript README
- [x] fern-api/fern-python README
- [x] fern-api/fern-go README
- [x] fern-api/fern-java README
- [x] fern-api/fern-postman README
- [x] fern-api/fern-openapi README

**Comment by dannysheridan** [comment]
Postman: https://github.com/fern-api/fern-postman/pull/79

**Comment by aevitas** [comment]
Py: https://github.com/fern-api/fern-python/pull/306

**Comment by dannysheridan** [comment]
OpenAPI: https://github.com/fern-api/fern-openapi/pull/82

**Comment by aevitas** [comment]
Ah, I had that one ready to go as well -- didn't see you just opened that branch too.

**Comment by dannysheridan** [comment]
Will keep my PR. If you have any improvements, all ears.

Working on Go now. (Agreed with your comments!) Will have the author of the generator, Alex, review before merging.

**Comment by aevitas** [comment]
LGTM. For the Go one, I dug into the various modes a little bit. There's the possibility of generating Go in its own package, but also just as a plain codegen to embed in an existing project, i.e. without its own `go.mod`. That's something that's unique to that generator, but it felt unique in more ways than just that, e.g. where it resolves its inputs from (does it do it from the host system? how does that work if the generator runs in a Docker container in the cloud?)

Just my notes, you're probably aware of all this stuff, but I think that should end up in the readme one way or another.

**Comment by dannysheridan** [comment]
https://github.com/fern-api/fern-go/pull/18

**Comment by dannysheridan** [comment]
I missed adding CONTRIBUTING.md to each of the repos. (Glad I checked all of the links.)

 Add to Typescript
 Add to https://github.com/fern-api/fern-java/pull/291
 Add to https://github.com/fern-api/fern-go/pull/19
 Add to Python
 Add to Postman
 Add to OpenAPI

**Comment by aevitas** [comment]
Contribs PR for Java: https://github.com/fern-api/fern-java/pull/292

**Comment by dannysheridan** [comment]
This issue is pending resolution until the following PRs are merged:
* https://github.com/fern-api/fern-python/pull/306 
* https://github.com/fern-api/fern-java/pull/291

**Comment by Leojack11** [comment]
Rocket 🚀

**Comment by dsinghvi** [comment]
Going to close this issue on the root repo and we can update accordingly in each generator repo
