### ISSUE TITLE
Move Fern documentation to Fern's own documentation solution

### ISSUE THREAD

**Issue by aevitas** [fern-api/fern#1871]
Fern offers a strong documentation offering built in to the toolkit that allows developers to easily document their APIs. The Vellum documentation runs on this solution: https://docs.vellum.ai/api-reference/generate

However, Fern's own documentation currently does not. Let's fix that.

- [x] Move documentation into its own repository (fern-api/docs)
- [x] Change documentation to use fern's own solution
- [x] Implement GitHub actions to automate generation and deployments for documentation

**Comment by dannysheridan** [comment]
Down to code review when ready

**Comment by aevitas** [comment]
@dannysheridan There's an initial setup on the main branch of https://github.com/fern-api/docs already - figured since it's a carbon copy of the original docs there wasn't much to review.

I've currently published it to https://aevitas.docs.buildwithfern.com/ but it has some formatting issues, like none of the markdown elements look right. How can I best fix this?

**Comment by dannysheridan** [comment]
I just added GitHub Actions to update the docs on release. I also renamed the docs URL to `staging.docs.buildwithfern.com` .

Ran into an issue here (https://github.com/fern-api/docs/actions/runs/5605814129/jobs/10255342974) that I hope to resolve promptly.

**Comment by dannysheridan** [comment]
Thanks, I just made a few commits to that repo. Changes including:
* org name to `fern`
* docs link to `staging.docs.buildwithfern.com`
* added logo and favicon

Formatting issues are going to require a deeper dive from @kafkas

**Comment by dannysheridan** [comment]
I missed adding `CONTRIBUTING.md` to each of the repos. (Glad I checked all of the links.)

- [x] Add to Typescript
- [ ] Add to Java
- [ ] Add to Go
- [ ] Add to Python
- [ ] Add to Postman
- [ ] Add to OpenAPI

**Comment by kafkas** [comment]
> Formatting issues are going to require a deeper dive from @kafkas
Yeah, I think this is because the mdx and md renderers are currently using different settings. We probably need to file a separate issue for that.

**Comment by dannysheridan** [comment]
@kafkas good thinking.

Using `.md`:
<img width="1389" alt="Screenshot 2023-07-24 at 19 04" src="https://github.com/fern-api/fern/assets/83524670/b8621e5e-37b9-4736-b8a4-3828746dc5e3">


Using `.mdx`:
<img width="1278" alt="Screenshot 2023-07-24 at 19 04" src="https://github.com/fern-api/fern/assets/83524670/68b19465-d6fa-4d07-aa61-59e8805a7c32">

Action: I am going to convert our docs to `.md`

**Comment by zachkirsch** [comment]
btw I think the goal should be to deprecate and delete support for .md - I just left support around for .md to be backcompat

**Comment by dannysheridan** [comment]
that's very helpful context. sounds like we should fix the `.mdx` rendering. will not proceed with my changes.

**Comment by zachkirsch** [comment]
sg, and depending on the priority of this ticket it's totally fine to use .md for now

**Comment by dannysheridan** [comment]
This issue is pending resolution until we go live with the new documentation website.
