### ISSUE TITLE
Document dependencies for the node client

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1878]
There are dependencies required but not documented, such as:
* @ungap/url-search-params
* axios
* url-join

These dependencies are a good list to document: https://github.com/FlatFilers/flatfile-node/blob/main/package.json

**Comment by dsinghvi** [comment]
@AlgoDame, @aevitas is actually owning this issue. Do you want to pick up another one instead?

**Comment by AlgoDame** [comment]
Yeah. Can you point some high priority ones to me? @dsinghvi

**Comment by aevitas** [comment]
Will be completed once https://github.com/fern-api/fern-typescript/pull/489 goes through.

**Comment by dannysheridan** [comment]
complete with https://github.com/fern-api/fern-typescript/pull/489

**Comment by jasontlouro** [comment]
Where are these dependencies @dannysheridan ? PR link is broken

**Comment by dannysheridan** [comment]
@jasontlouro https://github.com/webflow/js-webflow-api/blob/47496a1d65a57b755129726664ad868237ef474e/package.json#L14-L22
