### ISSUE TITLE
Give code blocks a `max-width`

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1898]
<img width="1678" alt="Screen Shot 2023-07-13 at 1 34 06 PM" src="https://github.com/fern-api/fern/assets/10870189/408d3b76-f9d6-4633-90e6-d02e02abc753">

Link: https://primer.docs.dev.buildwithfern.com/api-reference/payments-api/search-list-payments

**Comment by kafkas** [comment]
Done.
