### ISSUE TITLE
Handle URL overflow in docs

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1899]
<img width="656" alt="Screen Shot 2023-07-13 at 1 40 57 PM" src="https://github.com/fern-api/fern/assets/10870189/c2a323aa-83ed-4dcc-80b4-26b269399718">

https://primer.docs.dev.buildwithfern.com/api-reference/payment-methods-api/save-a-payment-method-token

**Comment by kafkas** [comment]
Done.
