### ISSUE TITLE
Properly handle large numbers of enum values in the docs UI

### ISSUE THREAD

**Issue by kafkas** [fern-api/fern#1914]
We probably don't want to render the entire enumeration as it takes a large amount of space.
<img width="565" alt="Screenshot 2023-07-16 at 7 17 26 PM" src="https://github.com/fern-api/fern/assets/36949216/38ab8ceb-d15e-44fd-8a9f-5e940906a34a">

**Comment by dsinghvi** [comment]
This is now tracked by this [linear issue](https://linear.app/fern-api/issue/FER-12/mocks-for-handling-several-enum-values)
