### ISSUE TITLE
Support `application/x-ndjson` Content Type in OpenAPI Importer

### ISSUE THREAD

**Issue by noanflaherty** [fern-api/fern#1923]
fern-generated API clients seem to return a type of `None` (in python) or `Promise<void>` in node if the response `content` property has a value of `application/x-ndjson`.

As a workaround, we must use `application/json` to get a correctly generated client, despite it being an inaccurate content type.

**Comment by dsinghvi** [comment]
This is now fixed https://github.com/fern-api/fern/pull/1939
