### ISSUE TITLE
Make sure jumps to anchors are not sudden when a page is opened for the first time 

### ISSUE THREAD

**Issue by kafkas** [fern-api/fern#1940]
When we navigate to a URL that contains a link to a section (e.g. https://vellum-staging.docs.dev.buildwithfern.com/api-reference/generate#generate-request-deployment_id) we want to make sure that the jump to that section is handled smoothly (i.e. no flickering/flashing). The ideal experience should resemble navigating to a Stripe page section https://stripe.com/docs/api/customers/update#update_customer-description

**Comment by dsinghvi** [comment]
Moving this ticket to [linear](https://linear.app/fern-api/issue/FER-36/jumps-to-anchors-should-not-be-sudden-on-link-open)
