### ISSUE TITLE
Implement overflow ellipsis for EndpointUrl

### ISSUE THREAD

**Issue by kafkas** [fern-api/fern#1948]
Ideally, we want something like a text ellipsis when the url overflows but since we're dealing with nested \
\<span\> elements (to support path parameter highlighting) that can't be flattened, it looks like we can't implement it with CSS. We need a way of detecting collisions/overflow programmatically and hide the overflowing parts of the url accordingly.

<img width="462" alt="Screenshot 2023-07-23 at 11 07 12 PM" src="https://github.com/fern-api/fern/assets/36949216/4d27f829-99f7-45cb-bc8a-55318e37d2fb">

**Comment by zachkirsch** [comment]
I would use https://blueprintjs.com/docs/#core/components/overflow-list, it works great and is totally unstyled (i.e. the component is just the logic and we can control the styling)

**Comment by kafkas** [comment]
Looks promising! Will give that a try.

**Comment by dsinghvi** [comment]
Closing in favor of a design ticket in [linear](https://linear.app/fern-api/issue/FER-15/mocks-for-rendering-the-full-url-vs-path)
