### ISSUE TITLE
Don't require login from the CLI if generating code locally

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1955]
`fern login` is for monitoring and controlling access to premium features (like publishing and API documentation generation).

If a user wants to try Fern's free tier without logging in, they should be able to. The `--skip-login` flag may be a good option.

**Comment by dsinghvi** [comment]
@mjperrone @aevitas @kikones34 @MarcSalvat, I'm closing this issue in favor of this one: https://github.com/fern-api/fern/issues/2003. 

If you have any comments on the proposal in the issue, let me know!
