### ISSUE TITLE
TableOfContents in custom markdown page is taking too much space

### ISSUE THREAD

**Issue by kafkas** [fern-api/fern#1956]
It's currently pushing the main content to the left, reducing its width. We want to make sure it's not taking too much space.

<img width="1316" alt="Screenshot 2023-07-25 at 12 37 27 AM" src="https://github.com/fern-api/fern/assets/36949216/c2c45f15-3a3a-488e-95ca-c003bd1621d0">

**Comment by dsinghvi** [comment]
Issue moved to [linear](https://linear.app/fern-api/issue/FER-34/table-of-contents-in-custom-markdown-takes-too-much-space)
