### ISSUE TITLE
Hide table of contents when it has no items

### ISSUE THREAD

**Issue by kafkas** [fern-api/fern#1963]
<img width="536" alt="Screenshot 2023-07-25 at 1 30 20 PM" src="https://github.com/fern-api/fern/assets/36949216/ff516e34-72c8-4edc-86f4-f20735bd8ba5">

**Comment by dsinghvi** [comment]
Moved to [Linear](https://linear.app/fern-api/issue/FER-33/hide-table-of-contents-in-docs-when-there-are-no-sub-headings)
