### ISSUE TITLE
API-wide error configuration ignored by FastAPI

### ISSUE THREAD

**Issue by stephenkao** [fern-api/fern#1966]
It looks like API-wide errors are ignored by FastAPI.  Following [this section in the docs](https://www.buildwithfern.com/docs/definition/api-yml#api-wide-errors), I have the following configuration:

```
# in common.yml:
errors:
  InsufficientPermissionsException:
    status-code: 401
```

```
# in api.yml
imports:
  common: ./internal/common.yml

errors:
  - common.InsufficientPermissionsException
```

Making a request with insufficient permissions (therefore raising said exception) still logs out the following warning:

```
Endpoint ‘...’ unexpectedly threw InsufficientPermissionsException. If this was intentional, please add InsufficientPermissionsException to the endpoint's errors list in your Fern Definition.
```

See [Discord thread](https://discord.com/channels/988611740499574794/988611741476859916/1133449830488870922).

Thanks in advance!

**Comment by dannysheridan** [comment]
this hasn't been requested again since July 2023, closing and will reopen if others want this!
