### ISSUE TITLE
Document Typescript generator custom configs

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1978]
Add to buildwithfern.com/docs

[Source code](https://github.com/fern-api/fern-typescript/blob/7c85a6f37c640317e73fb904968126aa816e43c5/packages/generators/sdk/cli/src/custom-config/schema/SdkCustomConfigSchema.ts#L4-L26)

Here's the list as of today:
```
    useBrandedStringAliases
    private: z.optional(z.boolean()),
    neverThrowErrors: z.optional(z.boolean()),
    namespaceExport: z.optional(z.string()),
    outputEsm: z.optional(z.boolean()),
    outputSourceFiles: z.optional(z.boolean()),
    includeCredentialsOnCrossOriginRequests: z.optional(z.boolean()),
    bundle: z.optional(z.boolean()),
    allowCustomFetcher: z.optional(z.boolean()),
    requireDefaultEnvironment: z.optional(z.boolean()),
    defaultTimeoutInSeconds: z.optional(z.union([z.literal("infinity"), z.number()])),
    skipResponseValidation: z.optional(z.boolean()),
    extraDependencies: z.optional(z.record(z.string())),
    treatUnknownAsAny: z.optional(z.boolean()),
    noSerdeLayer: z.optional(z.boolean()),
```

**Comment by zachkirsch** [comment]
I just added these to the fern-typescript readme!

**Comment by dannysheridan** [comment]
Is the PR merged? 

<img width="1322" alt="Screenshot 2023-07-26 at 19 04" src="https://github.com/fern-api/fern/assets/83524670/db655d65-f30e-49a2-bf5e-a1a739e072a0">

**Comment by zachkirsch** [comment]
It’s in the readme https://github.com/fern-api/fern-typescript

**Comment by dsinghvi** [comment]
Closing this issue because it should be filed on `fern-typescript`
