### ISSUE TITLE
Create APIs by the CLI with a explicit name

### ISSUE THREAD

**Issue by danielkocot** [fern-api/fern#2017]
When I use `fern init` new folder named `api` is created. If I created a second API is named `api-1`. I can't find anything in the documentation about naming the APIs from the beginning. And not only rename the folder afterwards. Would be good to have something for a better developer experience  available in the near future :).

**Comment by dannysheridan** [comment]
closing as this is a good idea but can be easily mitigated right now by renaming the file manually
