### ISSUE TITLE
[Bug] Support escaping tags that begin with numbers

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2018]
Tags that begin with numbers cause fern generated code to fail to compile. Fern should prefix any tags with an underscore. 

For example: 
```yaml
paths: 
  /my/path: 
    tag: 
      - 4dimensional
```

will generate a Fern definition 
```yaml
definition/
  4dimensional.yml
```

which will generate code
```python
class Client: 
  def __init__(...): 
    self.4Dimensional = new 4DimensionalClient(); # <----- fails to compile
```

Instead the generator should generate 
```python
class Client: 
  def __init__(...): 
    self._4dimesional = new _4DimensionalClient(); # <----- compiles
```

**Comment by perintyler** [comment]
Hey, @dannysheridan asked me to take a crack at this ticket, and I have a few clarification questions.

### Question 1)

In [fern's documentation for importing openapi](https://buildwithfern.com/docs/spec/extensions), it describes an extensions that can be used to set the group name for a path: `x-fern-sdk-group-name`:

```
The OpenAPI below will client.users.create():

paths:
  /users
    post:
      x-fern-sdk-group-name: users
      x-fern-sdk-method-name: create
```


As I understand it, the `x-fern-sdk-group-name` field indicates which package a path belongs to; the package will be defined in the `definition` directory. Similarly, this ticket explains that the package can be set using the `tags` key. (Note: the ticket description actually uses `tag`, but I assume this is a typo -- the test snapshots use the plural version: `tags`). So do `x-fern-sdk-group-name` and `tags` serve the same exact purpose? Is there any difference between the two keys?

### Question 2)

At what stage should the tag be prefixed with an underscore? 

Correct me if I'm wrong, but as I understand it, the process for importing an openAPI file and generating source code for a python API (as described in the ticket) occurs in __3__ stages:

1. Convert `openapi.json` to `IR`: a yml file that uses fern's own custom schema
- This happens in `cli/openapi-parser`
- - openapi-parser input: an openapi `JSON` file
- - openapi-parser output: an IR `YML` file

2. Convert `IR` file to a `fern` directory structure: YML definition files and a generator file for configuring the output location for each generator SDKs.
- This happens in `cli/openapi-ir-to-fern`
- - openapi-ir-to-fern input: an IR `YML` file
- - openapi-ir-to-fern output: `fern/api/generators.yml`, `fern/fern.config.json`,  `fern/api/openapi/api.yml`, and the `fern/definition` directory

3. Generate python code based on the specs outline in the generated `fern` directory.
- This happens in `fern-python`
- - fern-python input: a fern directory
- - fern-python output: a `generated` directory containing source code for a `python` API

I would think that you'd want tag names to match across the openapi file, IR file, and fern files. If so, it would make sense to implement the underscore prefixing in the `fern-python` repo. The downside of this approach is that every generator SDK would need to do the same. Instead, it seems like this ticket is suggesting that the tag name should be prefixed when generated the `IR` file. Is that correct?

> If the answer to my question is 'yes', then I'm thinking that a good place to implement the underscore prefixing would be in [cli/openapi-parser/converters/convertPathItem.ts](https://github.com/fern-api/fern/blob/fbf43e2465d2cddca44ca79327f3de80fad59537/packages/cli/openapi-parser/src/v3/converters/convertPathItem.ts)

### Questions 3)

In `cli/generation/ir-generator/casings/CasingsGenerator.ts`, there's a function called `constructCasingsGenerator`, which returns an object that looks like this:

```json
{
    "originalName": "string",
    "camelCase": "string",
    "snakeCase": "string",
    "screamingSnakeCase": "string",
    "pascalCase": "string"
}
```

> [snapshot of IR generated by `cli/generation/ir-generator` that uses the name casing object](https://raw.githubusercontent.com/fern-api/fern/fbf43e2465d2cddca44ca79327f3de80fad59537/packages/cli/generation/ir-generator/src/__test__/__snapshots__/generateIntermediateRepresentation.test.ts.snap)


Do `IR` files generated by `fern init --openapi` (i.e. the openapi importer) follow a different schema than `IR` files generated by the standard `fern init` command? If so, should `openapi` casing generator be imported or re-implemented inside the `cli/openapi-parser` package? As I understand it, doing so would fix the problem described in this ticket.

**Comment by dsinghvi** [comment]
@perintyler really impressed with your ability to dive into the code and come up with a solution -- you are right that the casings generator is a good place to do this.
