### ISSUE TITLE
Add Support for Pydantic v2 to Python Client Generator

### ISSUE THREAD

**Issue by noanflaherty** [fern-api/fern#2075]
The fern python client generator currently generates clients using Pydantic v1.x.x. However, Pydantic v2.x.x has since been released and is incompatible. This prevents folks who use Pydnatic v2.x.x from using fern-generated python clients.

See issue here as an example: https://github.com/vellum-ai/vellum-client-python/issues/7

**Comment by abeerag** [comment]
We use the Vellum API and need support for pydantic==2.4.0

**Comment by dsinghvi** [comment]
@abeerag we recently released a version of the python generator that is compatible with pydantic 2+. Vellum's latest Python SDK is now updated as well. 

Closing this issue, but feel free to reopen!

**Comment by ashb** [comment]
```python
try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore
```

I would call this "barely" compatible with Pydantic v2. Yes it works, but it uses almost none of the new features.
