### ISSUE TITLE
[Bug] Generator fails when a discriminant value starts with a number

### ISSUE THREAD

**Issue by kikones34** [fern-api/fern#2094]
I have the following enum type in my API definition:

```json
"DetectorType": {"type": "string", "enum": ["person", "face", "4w_vehicle"]
```

When attempting to generate a Java SDK, it fails with the following error:

```
[api]: fernapi/fern-java-sdk not a valid name: 4WVehicle
```

Note that the same specification works without issue when generating a Python SDK.
I'm using the latest stable versions Fern 0.14.3 and Java generator 0.3.7.

----

As a side note, it was impossible for me to see where the issue was when executing the generator with the `--local` option, as it just says:

```
[api]: fernapi/fern-java-sdk Docker exited with a non-zero exit code.
```
And using `--log-level debug` yielded the following undecipherable traceback:

```
DEBUG 2023-09-06T14:01:02.032Z [api]: fernapi/fern-java-sdk Error: Docker exited with a non-zero exit code.
                                                                at tryRunDocker (/home/k34/.nvm/versions/node/v20.5.0/lib/node_modules/fern-api/bundle.cjs:549185:11)
                                                                at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                                                at async runDocker (/home/k34/.nvm/versions/node/v20.5.0/lib/node_modules/fern-api/bundle.cjs:549159:5)
                                                                at async runGenerator (/home/k34/.nvm/versions/node/v20.5.0/lib/node_modules/fern-api/bundle.cjs:549253:3)
                                                                at async writeFilesToDiskAndRunGenerator (/home/k34/.nvm/versions/node/v20.5.0/lib/node_modules/fern-api/bundle.cjs:549311:3)
                                                                at async /home/k34/.nvm/versions/node/v20.5.0/lib/node_modules/fern-api/bundle.cjs:549272:9
                                                                at async TaskContextImpl.runInteractiveTask (/home/k34/.nvm/versions/node/v20.5.0/lib/node_modules/fern-api/bundle.cjs:534309:7)
                                                                at async Promise.all (index 0)
                                                                at async runLocalGenerationForWorkspace (/home/k34/.nvm/versions/node/v20.5.0/lib/node_modules/fern-api/bundle.cjs:549267:19)
                                                                at async generateWorkspace (/home/k34/.nvm/versions/node/v20.5.0/lib/node_modules/fern-api/bundle.cjs:550066:5)
```

**Comment by kikones34** [comment]
Actually, I think this issue may have been solved in this commit, although not 100% certain: https://github.com/fern-api/fern/commit/4cfa6ba096bff0f4593a8b5ee9d688554cc67e68

**Comment by kikones34** [comment]
Hi @dannysheridan, thanks for the fast reply! I didn't notice 0.3.7 was not the latest version, sorry.
I tried both 0.4.9 and 0.5.0-rc0, but both still result in the same error.

**Comment by dannysheridan** [comment]
Helpful info. Adding @dsinghvi to take a look

**Comment by kikones34** [comment]
For the record, I have tried using Fern 0.15.0-rc13, but I cannot get it to work, it complains about the specification:

```
api.yml -> name
Incorrect type
Expected string but received undefined
api.yml
Unexpected key
Encountered unexpected key openapi
api.yml
Unexpected key
Encountered unexpected key info
api.yml
Unexpected key
Encountered unexpected key paths
api.yml
Unexpected key
Encountered unexpected key components
```

**Comment by dsinghvi** [comment]
@kikones34 upgrading to the latest rc will work. The only trick is that when you upgrade you can move everything in the `api` directory up one level. 

Here's what you want to modify the directory structure to: 
```bash
fern/
  openapi/
     openapi.json # or yaml
  generators.yml
  fern.config.json
```

**Comment by kikones34** [comment]
Thanks for the info, Fern now parses the specification correctly. However, it seems the enum still causes an issue (although the error is ever so slightly different):

```
[api]: fernapi/fern-java-sdk not a valid name: 4WVehicleValue
```

Tested with Fern 0.15.0-rc13 and Java generator 0.4.9 and 0.5.0-rc0, with the same result.

**Comment by dsinghvi** [comment]
Got it -- we'll push a fix by end of week. Is that timeline okay? 

There are 2 potential ways to unblock temporarily: 
1/ Comment out that one enum value, to generate the rest of the SDK. 
2/ Use the x-fern-enum extension to provide your own enum name that is valid and doesn't start with a number. Docs [here](https://buildwithfern.com/docs/spec/extensions#enum-descriptions-and-names).

**Comment by kikones34** [comment]
The enum was not actually causing the issue, it's the following discriminator:

```
"discriminator": {
    "propertyName": "type",
    "mapping": {
        "4w_vehicle": "#/components/schemas/TargetFiltersVehicle",
        "face": "#/components/schemas/TargetFiltersFace",
        "person": "#/components/schemas/TargetFiltersPerson"
    }
}
```

If I remove the `4` from there, then the generation works (without needing to change anything about the enum).

**Comment by kikones34** [comment]
Hi, any updates on this?

**Comment by dsinghvi** [comment]
> Hi, any updates on this?

@kikones34 can we get a minimal OpenAPI spec to reproduce this with? Maybe just a spec with that union?

**Comment by kikones34** [comment]
The following spec reproduces the error for me:

```yaml
openapi: 3.1.0
info:
  title: Test
  version: 0.1.0
paths:
  /search:
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Person'
                - $ref: '#/components/schemas/Vehicle'
              discriminator:
                propertyName: entity_type
                mapping:
                  person: '#/components/schemas/Person'
                  4w_vehicle: '#/components/schemas/Vehicle'
components:
  schemas:
    Person:
      properties:
        entity_type:
          const: person
        age:
          type: integer
      type: object
      required:
        - entity_type
    Vehicle:
      properties:
        entity_type:
          const: 4w_vehicle
        brand:
          type: string
      type: object
      required:
        - entity_type
```

**Comment by kikones34** [comment]
Can I help in any other way? (Well, besides taking a look at the source code, which I may consider if I have the time).

**Comment by kikones34** [comment]
I've been looking into this, here's what I've found.

First, the IR for the enum doesn't case any issues, since it replaces `4` by `FOUR`:
```json
{
    "name": {
        "originalName": "FourWVehicle",
        "camelCase": {
            "unsafeName": "fourWVehicle",
            "safeName": "fourWVehicle"
        },
        "snakeCase": {
            "unsafeName": "four_w_vehicle",
            "safeName": "four_w_vehicle"
        },
        "screamingSnakeCase": {
            "unsafeName": "FOUR_W_VEHICLE",
            "safeName": "FOUR_W_VEHICLE"
        },
        "pascalCase": {
            "unsafeName": "FourWVehicle",
            "safeName": "FourWVehicle"
        }
    },
    "wireValue": "4w_vehicle"
}
```
(Note: not sure why the `originalName` is also changed).

However, the IR for the discriminant value is different, it maintains the original name for the `unsafeName` fields:
```json
{
  "name": {
      "originalName": "4w_vehicle",
      "camelCase": {
          "unsafeName": "4WVehicle",
          "safeName": "_4WVehicle"
      },
      "snakeCase": {
          "unsafeName": "4_w_vehicle",
          "safeName": "_4_w_vehicle"
      },
      "screamingSnakeCase": {
          "unsafeName": "4_W_VEHICLE",
          "safeName": "_4_W_VEHICLE"
      },
      "pascalCase": {
          "unsafeName": "4WVehicle",
          "safeName": "_4WVehicle"
      }
  },
  "wireValue": "4w_vehicle"
}
```

Then, the Java generator uses this `unsafeName` to generate a class name:
```java
@Override
public ClassName getUnionSubTypeWrapperClass() {
    return getUnionClassName()
            .nestedClass(singleUnionType
                            .getDiscriminantValue()
                            .getName()
                            .getPascalCase()
                            .getUnsafeName() + "Value");
}
```
(file is `UnionGenerator.java`).

This results in the invalid class name `4WVehicleValue`.

I'd do a PR to fix the issue, but I'm not sure if I understand the meaning of the `unsafeName` fields. From what I've gathered, these should be names that are generally valid identifiers, but that may be language keywords, correct? So `4WVehicle` is not a valid `unsafeName` since it's not a valid identifier. If that's the case, then I propose to handle the discriminant values in the same way as enum values and transform numbers to words ("4w_vehicle" -> "four_w_vehicle").

Otherwise, just changing `getUnsafeName` to `getSafeName` would fix the issue, but I don't think that's what we want to do? @dsinghvi input appreciated.
