### ISSUE TITLE
Inconsistent IR for implicit root packages

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2212]
If the user defines a `config.yml` and `config/__package__.yml`, Fern consolidates the two files into a single subpackage. However, if `config.yml` defines a service, the Fern filepath between the subpackage and the service defined within it don't match. 

To be clear, the `fernFilepath` for the subpackage looks like the following:

```json
{
  "packagePath": [
      {
          "originalName": "config",
          "camelCase": {
              "unsafeName": "config",
              "safeName": "config"
          },
          "snakeCase": {
              "unsafeName": "config",
              "safeName": "config"
          },
          "screamingSnakeCase": {
              "unsafeName": "CONFIG",
              "safeName": "CONFIG"
          },
          "pascalCase": {
              "unsafeName": "Config",
              "safeName": "Config"
          }
      }
  ],
  "file": null
},
```

Whereas the service's `fernFilepath` looks like the following:

```json
{
  "packagePath": [],
  "file": {
      "originalName": "config",
      "camelCase": {
          "unsafeName": "config",
          "safeName": "config"
      },
      "snakeCase": {
          "unsafeName": "config",
          "safeName": "config"
      },
      "screamingSnakeCase": {
          "unsafeName": "CONFIG",
          "safeName": "CONFIG"
      },
      "pascalCase": {
          "unsafeName": "Config",
          "safeName": "Config"
      }
  }
```

This also leads us to ask - should we even only this confusing merging logic to happen? If a user defines a `config.yml`, should `fern` complain if a `config/__package__.yml` also exists? We already disallow a `service` from being defined in both files (since they share the same scope), so it might be best to prevent this from happening in general.

**Comment by dannysheridan** [comment]
moving to linear: https://linear.app/fern-api/issue/FER-664/[feature]-inconsistent-ir-for-implicit-root-packages
