### ISSUE TITLE
[Feature] Support command clicking in Fern YAML Definitions

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2250]
**Is your feature request related to a problem? Please describe.**
Support command clicking when navigating the Fern Definition (something similar to https://github.com/42Crunch/vscode-openapi). 

**Additional context**
Each IDE will likely require its own plugin: VsCode, PyCharm, etc.

**Comment by dannysheridan** [comment]
won't be prioritizing in the coming months, can reopen in the future if this request comes up again
