### ISSUE TITLE
[Bug] OpenAPI importer hard failure when "endpoint name" overlaps

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2258]
**Describe the bug**
When i ran `fern check` with my OpenAPI spec I got

```
The OpenAPI Spec has conflicting sdk method names. See POST /my/path
```

This error is hard to fix because it doesn't list what endpoints are conflicting + its probably better to emit a warning instead of a hard failure. 

**To Reproduce**

Run `fern check` on https://github.com/Propify-API/propify-docs/blob/74654c181eeff250e49ed43d4a227b0183ba567c/fern/openapi/openapi.yml

**Additional context**
As an initial step, improving the error messaging and suggesting remediation would be better.

**Comment by charliettaylor** [comment]
Hello, I'd like to try this issue out but it looks like the link you sent 404s now. Would you mind giving another yml to recreate this with? Any other info on how to start contributing would be appreciated too, thanks!

**Comment by dsinghvi** [comment]
Hey @charliettaylor ofcourse: 

```yaml
openapi: 3.0.0
info:
  title: Minimal API
  version: 1.0.0
paths:
  /hello:
    get:
      x-fern-sdk-method-name: hello
      summary: Get a friendly greeting
  /helloV2:
    get:
      x-fern-sdk-method-name: hello
      summary: Get a friendly greeting
```

is a minimally reproducible example and the error is thrown [here](https://github.com/fern-api/fern/blob/0d2e523de4e2853bed1a70e2fae33727dcefe46e/packages/cli/openapi-ir-to-fern/src/converters/convertToServices.ts#L51). 

Some context about our OpenAPI importer, we have 2 stages: 
- openapi-parser ([link](https://github.com/fern-api/fern/tree/0d2e523de4e2853bed1a70e2fae33727dcefe46e/packages/cli/openapi-parser)) -- The parser converts the OpenAPI into a structured format that we call OpenAPI IR. The schema of OpenAPI IR is [here](https://github.com/fern-api/fern/blob/0d2e523de4e2853bed1a70e2fae33727dcefe46e/fern/openapi-ir/definition/finalIr.yml#L6-L21)
- openapi-ir-to-fern([link](https://github.com/fern-api/fern/tree/0d2e523de4e2853bed1a70e2fae33727dcefe46e/packages/cli/openapi-ir-to-fern)) -- This package takes the aforementioned IR and turns it into a fern definition.

**Comment by dsinghvi** [comment]
The easiest change to make here is that instead of throwing an exception, we log an error message that a specific path or endpoint will be skipped when generating the SDK.

**Comment by charliettaylor** [comment]
Perfect, I'll start messing with it later tonight. Thanks!
