### ISSUE TITLE
[Bug] yml file naming collisions can create unnecessary imports

### ISSUE THREAD

**Issue by wwohlers** [fern-api/fern#2262]
**Describe the bug**
If Fern definition file `/foo/__package__.yml` imports `/bar.yml`, and there also exists a `/bar/__package__.yml` file, then the code generated for `Foo` will import *both* the code generated for `/bar.yml` and the code generated for `/bar/__package__.yml`. This can create unnecessary import cycles.

**To Reproduce**
Steps to reproduce an unnecessary import cycle:

1. Create a definition file `/bar.yml` with a type `BarUtil`.
2. Create a definition file `/foo/__package__.yml` with a type `Foo` that depends on `BarUtil`. Import `/bar.yml` as `bar` (I'm not sure if the import name is critical to reproducing, but I figured it might be).
3. Create a definition file `/bar/__package__.yml` with a type `Bar` that depends on both `BarUtil` and `Foo`. Import `/bar/__package__.yml` as `bar` (again, I'm not sure if the import name is critical).
4. Generate Python code, and observe the import cycle.

**Expected behavior**
There shouldn't be an import cycle. `Foo` depends on `BarUtil`. `Bar` depends on `BarUtil` and `Foo`. There is no cycle in this dependency graph. However, for some reason (likely confusion from the similar names `/bar.yml` and `/bar/__package__.yml`, and possibly exacerbated by the two files being imported under the same name `bar`), the Python code generated from `/foo/__package__.yml` will unnecessarily import the code generated from `/bar/__package__.yml`. This creates a dependency of `Foo` on `Bar`, which completes the import cycle `Foo --> Bar --> Foo`. 

**Desktop (please complete the following information):**

- OS: MacOS Sonoma 14.1
- Fern Version 0.15.0-rc31

**Comment by dannysheridan** [comment]
closing as stale and we haven't heard about this issue since
