### ISSUE TITLE
[Feature] SDK generators should create a user agent

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2264]
**Is your feature request related to a problem? Please describe.**
Today a Fern generated SDK does not create a user-agent. 

Each generated SDK should send a `User-Agent` header that is formatted with something like 
```
<package>/<language>/<version>
```

In practice, this may look like
```
cohere-ai/typescript/7.2.0
com.cohere/java/1.0.0
```

**Describe the solution you'd like**
Step 1: Introduce the `user agent` field into the IR
Step 2: Update the code generators to use the user agent field to send headers

**Additional Context** 
MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
gRPC: https://grpc.github.io/grpc/core/md_doc__p_r_o_t_o_c_o_l-_h_t_t_p2.html

**Comment by kisharnath** [comment]
hey can I work on this?

**Comment by dsinghvi** [comment]
@kisharnath sure: 

Steps you'll need to take: 
1) Add a `userAgent` field to the intermediate representation (https://github.com/fern-api/fern/tree/main/fern/ir-types-v29) 
2) Populate the field in `generateIntermediateRepresentation.ts`
3) After that merges, new SDKs for the Intermediate Representation will be published
4) Upgrade the Python/Java/Go/TypeScript generators to read this new field and send a user agent

**Comment by dannysheridan** [comment]
Note: this was closed as stale and is not completed.
