### ISSUE TITLE
[Bug] Almost all links on docs.buildwithfern.com are broken

### ISSUE THREAD

**Issue by mstade** [fern-api/fern#2267]
**Describe the bug**

I'm trying to learn more about Fern, and specifically it's API definition format. I started with the [API Definition page](https://docs.buildwithfern.com/api-definition), and clicked "Read more" later in the page, which links to https://docs.buildwithfern.com/compiler/cli-reference.mdx#fern-write-definition. Clicking that link opens a new window which is confusing all by itself, but it then redirects to https://docs.buildwithfern.com/. It took me a few times clicking various links to understand that the links are broken, it isn't just that all of them point to this one page.

**To Reproduce**

1. Go to almost any page
2. Click on almost any link (in-page anchors seem to work, mostly)
3. Have a new window open and redirect you to https://docs.buildwithfern.com/

**Expected behavior**
I expect the links to work, and be relevant.

**Screenshots**

https://github.com/fern-api/fern/assets/605731/a0705b5b-6dad-44e6-8398-d11c66103e85

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 119

**Additional context**
n/a

**Comment by dsinghvi** [comment]
@mstade thanks for filing this issue and you're 100% right that there are several links broken. 

I've started fixing a couple in this PR: https://github.com/fern-api/docs/pull/58

**Comment by dannysheridan** [comment]
fixed the broken links with improvements made by @minaelee 🎆
