### ISSUE TITLE
[Bug] Docs do not have visible text when searching on a dark background

### ISSUE THREAD

**Issue by jatinsandilya** [fern-api/fern#2288]
**Describe the bug**
The fern generated docs do not have visible text on the selected text when searching on a dark background. 

This is on the default colour scheme. 

**To Reproduce**

1. Go to https://docs.revert.dev (or a fern generated docs page)
2. Click on search
3. Search for any term. 
4. Notice the dropdown's selected option has text that is not visible. 

**Expected behavior**

Text should be visible on the default color scheme. 

**Screenshots**

![Screenshot 2023-11-15 at 11 18 17 PM](https://github.com/fern-api/fern/assets/7681067/91a0cd7f-a5a9-4046-bf1d-3080dd35207a)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] Version 119.0.6045.123 (Official Build) (arm64)

**Additional context**

**Comment by dsinghvi** [comment]
@abvthecity im guessing we should use some basic contrast detection that you were mentioning before?

**Comment by abvthecity** [comment]
This should be fixed in https://github.com/fern-api/fern-ui/pull/273 which picks black/white text color based on luminosity of the accent-primary color (which is the search result selection's background color)
