### ISSUE TITLE
[Bug] SDK examples do not show up for dummy examples

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2293]
**Describe the bug**
SDK examples should use dummy examples if OpenAPI or Fern Definition examples are not specified. 

**Expected behavior**
If an endpoint has a missing examples it should fill them in to the best of its ability. Specifically: 
- Add up to n query parameters
- Add any required properties for the request
- Add all fields for the response

**Comment by dannysheridan** [comment]
Seems like is could be grouped with: https://github.com/fern-api/fern/issues/2373
