### ISSUE TITLE
[Feature] Render beta flag on fields that are marked in-development

### ISSUE THREAD

**Issue by adamsuskin** [fern-api/fern#2296]
**Is your feature request related to a problem? Please describe.**
We have fields in our API shapes that are in-development or beta. We'd like the Fern docs to automatically render a label that they are in beta like how the docs can for incubating endpoints and services.

**Additional context**
We use the `in-development` availability to mark our fields as beta.

**Comment by dsinghvi** [comment]
<img width="593" alt="Screenshot 2023-11-17 at 9 08 06 AM" src="https://github.com/fern-api/fern/assets/10870189/870d4562-dfe8-4467-822c-21a54f4b8f6c">

@abvthecity The docs currently render this beta tag at the endpoint level, but we'll want some similar version of it on fields as well

**Comment by dsinghvi** [comment]
@adamsuskin https://github.com/fern-api/fern/pull/2420 once this is released this issue should be fixed

**Comment by dannysheridan** [comment]
released https://github.com/fern-api/fern/pull/2420 and available https://docs.buildwithfern.com/api-definition/fern-definition/availability!
