### ISSUE TITLE
Support global `auth: true` in `api.yml`

### ISSUE THREAD

**Issue by Swimburger** [fern-api/fern#2299]
**Is your feature request related to a problem? Please describe.**
You can set `auth: true` on endpoints and on services, but not API wide. 
Our entire API requires auth.

**Describe the solution you'd like**
Let us set `auth: true` in api.yml

**Comment by kash2104** [comment]
Hi dsinghvi ,
Can I work on this issue?

**Comment by sainithin-5736** [comment]
Hi @Swimburger , Can I work on this issue?

**Comment by dannysheridan** [comment]
Confirming that in CLI version `0.46.13` this is now valid! Thanks for the suggestion.
