### ISSUE TITLE
[Bug] Fern Check doesnt throw error for: Examples are not supported for undiscriminated unions

### ISSUE THREAD

**Issue by damonbanks** [fern-api/fern#2324]
**Describe the bug**
When you add examples to undiscriminated Unions, either on the union itself or the endpoint example that references the union the `fern check` command doesn't find the issue.

```service:
  auth: true
  base-path: /roles
  audiences:
    - public
  endpoints:
    assign:
      path: /{roleId}
      method: POST
      docs: Assign an existing role to the specified actor in the specified resource context
      display-name: Assign a role
      path-parameters:
        roleId:
          docs: ID of the role to be assigned
          type: string
      request:
        name: AssignRoleRequest
        body:
          properties:
            testId:
              type: testIdUnion
              docs: The user, guest to assign the role to
      response: AssignRoleResponse
      errors:
        - commons.BadRequestError
        - commons.NotFoundError
      examples:
        - name: Example0
          path-parameters:
            roleId: ...
          request:
            actorId: $ActorIdUnion.UserId
          response:
            body: ...

types:
  ActorIdUnion:
    discriminated: false
    union:
      - commons.UserId
      - commons.GuestId
    examples:
      - name: UserId
        value: $commons.UserId.Example0
```

**To Reproduce**

1. Add an example on an undiscriminated
2. Run `fern check`. Everything looks okay
3. When you try to build the SDK you will get an error `Examples are not supported for undiscriminated unions`

**Expected behavior**
That `fern check` throws the `Examples are not supported for undiscriminated unions` error

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- Version 119.0.6045.159
- Fern Version: 0.15.3

**Comment by dsinghvi** [comment]
@damonbanks this should now be fixed
