### ISSUE TITLE
[Feature] Make `CodeBlocks` expandable

### ISSUE THREAD

**Issue by homanp** [fern-api/fern#2326]
**Is your feature request related to a problem? Please describe.**
Currently the code blocks in the `mdx` files have a scrollbar. They should be expanded all the way to mitigate unnecessary scrolling.

<img width="831" alt="Screenshot 2023-11-23 at 22 40 17" src="https://github.com/fern-api/fern/assets/2464556/c0bdabdb-263b-4e4d-b418-d105d0b54d03">

**Describe the solution you'd like**
Have all code blocks full expanded

**Comment by dannysheridan** [comment]
great idea, moving this to our internal linear to track this request
