### ISSUE TITLE
[Documentation] Configure whether a link should be opened in a new tab

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2347]
### What can be improved

If I click on the TypeScript SDK link here: https://docs.buildwithfern.com/overview/welcome/generators it opens the link as a new tab in my browser. That's not the behavior I'd expect. Is this configurable?

**Comment by dannysheridan** [comment]
this has since been solved and is live!

@minaelee agree that fixing the documented behavior is needed.

**Comment by minaelee** [comment]
https://github.com/fern-api/fern/pull/2879 documents the default link behavior
