### ISSUE TITLE
[Feature] Make it possible to add a `url` property to the `tabs` node in yml.

### ISSUE THREAD

**Issue by homanp** [fern-api/fern#2357]
**Is your feature request related to a problem? Please describe.**
It would be great if we could add links to external URLs in the `tabs` definition. Example: 
https://github.com/homanp/superagent/blob/main/fern/docs.yml#L7

**Describe the solution you'd like**
```
tabs: 
  discord: 
    url: # <------ if url prop present then it just links out
```

**Comment by mgregerson** [comment]
+1 as this is relevant to my current build.

**Comment by dsinghvi** [comment]
This is now possible https://buildwithfern.com/learn/docs/building-your-docs/navigation#tabs
