### ISSUE TITLE
[Bug] Fern Documentation doesn't correctly load nested anchor links

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2367]
**Describe the bug**
When i go to https://fern-preview-0fc7d854-84a7-4def-b1cc-edd5a25871e6.docs.buildwithfern.com/api-definition/fern-definition/packages#navigation, this doesn't load to the navigation sub header. 

**To Reproduce**
Go to https://fern-preview-0fc7d854-84a7-4def-b1cc-edd5a25871e6.docs.buildwithfern.com/api-definition/fern-definition/packages#navigation. 

**Expected behavior**
Loads at the navigation subheader

**Screenshots**
Where it loads
<img width="1728" alt="Screenshot 2023-11-27 at 6 33 49 PM" src="https://github.com/fern-api/fern/assets/10870189/2e770a14-df11-4cc4-980c-d5578212f8b2">

Where I expect it should load
<img width="1611" alt="Screenshot 2023-11-27 at 6 34 07 PM" src="https://github.com/fern-api/fern/assets/10870189/c95bf2ec-69d1-4b0e-a367-f21d7fa19b6b">

**Comment by dannysheridan** [comment]
this has been fixed and works as expected
