### ISSUE TITLE
[Bug] IR should return a required property for terminator in StreamingResponse

### ISSUE THREAD

**Issue by mmolash** [fern-api/fern#2368]
**Describe the bug**
Currently, the IR returns an optional property for terminator in StreamingResponse.

**To Reproduce**
See [IR definition of StreamingResponse](https://github.com/fern-api/fern/blob/7e98e560a723ffb85a5571a668d74ddffae45979/fern/apis/ir-types-v31/definition/http.yml#L178C10-L178C10).

**Expected behavior**
IR returns a required property for terminator in StreamingResponse.

**Comment by dannysheridan** [comment]
closing as this hasn't resulted in user-facing issues
