### ISSUE TITLE
[Bug] Using a fern reserved model name causes a ConflictError

### ISSUE THREAD

**Issue by hjblom** [fern-api/fern#2374]
**Describe the bug**
When using Fern to generate code from an OpenAPI specification, a naming conflict arises when a model name in the generated code clashes with an internal convention used by Fern. Specifically, the issue occurs when a `$ref` in the OpenAPI specification has the same name as an internal convention used by Fern. This leads to errors in the generated code, such as "BadRequestError" and "UnauthorizedError" being declared multiple times in the same file.

**To Reproduce**

1. Create an OpenAPI specification with a `$ref` that has the same name as an internal convention used by Fern.
2. Run Fern to generate code using the OpenAPI specification.
3. Observe the errors related to model name clashes.

Example Specification that can be used to reproduce the errror.
```yaml
# Example OpenAPI Specification
openapi: 3.1.0

info:
  title: My API
  version: 1.0.0

paths:
  /example:
    get:
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
  
components:
  schemas:
    UnauthorizedError:
      type: object
      properties:
        error:
          type: string
```

Example output:
```shell
➜  fern git:(main) ✗ fern generate
[api]: __package__.yml -> errors -> UnauthorizedError
       UnauthorizedError is already declared in this file
```

By changing the `$ref` from `UnauthorizedError` to `UnauthorizedErr` it generates successfully. The example code it generates in this case would be:
```python
    def get_example(self) -> None:
        ...
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 401:
            raise UnauthorizedError(pydantic.parse_obj_as(UnauthorizedErr, _response.json()))  # type: ignore
        ...
```

Since the naming of `UnauthorizedError` and `UnauthorizedErr` is different, it works.

**Expected behavior**
Fern should handle naming conflicts gracefully and avoid declaring models with names that clash with its internal conventions. There could be an option to provide an optional prefix or suffix for Fern models to prevent such conflicts. For example:
```json
{
  "organization": "Org",
  "version": "0.15.5",
  "fern-model-prefix": "Fern"
}
```

which would then generate the code

```python
    def get_example(self) -> None:
        ...
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 401:
            raise FernUnauthorizedError(pydantic.parse_obj_as(UnauthorizedError, _response.json()))  # type: ignore
```

This means that `FernUnauthorizedError` would not conflict with `UnauthorizedError` and no change needs to be made in the specification.

**Desktop**
- OS: MacOS
- Version: 0.15.5

**Comment by dannysheridan** [comment]
Tested this issue with CLI version 0.16.6 and it did not resolve the issue. (Note: In v16 of Fern we made meaningful revisions to the OpenAPI parser.

**Comment by dsinghvi** [comment]
@hjblom this should be fixed in https://github.com/fern-api/fern/pull/2550
