### ISSUE TITLE
Support multiple `allOf` schemas in the OpenAPI Importer

### ISSUE THREAD

**Issue by dvargas92495** [fern-api/fern#2377]
**Is your feature request related to a problem? Please describe.**
I have the following `allOf` schema: https://github.com/vellum-ai/vellum-client-generator/pull/105/files#diff-b12ee94bc4f8259a3297c5b14fb6de75f26cde867436407eb55eed59c03fb3f8R1480-R1503
- it extends two schemas, one's a reference and one's defined inline.
- The referenced schema is polymorphic

It appears that because of the `getSingularAllOf` function, any schema that implements multiple `allOf` entries will be skipped entirely. This results in `allOf: []` during the intermediate OpenAPI IR.

**Describe the solution you'd like**
Support for schemas that utilizes multiple `allOf` entries.

**Describe alternatives you've considered**
We could nest objects within properties, but this would lead to a less idiomatic API for us.

**Additional context**
See `fern-x-vellum` for more details.

**Comment by dannysheridan** [comment]
We've made improvements to the OpenAPI importer, specifically related to polymorphism, over the last year. Closing this as it's _likely_ been resolved and there's not an easy OpenAPI spec for me to repro the problem with.
