### ISSUE TITLE
[Bug] Linking to an internal resource opens in a new tab

### ISSUE THREAD

**Issue by ashleygmulligan2** [fern-api/fern#2382]
**Describe the bug**
I'd expect when I link to an endpoint that it takes me there. I'd expect when linking to an external URL that it opens in a new tab. Currently, both open in a new tab.

**To Reproduce**

1. Make a link in a custom mdx file.

**Expected behavior**
I'd expect when I link to an endpoint that it takes me there. I'd expect when linking to an external URL that it opens in a new tab. Currently, both open in a new tab.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by dannysheridan** [comment]
Related to https://github.com/fern-api/fern/issues/2347

**Comment by dsinghvi** [comment]
@abvthecity https://docs.joincandidhealth.com/ has another example of this

**Comment by dannysheridan** [comment]
this has since been solved and is live!
