### ISSUE TITLE
[Feature] intro mdx for each section

### ISSUE THREAD

**Issue by ashleygmulligan2** [fern-api/fern#2383]
**Is your feature request related to a problem? Please describe.**
I need to introduce concepts before each section of endpoints. I cannot do that today.

**Describe the solution you'd like**
I'd like to interject .mdx files before various sections of the API. 

**Describe alternatives you've considered**
I can't think of another way to do this that would be ideal.

**Additional context**

**Comment by dsinghvi** [comment]
This is now supported https://buildwithfern.com/learn/docs/api-references/write-markdown-in-api-reference
