### ISSUE TITLE
[bug] unable to generate using colima

### ISSUE THREAD

**Issue by lfayoux** [fern-api/fern#2392]
### Describe the bug
When using [colima](https://github.com/abiosoft/colima) I am unable to run fern generate.
### To reproduce

1. Quit docker desk, Install and set up colima
2. run fern generate with --keepDocker
3. Observer that there are no resulting docker containers

### Expected behavior
Should run successfully or persist the docker container

### Versions
- Desktop OS: macOS
- Fern Version: 0.15.2

**Comment by jellydn** [comment]
I've got the same issue with https://orbstack.dev/ and below is my workaround.

```sh
DOCKER_HOST="unix:///Users/huynhdung/.orbstack/run/docker.sock" fern generate --local
```

You could get the path by command: `docker context ls --format json | jq`

**Comment by jellydn** [comment]
FYI - Worked for me with Orbstack but got error with Colima.

```sh
❯ DOCKER_HOST="unix:///Users/huynhdung/.colima/default/docker.sock" make generate-sdk
Generating SDK...
[api]: ✓ All checks passed
[api]: fernapi/fern-typescript-node-sdk Docker exited with a non-zero exit code. Logs here: /var/folders/rz/6r6_41fx38b7f5c2p2jbqqzh0000gn/T/tmp-2431-5JyQzX0as58c
[api]: fernapi/fern-typescript-browser-sdk Docker exited with a non-zero exit code. Logs here: /var/folders/rz/6r6_41fx38b7f5c2p2jbqqzh0000gn/T/tmp-2431-nffNh7GNzOMD
┌─
│ x  fernapi/fern-typescript-node-sdk
│ x  fernapi/fern-typescript-browser-sdk
└─
make: *** [generate-sdk] Error 1
```

**Comment by dannysheridan** [comment]
Since this was filed, we haven't gotten this request again. Closing, but open to re-opening if you'd like to follow up!
