### ISSUE TITLE
Ability to serve content read from the mdx files in the docs, as in-line on the API reference sections as well as in other mdx files

### ISSUE THREAD

**Issue by maverick143** [fern-api/fern#2394]
### Problem description
Ability to serve content read from the mdx files in the docs, as in-line on the API reference sections. And we don't want to duplicate the same content in two places. The same thing can be extended to support in other mdx files (serve content from one mdx file , in-line into another mdx file).

### Why would it be useful?
Lesser clicks for the users

### Describe the solution (optional)
Ability to serve content read from the mdx files in the docs, as in-line on the API reference sections. And we don't want to duplicate the same content in two places. The same thing can be extended to support in other mdx files (serve content from one mdx file , in-line into another mdx file).

### Additional context
![Screenshot 2023-11-29 at 09 51](https://github.com/fern-api/fern/assets/401248/47f37478-9b21-40c2-a97c-6f2d271f6fcc)

Today, you can do this by entering the contents in the description field of a path within OpenAPI specification, such as below. But that means, we may end up having to store the content in two places or can't have the content in-line.

```
"paths": {
    "/client-session": {
      "post": {
        "tags": ["Client Session API"],
        "summary": "Create a client session",
        "description": "Creating a client session generates a client token: a temporary key used to initialize [Universal Checkout](https://primer.io/docs/accept-payments/setup-universal-checkout/installation/web) ... \nClient tokens expire after 24 hours.\n"

```

**Comment by dannysheridan** [comment]
Thanks for filing this suggestion! We hear that users prefer to keep the source of truth as their OpenAPI spec. One option is to use Overlays: https://docs.buildwithfern.com/api-definition/openapi/open-api-extensions#overlaying-extensions
