### ISSUE TITLE
[Bug] Empty properties produce non descriptive error on fern check

### ISSUE THREAD

**Issue by ashleygmulligan2** [fern-api/fern#2397]
### Describe the bug
when you leave docs: empty, you get a non-descriptive error on` fern check`

### To reproduce

1. Leave docs: empty

If relevant, provide a minimal API definition (OpenAPI or Fern Definition) or Docs configuration (`docs.yml`) that can be used to reproduce the error.

### Expected behavior
I’d love for it to be more specific on why here.

### Screenshots
![image](https://github.com/fern-api/fern/assets/17680735/0646a2b9-4d9e-4ef6-b32d-45a6478bb562)

**Comment by dannysheridan** [comment]
Closing as stale.
