### ISSUE TITLE
[Bug] Fern-bot proceeds even when Github protected branches have prevented commit from merging

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2412]
### Describe the bug
Fern-bot doesn't gracefully handle pushing a commit to a protected branch. It continues as if the commit was allowed to be pushed on the protected branch and tags a release. 

### To reproduce

1. Protect your default branch
2. Setup fern to output a sdk to the github repo 
3. Generate and see Fern not tag a commit but tag a release

### Expected behavior
Fern-bot shoudl fail and tell the user to update their protected branches

### Screenshots
This is what the commit that failed to make it to the protected branch loks like
<img width="1718" alt="Screenshot 2023-12-01 at 10 22 30 AM" src="https://github.com/fern-api/fern/assets/10870189/53f8f8ea-daf0-4723-9dbf-6a282f760959">

### Versions
- Fern Version: 0.15.5

**Comment by dannysheridan** [comment]
closing for https://linear.app/buildwithfern/issue/FER-684/[bug]-fern-bot-proceeds-even-when-github-protected-branches-have
