### ISSUE TITLE
[Feature] Run `fern generate --docs` for any docs that reference a published SDK

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2413]
### Problem description

After a SDK is published, the code snippets may have changed. Therefore, to grab the latest code snippets, we should trigger an update to the docs. 

### Why would it be useful?

Currently we have to wait till the sdk is released and manually run `fern generate --docs`. 

### Describe the solution (optional)

```
Step 1: Run command `fern generate --group <>`
Step 2: Check if any of those published coordinates are referenced by the docs
Step 3: If yes, run `fern generate --docs`
```

**Comment by dannysheridan** [comment]
closing for https://linear.app/buildwithfern/issue/FER-683/[feature]-run-fern-generate-docs-for-any-docs-that-reference-a
