### ISSUE TITLE
[Feature] Fern's Github integration should create proper SDK issue templates

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2414]
### Problem description

Fern doesn't generate issue templates for the SDKs that are published to Github. 

### Why would it be useful?

SDK users need to be prompted to fill out all relevant information so that users can root cause. 

### Additional context
For example, issues files should have a field for the SDK version

<img width="890" alt="Screenshot 2023-12-01 at 1 54 54 PM" src="https://github.com/fern-api/fern/assets/10870189/260687d7-02bf-4748-bb23-3a544b8e83e2">

Add any other context or screenshots.

**Comment by dannysheridan** [comment]
moving to linear: https://linear.app/fern-api/issue/FER-667/[feature]-ferns-github-integration-should-create-proper-sdk-issue
