### ISSUE TITLE
[Fern's Documentation] Highlight the Postman Generator earlier on in the README and/or Docs

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2416]
### What can be improved

We should make it clearer that Fern can publish to Postman.

Example that we can link to: https://github.com/revertinc/revert/blob/dd0c6a5157b1ec536ed99ad2e3e27caae9b94066/fern/generators.yml#L12-L23

**Comment by SK-Sam** [comment]
Postman Collections syncing seems like a big enough deal that it deserves its own highlighted section in the docs, how about changes similar to this? I'll mock down what I'm thinking into a PR and tag it here

<img width="1437" alt="Screenshot 2024-01-24 at 10 39 12 PM" src="https://github.com/fern-api/fern/assets/10618376/3f1b9dfd-9ec3-4f3c-ac5e-b43c601e05f5">


- Bump up higher into docs, as you pitched, while adding more emphasis on what the result looks like
- Add Postman logo into diagram as per screenshot
<img width="924" alt="Screenshot 2024-01-24 at 10 45 56 PM" src="https://github.com/fern-api/fern/assets/10618376/7986419b-db5a-4549-bcc0-5399a30d1b38">

- Add video of Postman Collection sync for a visual example, similar to Fern Express Video, similar to this in README:

**Comment by dannysheridan** [comment]
I like the idea of adding it to the graphic. Let me take an action here and chat with our designer. May take days to get back here
