### ISSUE TITLE
[Feature] When picking one SDK language for code snippets, all of the snippets should change

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2419]
### Problem description

Currently you have to select the langauge you want on every snippet. 

### Why would it be useful?

If I pick TS for one code snippet, its reasonable to assume thats what the user wants all the code snippets to be in. 

### Describe the solution (optional)

- Update all code snippets when a specific language is chosen
- Store the picked language as a cookie so the user doesn't have to change it again and again

**Comment by dannysheridan** [comment]
This is now live in prod!
