### ISSUE TITLE
[Bug] API reference not properly justified left

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2422]
### Describe the bug
The API Reference packages should be left indented

<img width="493" alt="Screenshot 2023-12-02 at 3 10 19 PM" src="https://github.com/fern-api/fern/assets/10870189/6ff91bd3-c583-478c-a232-49207cb326a0">

### Expected behavior
Normally the API reference is properly indented to the left (see here: https://candid.docs.buildwithfern.com/)
<img width="363" alt="Screenshot 2023-12-02 at 3 11 33 PM" src="https://github.com/fern-api/fern/assets/10870189/d0a64096-0a8c-478b-b31d-59d432b0ef22">

**Comment by abvthecity** [comment]
Cannot repro
