### ISSUE TITLE
[Feature] Better CLI output for Fern Check

### ISSUE THREAD

**Issue by damonbanks** [fern-api/fern#2434]
### Problem description

I get several irrelivant warnings when running `fern check`. If there is a real error, id like to only see that. When the terminal window is small/short the error gets lost.

### Why would it be useful?

The warnings are cluttering the output when there is an actual error.

### Describe the solution (optional)

If there are error(s) show those only. If not, then show some warnings. 

### Additional context

Add any other context or screenshots.
<img width="1186" alt="Screenshot 2023-12-04 at 10 42 29 AM" src="https://github.com/fern-api/fern/assets/149414575/ff57fbfb-7631-4d01-ab01-ddf663e73a63">
![Screenshot 2023-12-04 at 10 36 37 AM](https://github.com/fern-api/fern/assets/149414575/bb2ba17e-32a7-4c48-8d0d-51941f0abe11)

**Comment by dsinghvi** [comment]
Suggested fix: 
- `fern check` does not print out warnings by default
- `fern check --warnings` will print out both errors + warnings

**Comment by lesjonesiv** [comment]
> Suggested fix:
> 
> * `fern check` does not print out warnings by default
> * `fern check --warnings` will print out both errors + warnings

+1 would love to see something like this

**Comment by damonbanks** [comment]
> Suggested fix:
> 
> * `fern check` does not print out warnings by default
> * `fern check --warnings` will print out both errors + warnings

Yes. This would be good. Maybe a `fern check --log-level warning` if it needs to be more robust for future iterations for logs such as `info, warning, error, debug, etc` But that might be overkill for the use case

**Comment by dsinghvi** [comment]
@damonbanks @lesjonesiv this is releases in `0.16.9`. To grab the latest, upgrade fern by running `fern upgrade`
