### ISSUE TITLE
[Feature] Unable to use custom generators with different image names

### ISSUE THREAD

**Issue by davidkonigsberg** [fern-api/fern#2442]
### Describe the bug
I would like to be able to use custom fern generators with image names that match my organization. Currently, I have a forked generator that has some business logic specific to my use case. In order to use this generator, I need to tag the image with the same name as the fern-provided generator and use a tag greater than or equal to the fern tag (I've been using 9.9.9).

### To reproduce
Build a fern generator image, tag it with a different name, try to use that with fern generate, you will get an error.

### Expected behavior
I should be able to use a custom generator as log as it satisfies whatever interface fern is looking for.

### Screenshots
See our slack convo: https://sayari.slack.com/archives/C066SHSBLBU/p1701716051732609

### Versions
- Desktop OS: macOS
- Fern Version: 0.15.11

**Comment by zdunecki** [comment]
Hey,

I'm working on this [PR](https://github.com/fern-api/fern/pull/2677). It allows to pass explicit version of IR. I wasn't aware but thanks to that we can pass custom docker image if we pass `irVersion` also.

I tried to use custom docker image without that flag and then it does not work. It does not look like a good interface rather like a side effect. 

I think it should be resolved better without explicit passing flag `irVersion` but after a merge above PR it can be possible. But probably tweaked in the future.

**Comment by dsinghvi** [comment]
Fixed by https://github.com/fern-api/fern/pull/3212
