### ISSUE TITLE
Bug: Layout for "Show Properties" button has incorrectly calculated width

### ISSUE THREAD

**Issue by kole** [fern-api/fern#2451]
### Describe the bug
Sometimes (intermittently) the button in the UI to expand properties has an incorrectly calculated width.

### To reproduce
- Navigate here: https://docs.propexo.com/api-reference/api-reference/admin/get-all-data-diffs
- View the buttons entitled "Show 9 enum values", "Show 5 Properties", and "Show 8 properties".
- Refresh page over and over to observe the UI bug intermittently (seen in attached screen rec)
- The bounding box is smaller than the inner text.

### Expected behavior
The button border always wraps around the text. The text never overflows the button border.

### Screenshots

https://github.com/fern-api/fern/assets/412111/c28091d3-5ec0-40ca-a66e-08e9d7872b31

### Versions
- Desktop OS: macOS 14.1.2
- Chrome 119.0.6045.199 (could not repro in Safari)
- Fern Version: 0.15.15 (also observed in 0.15.0-rc68) 

### Additional context
It seems like there is some js that is incorrectly calculating the width at page load time. Suggested fix might be to use CSS only.

**Comment by dannysheridan** [comment]
we've updated the enum component as seen below. this is no longer an issue. Thanks for reporting so we could track!

![Screenshot 2024-01-27 at 21 07](https://github.com/fern-api/fern/assets/83524670/48881939-39d2-4013-84ca-8e060d6daba2)
