### ISSUE TITLE
[Bug] Linking to specific sections doesn't work in fern's documentation

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2453]
### Describe the bug
https://docs.buildwithfern.com/api-definition/openapi/extensions#overlaying-extensions doesn't redirect to the correct section. 

### To reproduce
1. Load https://docs.buildwithfern.com/api-definition/openapi/extensions#overlaying-extensions

### Expected behavior
Loads the `Overlaying Extensions` sections

**Comment by dannysheridan** [comment]
confirming this now works. example: https://docs.buildwithfern.com/api-definition/openapi/open-api-extensions#server-names
