### ISSUE TITLE
[Bug] Broken Relative Paths in <a> Tags Causing SEO Penalties

### ISSUE THREAD

**Issue by noanflaherty** [fern-api/fern#2462]
### Describe the bug
There are invalid urls being auto-generated and inserted into the dom. These invalid urls result in 404s. Search engines pick up this 404 and penalize you in SEO world.

### To reproduce

1. Go to https://docs.vellum.ai/
2. Open chrome dev tools
3. Click on the "Elements" tab
4. cmd-F
5. Search for "docs.vellum.ai". Notice you can find an a tag with a href of `/docs.vellum.ai#frequently-visited-resources`
6. Notice that it's the base of a relative path which results in a full path of  `docs.vellum.ai/docs.vellum.ai#frequently-visited-resources`

![image (1)](https://github.com/fern-api/fern/assets/14092604/7e7110b7-dbe9-4131-a435-60f0771331c4)

### Expected behavior
It should either be a valid relative path or use an absolute path

**Comment by abvthecity** [comment]
Thanks for the bug report, merged a PR to fix this https://github.com/fern-api/fern-ui/pull/280 and should get this released by EOD today.
