### ISSUE TITLE
[Feature] Add support for Kotlin Multiplatform Client

### ISSUE THREAD

**Issue by BierDav** [fern-api/fern#2463]
### Problem description

Jetpack Compose Multiplatform came quite appealing recently, The open api generator works fine, but what if there would be a fern one?

### Why would it be useful?

More platforms are always better.

**Comment by dannysheridan** [comment]
while we plan to expand to additional platforms in the future, this is not a focus for us right now

**Comment by nathanfallet** [comment]
Linked to #3360
