### ISSUE TITLE
[Bug] Comment syntax  `%% ... %%` has no effect

### ISSUE THREAD

**Issue by jackfischer** [fern-api/fern#2472]
### Describe the bug
Expected to be able to comment out content in `mdx` files via the `%% ... %%` syntax

### To reproduce

1. Add a comment `%% this is a comment %%`
2. Preview shows the actual characters `%% this is a comment %%`

If relevant, provide a minimal API definition (OpenAPI or Fern Definition) or Docs configuration (`docs.yml`) that can be used to reproduce the error.

### Expected behavior
Comment content does not appear visually in the browser. May or may not appear in source code.

### Versions
- Desktop OS: [e.g. macOS, Windows, Linux]  
- Fern Version: tested on 0.15.0-rc68

**Comment by dannysheridan** [comment]
haven't had anyone else request this functionality. can re-open if others also are looking for the comment syntax to be supported. Thanks, Jack for opening in the first place!
