### ISSUE TITLE
[Feature] Support uploading and hosting images

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2477]
### Problem description

As a user, I want to be able to reference an image in my `fern` directory and have that available for reference in my docs.

### Why would it be useful?

Avoid me having to host somewhere else. Today, I have to add a public S3 bucket manually. 

### Proposed solution

`![](/fern/docs/images/foo.png)` and Fern uploads the images for hosting when I build my docs.

**Comment by dannysheridan** [comment]
In the meantime, here's my approach to adding images: https://github.com/fern-api/fern/blob/58161583cf2bdb9c73e7f93c0c911c585de5156b/fern/docs/pages/welcome/introduction.mdx#L11

**Comment by starlightknown** [comment]
Need the same feature, thank you.

**Comment by abvthecity** [comment]
Image upload supported as of [0.23.1](https://github.com/fern-api/fern/releases/tag/0.23.1)
