### ISSUE TITLE
Publish a spec for generators.yml

### ISSUE THREAD

**Issue by billytrend-cohere** [fern-api/fern#2484]
### Problem description

generators.yaml config is hard to discover

### Why would it be useful?

if we could add a yaml spec and had completions would be easier to discover config

### Describe the solution (optional)

you can do something like this `# yaml-language-server: $schema=<urlToTheSchema>`

https://github.com/redhat-developer/yaml-language-server

**Comment by dannysheridan** [comment]
This is now released!

https://buildwithfern.com/learn/sdks/reference/configuration#schema-validation
