### ISSUE TITLE
[Feature] Make timeout configurable for python SDK

### ISSUE THREAD

**Issue by arcticfly** [fern-api/fern#2495]
### Problem description

I would like to allow the timeout to be greater than 60 seconds for requests made through a generated Python SDK.

### Why would it be useful?

Some requests (like activating idle models on GPUs) take more than 60 seconds to complete. We shouldn't throw a timeout error in all cases if 60 seconds pass without a response.

### Describe the solution (optional)

Ideally, timeouts could be declared dynamically at the time a field is called by passing an optional parameter to the request.

### Additional context

We're another YC startup (OpenPipe) and we'd really like to use your tool.

**Comment by dsinghvi** [comment]
@arcticfly thanks for filing this request! we'll follow up when this is live

**Comment by arcticfly** [comment]
Btw, since creating this issue we found https://github.com/fern-api/fern-python?tab=readme-ov-file#-timeout_in_seconds, which solves our immediate problem by allowing us to declare more convenient defaults for timeouts. However, it would still be great to pass in dynamic values at runtime.

**Comment by aakrem** [comment]
Would be better to have the fern timeout per endpoint. the above solution will be applied for all endpoints :/

**Comment by devgenix** [comment]
Stumbled on this while searching for similar. In my use case, I just need to change the timeout for a request that build an image and would take longer than 60 seconds. 

It would be nice to have that. In the meantime, I did similar as @arcticfly mentioned.

**Comment by armandobelardo** [comment]
Hi there folks! This is now possible as of version 0.10.1 of the python generator! This allows you to pass in a timeout per-request.
Here's the changelog entry: https://github.com/fern-api/fern/blob/main/generators/python/sdk/CHANGELOG.md#0101---2024-02-14
