### ISSUE TITLE
[Feature] Auto-Generated Code Snippet Examples

### ISSUE THREAD

**Issue by noanflaherty** [fern-api/fern#2506]
### Problem description

Today, I must explicitly define an example for it to show up as a Python Code Snippet in our [API docs](https://docs.vellum.ai/api-reference/introduction/getting-started).

### Why would it be useful?

This requires manual effort and is error prone if our example diverges from the API spec. As a result, I don't end up adding examples and our customers miss out.

### Describe the solution

Instead, I'd love for fern to auto-generate code-snippet examples given reasonable place-holder values. The same values shown today for curl snippets are a good starting point. Down the road, I could see AI helping generate even richer examples.

**Comment by armandobelardo** [comment]
@noanflaherty this should be all set now! Fern is autogenerating example, and it should be enabled for y'all today!

Going to close this out, but please feel free to reopen or ping if anything is up
