### ISSUE TITLE
[Docs] Generate docs for a specific audience

### ISSUE THREAD

**Issue by sarora007** [fern-api/fern#2520]
### Problem description

We did a product experiment a few months back where we launched an Accounts Receivable API MVP.
We published docs on fern but only wanted to share those docs w/ the select prospects we were engaging w/.
RN, anyone can see those docs. We’d like to only share the AR docs w/ specific orgs we’re experimenting w/

### Why would it be useful?

Helps us experiment faster w/o needing to show our hand to the larger market

### Describe the solution (optional)

I can set a password for any single doc article. When a user goes to that specific doc, they will need to enter the password to view the doc. 

### Additional context

Add any other context or screenshots.

**Comment by dannysheridan** [comment]
+1 request from another user

**Comment by dannysheridan** [comment]
We've acted upon this request and now support generating docs for a specific audience natively in Fern Docs!

We've decided to describe this functionality as `Role-based access control (RBAC)`. Here's a look at how to configure in `docs.yml`: https://buildwithfern.com/learn/cli-api/cli-reference/changelog/2024/10/25
