### ISSUE TITLE
Docs Markdown Component for SDK/cURL snippets

### ISSUE THREAD

**Issue by thesandlord** [fern-api/fern#2524]
### Problem description

In order to put code snippets into docs and guides, they need to be manually created in all supported languages and cURL. When the API changes, these need to be manually changed as well.

### Describe the solution

Examples are already defined in the Fern definition. It would be great to just drop in the existing examples into the docs. These would always stay in sync with the Fern definition, and automatically create snippets for all supported Fern languages. 

### Why would it be useful?

Docs are more useful if explanation and code are side by side. This encourages more full featured docs to be written easily, and makes Fern a true all in one platform!

**Comment by Rutledge** [comment]
+1 We have examples in the github repos. It would be nice if these were available in the docs!

**Comment by dannysheridan** [comment]
Thanks for this feedback! We've acted upon it and developed a component that can be used:

https://buildwithfern.com/learn/docs/content/components/request-snippet
