### ISSUE TITLE
[Feature] Link to API documentation component

### ISSUE THREAD

**Issue by thesandlord** [fern-api/fern#2525]
### Problem description

Right now, in order to link to a API route in docs, you just have to copy/paste the full URL. It would be nice to have a component that automatically linked or even pulled in basic info about the API endpoint (POST/GET, click to expand inline, etc) that could be dropped into docs.

### Why would it be useful?

This makes it easier to make a cohesive docs experience that looks great

**Comment by dannysheridan** [comment]
Great idea. Others share this request. I'm closing this issue in favor of https://github.com/fern-api/fern/issues/5240
