### ISSUE TITLE
[Bug] Allow-multiple mixed with optional type causes required list on python sdk

### ISSUE THREAD

**Issue by damonbanks** [fern-api/fern#2529]
### Describe the bug
When the allow-multiple: true and the type: optional<integer> are on a request type in fern definition the python SDK only shows optional on one of the types not the list type:
Fern Def:
` ids:
       type: optional<integer>
       allow-multiple: true`

Python SDK:
`  ids: typing.Union[typing.Optional[integer], typing.List[integer]],
`

### To reproduce
See above

### Expected behavior
Given the above fern def. We dont want the ids required (it is now in the python sdk). The python sdk should produce something like:
`ids: typing.Optional[typing.Union[integer, typing.List[integer]]]`
or
` typing.Union[typing.Optional[integer], typing.Optional[typing.List[integer]]]`

Link to Python SDK:
Our SDK: https://github.com/FlatFilers/flatfile-python/blob/ee044b531bb23ac0dd2a35b76c8d88c027945acc/src/flatfile/resources/records/client.py#L54C1-L55C1

### Version
Fern Version: [e.g. 0.15.9; found in `fern.config.json`]

**Comment by armandobelardo** [comment]
This should be fixed! I also took a look and it seems the SDK is already updated with the fix: https://github.com/FlatFilers/flatfile-python/blob/main/src/flatfile/resources/records/client.py#L61
