### ISSUE TITLE
[Fern's Documentation] How to implement retry logic, like exponential backoff

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2545]
### What can be improved

"On the Fern homepage it says "Retry logic - Choose a retry mechanism for API calls, such as exponential backoff." But searching in the docs I can find no info on this. Where is it documented please?" - Richard Cooke

**Comment by dannysheridan** [comment]
We default each client to exponential backoff with 2 retries, and SDK users can customize this by using the `maxRetries` option.

**Comment by SK-Sam** [comment]
@dannysheridan does `maxRetries` belong in the `generators.yml` `config` level of options? Something like:

```
config:
   timeoutInSeconds: 120
   maxRetries: 6
```

Or can SDK users customize `maxRetries` elsewhere?

**Comment by dannysheridan** [comment]
yes, it belongs in the `generators.yml` config!
