### ISSUE TITLE
[Bug] Docs table of contents sidebar links don't support markdown links

### ISSUE THREAD

**Issue by thesandlord** [fern-api/fern#2552]
If I have a header on a docs page like:

```
[Test](https://google.com)
```

The sidebar ToC renders the full text, not just `Test`

Production Example:

https://docs.buildwithfern.com/overview/guides/publishing-to-maven-central#step-2--create-an-account-on-sonatype-jira--create-an-account--here--https---issues-sonatype-org-secure-signup-default-jspa--

![image](https://github.com/fern-api/fern/assets/8902396/b58b4782-02d6-481e-8fd0-742f316be17d)

https://docs.mercoa.com/concepts/entities

![image](https://github.com/fern-api/fern/assets/8902396/d4649ba6-e7cc-44db-a0a0-ead37012c68f)

**Comment by dannysheridan** [comment]
Thanks for reporting! This has been fixed:
![Uploading Screenshot 2024-01-25 at 23.49.png…]()
