### ISSUE TITLE
[Bug] Missing OneOf fields

### ISSUE THREAD

**Issue by starlightknown** [fern-api/fern#2556]
### Describe the bug

Fern docs are missing some information, particularly when there's a oneof involved. For example, the common fields for works.create are missing: https://devrev.docs.buildwithfern.com/api-reference/works/create

**Comment by dannysheridan** [comment]
this is now fixed and is live: https://devrev.docs.buildwithfern.com/dev-rev-rest-api/api-reference/works/create
