### ISSUE TITLE
[Feature] collapsible components for sections, tables and code snippets

### ISSUE THREAD

**Issue by aleksAperans** [fern-api/fern#2559]
### Problem description

at times the number of pages tied to a section, or the number of rows in our tables, or the length of a code snippet can  take up a sizable amount of real-estate either on the side-nav or body of the page. 

### Why would it be useful?

collapsible components enable users to shrink the copy in a given page or section, allowing them to view other copy within a page with more ease. 

### Why would this feature be useful for Fern users?

other doc users might have similar verbose content in their pages and side-panels

### Describe the solution (optional)

collapsible components for sections in the side-nav, tables and code snippets

### Additional context

Add any other context or screenshots.
![collapse_containers](https://github.com/fern-api/fern/assets/139813505/fb1435fe-5cc1-4948-ae13-199305d9e3ac)

**Comment by dannysheridan** [comment]
This is now available! https://docs.buildwithfern.com/generate-docs/overview/writing-content#nested-sections
