### ISSUE TITLE
[Feature] responsive page width or "full width mode" 

### ISSUE THREAD

**Issue by aleksAperans** [fern-api/fern#2560]
### Problem description

at times the amount of content that is housed within a page can exceed the horizontal limits of the page making it difficult to read and digest.

### Why would it be useful?

having dynamic width or "full width mode" would enable users to interact with verbose content with more ease. 

### Describe the solution (optional)

Option 1: dynamic page width - downside here is that aesthetically it probably won't feel great to not have a uniform experience with the documents. could be wrong

Option 2: optionality to enter "full width mode" giving the reader or client the ability to opt in to a view that better supports wide content.

### Additional context
Examples that illustrate horizontal overflow. 
![horizontal](https://github.com/fern-api/fern/assets/139813505/5532626c-d9d3-473c-a51e-3dbd50d6250e)

![content2](https://github.com/fern-api/fern/assets/139813505/e7ace9ea-0283-4fbe-983a-7f950334120e)

**Comment by aleksAperans** [comment]
a good example of the problem we are facing is here: https://documentation.sayari.com/sayari-library/coverage/coverage

**Comment by dsinghvi** [comment]
@aleksAperans did andrew's suggestion above solve your issue?

**Comment by aleksAperans** [comment]
@dsinghvi it did --  thank you!
