### ISSUE TITLE
[Feature] Detect broken/dead links with a Link Checker

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2561]
### Problem description

When crafting a relative link (e.g., /devices/send) or absolute link (docs.example.com/devices/send) in Fern Docs, there is easily room for error that the link doesn't actually work. I'd like to be able to get a warning from Fern when this occurs.

### Why would it be useful?

Prevents users from hitting URLs that are 404s or redirect to a homepage, for example. As an author of docs, I want to prevent this frustrating experience for my users.

### Describe the solution (optional)

Something like: https://github.com/stevenvachon/broken-link-checker

**Comment by dannysheridan** [comment]
```mdx
  <Card 
    title="Users" 
    icon="fa-solid fa-person"
    href="/guides/overview/entities#user"
  />
```

this is an example where it took me 3 commits to get the `href` correct. I ended up previewing the docs and then copying and pasting the url because manually typing it had too many mistakes (like using `users` instead of `user`; having `entities/user` instead if `entities#user`)

**Comment by dannysheridan** [comment]
This includes images like `![](../docs/assets/my-image.png)`

**Comment by dannysheridan** [comment]
examples of what should be caught: 
* https://github.com/fern-api/fern/pull/2745/files
* https://github.com/fern-api/fern/pull/2741/files

**Comment by noanflaherty** [comment]
My dream state:
1. Fern allows me to define redirects to avoid dead links that are out in the wild outside of our control
2. `fern check` shows dead links as warnings (or can be configured to be an error)
