### ISSUE TITLE
[Feature] Add caption option for code blocks

### ISSUE THREAD

**Issue by aleksAperans** [fern-api/fern#2564]
### Problem description

When adding code snippets to markdown, reference text to the snippet needs to appear either above or below the snippet as regular text. This is very much a nice to have,  but it would be more elegant if the text appeared nested with the snippet itself.

### Why would it be useful?

ease of use, referencing code snippets

### Describe the solution (optional)

enable fern developers working on markdown to assign caption text to a code snippet.

### Additional context
![aa 06 01](https://github.com/fern-api/fern/assets/139813505/4016a3a5-e8e1-45fd-ac91-71e099caba35)

**Comment by dannysheridan** [comment]
We don't plan to add a `prop` to a code block for a caption. If this becomes more than a nice to have, let us know!
