### ISSUE TITLE
[Feature] add option to include side-nav separators

### ISSUE THREAD

**Issue by aleksAperans** [fern-api/fern#2565]
### Problem description

when a mdx page is not linked to a section and falls within a two-tier structure (tab, page) it would be nice to have the option to insert a line separator, to provide more visual clarity between the pages and content. Perhaps this is an underlying issue that the 3 tier structure must always be followed (tab,section,page) where the net result is redundant wen there isn't much content in the page 

### Why would it be useful?

additional visual clarity

### Describe the solution (optional)

ability to add a horizontal line or some other object to distinguish pages in the side-nav

### Additional context

![aa 06 01](https://github.com/fern-api/fern/assets/139813505/d0a622f5-bda5-4e34-974f-1b3d32cd05f1)

**Comment by dannysheridan** [comment]
Thanks for the request! Haven't gotten this ask again since this message. Closing this issue. There may be a way to solve this with CSS -- if that's a path you want to explore, please feel free to re-engage.
