### ISSUE TITLE
[Bug] Browser hangs when trying to expand a response.

### ISSUE THREAD

**Issue by davidkonigsberg** [fern-api/fern#2573]
### Describe the bug
When clicking "Expand All" next to the "Get Entity" response [here](https://sayari-analytics.docs.buildwithfern.com/api/api-reference/entity/get-entity#entity-get_entity-response) the browser will freeze/crash

### To reproduce

1. Go to https://sayari-analytics.docs.buildwithfern.com/api/api-reference/entity/get-entity#entity-get_entity-response
2. Click 'Expand All' next to 'Response' 
3. browser will freeze. If chrome, it will eventually ask you if you want to wait or give up.

### Expected behavior
Either expand the section without error, or hide the option if the response is too large/complex

### Screenshots
<img width="1494" alt="Screenshot 2024-01-08 at 5 19 32 PM" src="https://github.com/fern-api/fern/assets/72822263/68e612bb-812a-4ae1-b1b0-644cf188c98c">

### Version
Fern Docs

### Additional context
Has been reproduced on Mac/windows with safari, chrome, brave, and Firefox

**Comment by dannysheridan** [comment]
Confirming I've reproduced this issue. Assigning to @abvthecity to remediate.

**Comment by dannysheridan** [comment]
We've removed the ability for end users to `expand all` so this issue is no longer a problem.
