### ISSUE TITLE
[Feature] publish fern github actions to marketplace

### ISSUE THREAD

**Issue by pfbyjy** [fern-api/fern#2574]
Background
===

Today we copy github actions from snippets that the fern team shares with us
This is error prone and might cause us to become out of sync as the fern cli evolves.

Ideal
===
Fern actions are published to the github marketplace
[Github docs for creating custom actions are here](https://docs.github.com/en/actions/creating-actions)
this will allow us depend on fern in the same way that we depend on other marketplace actions
So we can do something like this

```
- uses: actions/fern_publish@v1
  with:
      branch: 'staging'
```

**Comment by dannysheridan** [comment]
Got the ball rolling:
* https://github.com/marketplace/actions/fern-preview-docs
* https://github.com/fern-api/preview-docs-action

Will need to test and revise the placeholder files for `Dockerfile` and `Entrypoint.sh` that I populated.

**Comment by dannysheridan** [comment]
In the meantime, this is the CI I recommend copying and pasting: https://github.com/fern-api/docs-starter/blob/main/.github/workflows/preview-docs.yml

**Comment by pfbyjy** [comment]
Thanks for the update on this!

**Comment by dannysheridan** [comment]
Closing as we haven't had this request again.
