### ISSUE TITLE
[Feature] Add link to external docs

### ISSUE THREAD

**Issue by coactive-steph** [fern-api/fern#2577]
### Problem description

We've recently migrated to Fern and are releasing a new version of our SDK alongside our new docs (hosted by Fern). The documentation for the previous SDK version (now deprecated, but still in use) is hosted by us in a separate location.

During the transition period, it would be nice to prominently display a link to the previous docs for customers that have yet to transition to the latest version of our SDK.

### Why would it be useful?

This feature will help companies/projects smoothly transition to Fern docs without losing reference to older documentation, whether that's temporarily or indefinitely.

### Describe the solution (optional)

Here are two ways to suggestions to accomplish this:

1. Allow Fern users provide a `url` instead of a `path` for externally hosted SDK version. Clicking this version on the docs page will redirect the user to the url value.
**docs.yml**
```
versions: 
  - display-name: v1
    path: versions/v1.yml
  - display-name: v0
    url: https://myproject.com/v0/docs
```
2. In `docs.yml` introduce a new optional property `banner` that takes markdown and displays it in a thin banner at the top of the page (like shown in this [Codepen](https://codepen.io/ista/pen/GXPKWW)). This feature could potentially serve other purposes, like other announcements related to documentation.

**Comment by dannysheridan** [comment]
We haven't heard this feature request from anyone else. If we do, I'll be happy to re-open and prioritize!
