### ISSUE TITLE
Specify keywords for package managers in generators.yml

### ISSUE THREAD

**Issue by gregorybchris** [fern-api/fern#2579]
### Problem description

Most package managers support keywords:
- JavaScript: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#keywords
- Python: https://python-poetry.org/docs/pyproject/#keywords

There should be a way to specify keywords in the fern spec

### Why would it be useful?

This helps with SEO and discoverability of packages.

**Comment by dannysheridan** [comment]
haven't heard this feature request from anyone else. if we do, I'm happy to re-open and prioritize!
