### ISSUE TITLE
Package software license in package definition

### ISSUE THREAD

**Issue by gregorybchris** [fern-api/fern#2580]
### Problem description

Most package managers support specifying the license for the package:
- JavaScript: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license
- Python: https://python-poetry.org/docs/pyproject/#license

There should be a way to specify this in the fern spec.

### Why would it be useful?

This makes it clear directly on the package manager website what the license is for the package without having to go to the SDK source code.

### Additional context

Note that currently you can currently add a license to your client repo without any issues, but the type of license will not be registered with the package manager unless it's in the package.json, pyproject.toml, etc.

**Comment by noanflaherty** [comment]
Noting that we'd also like and benefit from this.

**Comment by dvargas92495** [comment]
We're about to add this manually, including adding a `"license": "MIT"` field to our `package.json`, along with the `LICENSE` file. My sense is I don't want to add `package.json` to my `.fernignore` file, but I'm also concerned about that file being overwritten during fern upgrades - what is the behavior if I add a license field to package.json? Similar question for the package.json equivalent for other languages.

**Comment by dsinghvi** [comment]
@dvargas92495 @noanflaherty fern will need to support this first class -- we do support generating a LICENSE file today but not adding it to the `package.json` by default.

**Comment by dannysheridan** [comment]
This is supported as of January 2024. https://buildwithfern.com/learn/sdks/reference/configuration#specify-package-metadata

If you have any questions using this feature, let me know!
