### ISSUE TITLE
[Feature] Support for `const`

### ISSUE THREAD

**Issue by dvargas92495** [fern-api/fern#2586]
### Problem description

We would like to use constant values from the [OpenAPI Schema](https://json-schema.org/understanding-json-schema/reference/const)

### Why would it be useful?

It would clean up our generated type files and sdks by not creating extra enums and instead reference the constant literal directly.

### Additional context

See [slack thread](https://vellum-ai.slack.com/archives/C052UMCSFA8/p1704838599517559)

**Comment by dsinghvi** [comment]
This is supported in the latest version of the CLI (`0.18.3`)
