### ISSUE TITLE
[Bug] Comments in code blocks are interpreted as h1 headers

### ISSUE THREAD

**Issue by huyouare** [fern-api/fern#2593]
### Describe the bug
When there are Python comments in a code block, these are also added as an h1 header in the `On this page` outline:

<img width="1092" alt="image" src="https://github.com/fern-api/fern/assets/3528340/acc366aa-300f-41bd-9671-e8e518f9c3de">

### To reproduce

1. Add a Python code block with a comment on its own line
2. Run docs generate
3. Observe the incorrect outline

### Expected behavior
Python comments should not appear in the outline.

### Screenshots
<img width="1092" alt="image" src="https://github.com/fern-api/fern/assets/3528340/3144bd26-206f-43c8-bc47-b48daf9d677b">

### Version
Fern Version: "version": "0.16.25"

**Comment by dsinghvi** [comment]
@abvthecity assigning ticket to you -- i wonder if we can use a library that is better about this

**Comment by huyouare** [comment]
This only happens when using explicit <CodeBlock> elements.

**Comment by dannysheridan** [comment]
this is now fixed in production!

![Screenshot 2024-02-01 at 15 27](https://github.com/fern-api/fern/assets/83524670/220e1c39-9844-4d97-bc6a-5228c4f1724b)

thanks for reporting
