### ISSUE TITLE
[Bug] Polymorphic OpenAPI schema is missing additional properties

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2598]
### Describe the bug
When `oneOf` is used in OpenAPI and there are `properties` for the object, Fern only renders the schema of the polymorphic type. It ignores additional properties that are present in the `properties` key.

### To reproduce
The following OpenAPI spec causes the `applies_to_part` to be missing in Fern Docs.

```yaml
oneOf:
      - $ref: '#/components/schemas/works-create-request-issue'
      - $ref: '#/components/schemas/works-create-request-ticket'
      properties:
        applies_to_part:
          type: string
        ...
```

Using the same OpenAPI spec, Stoplight shows more properties in the request body than Fern Docs does. Fern Docs is missing properties.

In Stoplight: https://docs.devrev.ai/api#/operations/works-create#request-body 
In Fern Docs: https://devrev.docs.buildwithfern.com/api-reference/auth-tokens/create#create-request

OpenAPI spec: https://github.com/devrev/fern-api-docs/blob/3a6fe732e1c968d2d9244ae8e5fae4202c1b4a8c/fern/apis/public/openapi/openapi-public.yaml#L3343-L3346

**Comment by dsinghvi** [comment]
This is now fixed.
