### ISSUE TITLE
[Feature] Offline mode

### ISSUE THREAD

**Issue by zdunecki** [fern-api/fern#2617]
### Problem description
Currently I'm not able to generate code without network connection. I don't want any trackers to follow me. In many places I need login token or fields like `organization`.

### Why would it be useful?
I want to run code generation locally, without network connection. Additionally I don't want to use any trackers.

### Describe the solution (optional)
Easy flags to disable trackers and ability to generate code without network connection. Probably by fixing places where it's unnecessary needed.

**Comment by zdunecki** [comment]
@dannysheridan 

For production-ready usage - yes. 

Maybe not necessarily full offline mode but I'd to use fern without your cloud(remote) solutions. 

It also means the interface is fit for this usage (for example fields like organization would not needed), or CLI is better fit for that without tons of custom commands to make this work.

I make small contributions to fern that may help with that but maybe you have a better idea for that. For example, I can image something like `fern --offline` (for example).

**Comment by dannysheridan** [comment]
This isn't something that's on the roadmap and we haven't gotten requests for it outside of this issue. @zdunecki if it becomes more important to you, let me know. If others face this, please feel to re-engage and we can discuss again.
