### ISSUE TITLE
Add more examples and validation to mock server

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2620]
The new `fern mock` command (re: https://github.com/fern-api/fern/pull/2618) looks for an exact example request match in terms of the following:
- [x] Path parameters
- [x] Query parameters
- [x] Headers
- [x] Request body

However, this doesn't cover _all_ of the details required for a proper integration test because there are gaps in what we can express in an example. This includes the following features:
- [ ] Auth
- [ ] Global headers
- [ ] File upload/download endpoints
- [ ] Streaming endpoints

To fix this, we will need to:
1. Add support for these features in examples.
2. Validate that the examples match the user request provided to the mock server.

**Comment by dannysheridan** [comment]
closing in favor of https://linear.app/fern-api/issue/FER-673/[feature]-add-more-examples-and-validation-to-mock-server
