### ISSUE TITLE
`required: false` is ignored for form-data file uploads

### ISSUE THREAD

**Issue by billytrend-cohere** [fern-api/fern#2622]
**Describe the bug**
`required: false` is ignored for form-data file uploads.

**Fern Definition To Reproduce**
```
  requestBody:
    content:
      multipart/form-data:
        schema:
          type: object
          x-fern-audiences: ['public']
          properties:
            data:
              type: string
              x-fern-audiences: ['public']
              format: binary
              description: The file to upload
            eval_data:
              type: string
              x-fern-audiences: ['public']
              format: binary
              required: false
              description: An optional evaluation file to upload
```

**Expected behavior**

eval_data should be optional but it isn't. This appears to affect at least python and typescript, maybe the others too

**Screenshots**

<img width="509" alt="image" src="https://github.com/fern-api/fern/assets/144115527/abc7a8eb-e08c-49e5-8c7b-fc9506aac6eb">

**Comment by dannysheridan** [comment]
While working on this issue, we should consider tackling: https://github.com/fern-api/fern/issues/2775

**Comment by dannysheridan** [comment]
Looking at the Cohere Python SDK 5.13.4, this is fixed and `eval_data` is showing up as optional. As such, closing this issue. Feel free to re-engage if you have further questions.

https://github.com/cohere-ai/cohere-python/blob/bb92887eca34f781bfc4afbf57a81f7cadf2e299/src/cohere/datasets/client.py#L247
