### ISSUE TITLE
[Feature] Add automatic retry to Python client

### ISSUE THREAD

**Issue by menegais1** [fern-api/fern#2628]
### Problem description

The SDK functions currently lack automatic retries, requiring code modifications or custom wrappers to be implemented on the generated SDKs. 

### Why would it be useful?

Request retries are a basic feature for HTTP requests, preventing transient failures from returning errors to the system.

### Describe the solution (optional)

A simple way to implement this is using the built-in HTTPX retry strategy, passing it on the http methods calls. The following example illustrates that.

```python
retry_strategy = httpx.Retry(
    total=3,  # Total number of retries (including the initial request)
    status_forcelist=[500, 502, 503, 504],  # HTTP status codes to retry
    backoff_factor=0.5,  # Factor by which the delay increases after each retry
    method_whitelist=["GET"],  # HTTP methods to retry
)

with httpx.Client() as client:
        response = client.get(url, retry=retry_strategy)
```

**Comment by dannysheridan** [comment]
@amckinney this will be good to track in a SDK feature matrix. For missing features, feels logical to link to open issues would watch to track progress

**Comment by armandobelardo** [comment]
Hi there @menegais1, we've added this feature in version 0.11.8-rc1
Here's the changelog: https://github.com/fern-api/fern/blob/main/generators/python/sdk/CHANGELOG.md#0118-rc1---2024-03-02
