### ISSUE TITLE
[Bug] OpenAPI init included erroneous pipe |

### ISSUE THREAD

**Issue by mgregerson** [fern-api/fern#2634]
### Describe the bug

```yaml
|
  openapi: "3.0.0"
  info:
...
```

### To reproduce

1. Run the command 
2. 
```terminal

fern init --openapi https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore-expanded.yaml

```

### Expected behavior

A yaml file file should be generated that is valid. Instead, a pipe is being included that indicates it is a string, not a JSON object. 

### To fix this issue

Manually remove the pipe | at the top of the yaml file. Run fern check, and it should pass. 

### Version

Fern Version: 0.16.33

**Comment by dannysheridan** [comment]
closing but will reopen if another user runs into this same problem
