### ISSUE TITLE
[Feature] Generated fern docs URL should be clickable

### ISSUE THREAD

**Issue by mgregerson** [fern-api/fern#2635]
### Problem description

When a user generates new docs, a published docs url is provided to the user in their terminal. At the moment, this is not a clickable link. It would be better user experience if it was clickable. 

Example:

```terminal

mgregerson/migrate-docs* fern-testorg/test-org % fern generate --docs
[docs]: ✓ All checks passed
[docs]: Published docs to https://test-org.docs.buildwithfern.com (​https://test-org.docs.buildwithfern.com​)

```

### Helpful PR to reference

It may be helpful to reference www.github.com/fern-api/fern/pull/2391

**Comment by dannysheridan** [comment]
closing and will reopen if we have users customers report this frustration
