### ISSUE TITLE
[Feature] Allow ability to add bullet points in mdx files

### ISSUE THREAD

**Issue by mgregerson** [fern-api/fern#2636]
### Problem description

At the moment, when attempting to write a bullet point in an mdx page, anytime one tries to add a bullet point in an unordered list, it is rendered as a dash (ie. - ).

For example:

```markdown

* Creating a wallet
* Issuing a credential
* Presenting a credential to another wallet

```

These are rendered as hyphens as opposed to bullet points. 

### Why would it be useful?

Some client's current documentation includes bullet points. This way, we can stay as true to their vision as possible.

**Comment by dannysheridan** [comment]
closing for https://linear.app/fern-api/issue/FER-670/[feature]-allow-ability-to-add-bullet-points-in-mdx-files
