### ISSUE TITLE
[Feature] Allow ability to set a specific order of tags/endpoints within each tag. 

### ISSUE THREAD

**Issue by mgregerson** [fern-api/fern#2646]
### Problem description

At the moment, when developing new fern docs, we are not able to set a specific order of our tags/endpoints within each tag. With this ability, we could more closely mirror a client's existing documentation. 

### Why would it be useful?

Documentation will more closely align with existing documentation.

**Comment by dannysheridan** [comment]
closing for https://linear.app/fern-api/issue/FER-671/[feature]-allow-the-ability-to-set-a-specific-order-of-tagsendpoints
