### ISSUE TITLE
[Bug] Pages that result to 500 error get past fern check validations

### ISSUE THREAD

**Issue by SK-Sam** [fern-api/fern#2661]
### Describe the bug
I am able to run:
- `fern check`
- `fern generate`

without any errors thrown, but on the docs site generated I have pages that can lead to a `500` error.

### To reproduce

1. In any page, include `<ResponseField>Some arbitrary content</ResponseField>`
2. Run the command `fern generate --docs --log-level debug ` or `fern check` and see it succeed
3. Navigate to the page with this problematic content and see that it should lead to a `500` error instead of the page.

I understand that `<ResponseField>Some arbitrary content</ResponseField>` or content that shouldn't be parsed should be known to the user, but the visibility of `500` pages may be a problem for folks who depend on `fern check`

### Expected behavior
Error raised regarding `500` pages.

### Screenshots

<img width="415" alt="Screenshot 2024-01-18 at 2 15 34 PM" src="https://github.com/fern-api/fern/assets/10618376/a0097e88-1d3a-4fb6-84e4-cbafaea4f6fb">

### Version
Fern Version: 0.16.35

**Comment by dannysheridan** [comment]
+1 this Issue is relevant: https://github.com/fern-api/fern/issues/2536

**Comment by dannysheridan** [comment]
closing as a dup of https://github.com/fern-api/fern/issues/2536
