### ISSUE TITLE
[Fern's Documentation] Codeblock example leads to error

### ISSUE THREAD

**Issue by SK-Sam** [fern-api/fern#2669]
### What can be improved

[On this section](https://docs.buildwithfern.com/generate-docs/component-library/code-block) when copying down the example, the validations pass yet leads to an unintended code block. This is most likely due to a backslash before the backticks in the codeblock: https://github.com/fern-api/fern/blob/main/fern/docs/pages/docs/components/codeblock.mdx#L14

### Relevant Screenshots

When copied down: 
![Screenshot 2024-01-19 at 3 54 24 PM](https://github.com/fern-api/fern/assets/10618376/07e1920f-f559-4e16-84de-1b40d5fc1624)

When removing backslash from Fern docs example:
![Screenshot 2024-01-19 at 3 55 42 PM](https://github.com/fern-api/fern/assets/10618376/12cde77e-caa1-4551-8933-95873cd8def2)

**Comment by dannysheridan** [comment]
resolved by https://github.com/fern-api/fern/pull/2748
