### ISSUE TITLE
[Feature] Use Schema components inline

### ISSUE THREAD

**Issue by SK-Sam** [fern-api/fern#2670]
### Problem description

Schema styling that is being used in API references cannot be accessed inline. 

This sort of styling that describes a resource would be amazing to inline insert into markdown pages. 
![Screenshot 2024-01-19 at 5 26 25 PM](https://github.com/fern-api/fern/assets/10618376/f7eb36c4-f087-4a78-99e8-e6f03683244f)

### Why would it be useful?

It seems common enough that docs can describe a resource outside of API references sections.

### Describe the solution (optional)

Allow Fern user to include something like this in a markdown page:
```
<Schema>
name: Error Format
type: object
properties:
  status: string
  name: string
  title: string 
  detail: string
example: 
  {
     "status": 404,
     "name": "NOT_FOUND",
     "title": "NotFoundError",
     "detail": "Could not find organization Default Medical"
  }
</Schema>
```
And output something like this:

![Screenshot 2024-01-19 at 5 23 10 PM](https://github.com/fern-api/fern/assets/10618376/fcc10b2c-0472-414a-8d12-bed48b840e76)

**Comment by dannysheridan** [comment]
tracking internally in linear 👍
