### ISSUE TITLE
Running `fern generate` should not require a `fern.config.json`

### ISSUE THREAD

**Issue by zdunecki** [fern-api/fern#2681]
### Problem description

I would like to use `generate` without `fern.config.json`.

### Why would it be useful?

`generate` command can be independent from standard fern flow. In the future this code can be used also for another use cases where folks want to use generation their way.

### Describe the solution (optional)

[My solution](https://github.com/fern-api/fern/commit/bcc153d4337a01fcbcbdd2ac0a7a627bbb03aaa8)

**Comment by dannysheridan** [comment]
Curious to hear more about the use case. We're thinking about putting `generators.yml` and `fern.config.json` into a single file called `fern.yml` and wondering if this would be a more elegant solution.

https://github.com/fern-api/fern/issues/2623

**Comment by zdunecki** [comment]
@dannysheridan 

My use case is similar to how people want to use external APIs - it should be simple at first glance but super-power if you go deeper. Flexibility is also needed.

In the case of fern, I'd use core parts of your software and based on that build custom solutions. For example I don't need tokens or organization - it's too much connected with remote fern. That's why I've created [offline](https://github.com/fern-api/fern/issues/2617) proposal. 

You did awsome job but it seems a little bit hard to extract what's important for my use case.

**Comment by dannysheridan** [comment]
not on the roadmap to change this. haven't received other requests for this functionality
