### ISSUE TITLE
Add file as a primitive to support file uploads

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#269]
The definition would need to support multipart form uploads with files and form parameters.

**Comment by dannysheridan** [comment]
`We have an endpoint where we upload an image, and another endpoint where we retrieve an image. Can I do that with fern? How do I define that?`
 
https://fern-api.slack.com/archives/C03Q0NFCE3E/p1669922093756529

**Comment by dsinghvi** [comment]
this is now supported

**Comment by nlarusstone** [comment]
Is this supported in all languages or just in the Java SDK?

**Comment by dsinghvi** [comment]
Hey Nicholas -- it is supported in all SDK languages (you might have to upgrade your generator to the latest though). Which one are you using?

**Comment by nlarusstone** [comment]
We're using the FastAPI one:
```
      - name: fernapi/fern-fastapi-server
        version: 0.3.14
```

I saw https://github.com/fern-api/fern-python/pull/321 is still open, so I was wondering if maybe not all of the languages support it

**Comment by dsinghvi** [comment]
Yup, FastAPI doesn't support this yet unfortunately.

**Comment by dannysheridan** [comment]
closing in favor of https://github.com/fern-api/fern/issues/5270 which is more specific for FastAPI server codegen
