### ISSUE TITLE
[Bug] Client doesn't properly serialize enums in request parameters

### ISSUE THREAD

**Issue by wwohlers** [fern-api/fern#2697]
**Describe the bug**
Python client sends in the raw enum value as opposed to the equivalent serialized string as a request query parameter, causing a `422` response to a valid request.

**Fern Definition To Reproduce**
Any route with request query params that include an enum type.

**Expected behavior**
You can call the client route and pass in an enum value. Instead, the client responds with a `422` complaining about the type of the value passed in for the enum field.

**Versions**
 - Fern CLI: 0.15.5
 - Generator: 0.7.1

**Comment by dsinghvi** [comment]
This PR https://github.com/fern-api/fern/pull/2793 fixes enum serialization in inlined requests. We still need to fix the SDK for path params and query params.
