### ISSUE TITLE
[Bug] Recursive references in undiscriminated unions 

### ISSUE THREAD

**Issue by dvargas92495** [fern-api/fern#2699]
**Describe the bug**
If I define a recursive type in a undiscriminated union, Fern forgets to surround the recursive type in quotes causing compilation errors.

**OpenAPI Schema To Reproduce**
```
# shape.yml
    Json:
      oneOf:
      - type: boolean
      - type: integer
      - type: number
        format: double
      - type: string
        minLength: 1
      - type: array
        items:
          $ref: '#/components/schemas/Json'
      - type: object
        additionalProperties:
          $ref: '#/components/schemas/Json'
      nullable: true
```

From [here](https://github.com/vellum-ai/vellum-client-generator/pull/114/files#diff-b12ee94bc4f8259a3297c5b14fb6de75f26cde867436407eb55eed59c03fb3f8R2027-R2041)

**Expected behavior**

`Json = typing.Union[bool, int, float, str, typing.List[typing.Optional["Json"]], typing.Dict[str, typing.Optional["Json"]]]`

**Screenshots**

**Versions**
 - Fern CLI: "0.15.0-rc74"
 - Generator: 0.6.5

**Additional context**
[Slack Thread](https://vellum-ai.slack.com/archives/C052UMCSFA8/p1703200985482599)

**Comment by dsinghvi** [comment]
This should now be fixed!
