### ISSUE TITLE
[Feature] Configure more idiomatic Union type codegen

### ISSUE THREAD

**Issue by armandobelardo** [fern-api/fern#2701]
**Is your feature request related to a problem? Please describe.**
No problem, but the current discriminated union code gen could be simpler//easier to follow

**Describe the solution you'd like**
Pseudo code for the code gen for the different cases
```
#  Case 1: discriminated simple (variation on how simple discriminated union generator works)
type Shape = typing.Union[Square, Circle]
class Circle: 
  type: "square"
  radius: double

class Square: 
  type: "square"
  length: double


# Case 2: union (works today) -> undiscriminated union generator
type Shape = typing.Union[Square, Circle]
class Circle: 
  radius: double

class Square: 
  length: double

# Case 3: variation on how simple discriminated union generator works
# but for when you want to have discriminated unions, but also access the objects 
# without their discriminator fields
from pydantic import BaseModel

class Circle: 
  radius: double

class Square: 
  length: double

class Shape(BaseModel): 
  __root__ = typing.Union[ShapeSquare, ShapeCircle]

  class ShapeSquare("Shape"):
    type: "square"
    length: double

  class ShapeCircle("Shape"): 
    type: "circle"
    length: double

  def __init__(type: typing.Union[Circle, Square]):
    if type isinstance Circle:
      __root__ = ShapeCircle()
    else:
      if type isinstance Circle:
      __root__ = ShapeCircle()

```

**Comment by alexrejto** [comment]
Hey @dannysheridan, I'm a big fan of fern for python code-gen. I've run into this issue with discriminated unions. I see you marked the issue as completed but I don't see it in any recent releases. Can you point me to a python generator version I can try this out on?

**Comment by armandobelardo** [comment]
Hi @alexrejto thank you for the kind words! This was actually moved to an internal ticket for us to track (it should've probably been kept as a Github issue), but hasn't been fixed just yet, but it is definitely still on our radar
