### ISSUE TITLE
Missing parameters in the SDK functions when sending along with a file using octet-stream

### ISSUE THREAD

**Issue by rnxj** [fern-api/fern#2703]
**Description**
One of our endpoints takes in a file and some more parameters along with it. So when we were generating SDKs, there wasn't a way to send those params along with the file. 

**Fern Definition To Reproduce**
[fern.zip](https://github.com/fern-api/fern-python/files/13616695/fern.zip)

**Current behavior**
In the `client.py` file, the function definition now is:
`def route(self, *, request: bytes) -> typing.Iterator[bytes]:`

**Expected behavior**
In the `client.py` file, the definition should be:
`def route(self, *, request: bytes, email: str) -> typing.Iterator[bytes]:`

**Versions**
 - Fern CLI: 0.15.15
 - Generator: 0.7.2

**Comment by dannysheridan** [comment]
closing as we've made progress on file upload in the Python SDK and the `.zip` referenced is no longer available.
