### ISSUE TITLE
[Feature] Provide a pyproject.toml or setup.py when outpuit is local-file-system

### ISSUE THREAD

**Issue by hatemelseidy** [fern-api/fern#2713]
Right now the generated python SDK with local-file-system is not complete. It's missing `pyproject.toml` or `setup.py`. I had to reverse engineer the SDK to learn that it requires `pydantic` and `httpx`, created my own `setup.py` manually and created a simple workflow to copy that to generated sdk and install it locally for testing.

My `setup.py` is pretty minimalistic, and looks pretty much like the below.

```
from setuptools import find_packages, setup

setup(
    ...
    packages=find_packages(),
    version="1.0.0",
    install_requires=[
        "pydantic",
        "httpx",
    ],
)
```

**Comment by armandobelardo** [comment]
This is intentional! Local file output today is not meant to be packable out of the box! Some of the reasons include that it depends on where you are outputting the code to and what it is for as mentioned above


(Also Pydantic 2 is supported)
