### ISSUE TITLE
[Feature] Admin-toggleable link directly to GH source at bottom of each docs page

### ISSUE THREAD

**Issue by minaelee** [fern-api/fern#2723]
### Problem description

It can be difficult to figure out what page in the GH repo maps to each page in the documentation website.

### Why would it be useful?

When you find an issue with a docs page, helps you to go directly to the source. Would make it painless for volunteer contributors to fix a simple typo, for example. Currently I'm working off guessing/memory/referencing docs.yml and none of these are fun.

### Describe the solution (optional)

Feature request: Toggleable admin setting to automatically add a link to each documentation page that takes you directly to the corresponding GH source.

Example: Scroll to the bottom of  https://docs.pingcap.com/tidbcloud/connect-via-standard-connection-serverless and click the link just above the "Was this page helpful?" text. It will take you directly to the source of that page in GH.

It also shows the last update timestamp and a link to the previous commit, but in my view, that unnecessarily clutters the UI. I would be happy to see a simple GH logo at the bottom that takes you to the source.

**Comment by dannysheridan** [comment]
@abvthecity was just talking about this today! Will add to the roadmap.

**Comment by dannysheridan** [comment]
we're planning to make it easier to edit pages without leaving your browser. I don't think this will be the exact implementation but we're incorporating the problem shared here!
