### ISSUE TITLE
[Bug] Unnecessary required boolean field in Java client

### ISSUE THREAD

**Issue by billytrend-cohere** [fern-api/fern#2732]
**Describe the bug**

Streaming API requires the boolean field to be populated even when using xyzStream function

**Screenshots**

![image](https://github.com/fern-api/fern-java/assets/144115527/8d0bf6f3-f44d-4da1-ba2f-b9942fcdc998)

**Comment by armandobelardo** [comment]
This is resolved in the latest version of the Java SDK, connected offline!
