### ISSUE TITLE
[Feature] Make HTTP request timeout configurable

### ISSUE THREAD

**Issue by Swimburger** [fern-api/fern#2733]
**Is your feature request related to a problem? Please describe.**
We have API endpoints that use LLMs which take longer to process than usual HTTP requests,
which causes timeout exceptions.

**Describe the solution you'd like**
Let us configure the timeouts for the entire API and maybe even per endpoint.

**Comment by armandobelardo** [comment]
Closing this out as Java now supports per-request timeouts as of version 0.8.4 of the Java generator
I believe Niels is already using this, so not tagging!
Changelog entry: https://github.com/fern-api/fern/blob/main/generators/java/sdk/CHANGELOG.md#084---2024-02-23
