### ISSUE TITLE
Support file streams to upload files rather than using byte arrays

### ISSUE THREAD

**Issue by Swimburger** [fern-api/fern#2734]
Currently, file uploads are generated using byte arrays, but this forces users to load entire files into memory.
File uploads should have a stream overload. In most cases, the file stream should be from local disk, but files streamed from the network should also be supported.

**Comment by Swimburger** [comment]
I know this has been solved for Java and C# based on AssemblyAI work I did. Not sure if all SDKs support streaming file uploads. For Ruby, we hand wrote this functionality.

**Comment by dannysheridan** [comment]
Going to close this out and if a user runs into a language-specific question, we can open a new issue.
