### ISSUE TITLE
Add convenience function for named file upload in Go client

### ISSUE THREAD

**Issue by billytrend-cohere** [fern-api/fern#2737]
**Describe the bug**

Currently if you want to upload a file with a file name you have to create a wrapper for it like this:

```
type MyReader struct {
	io.Reader
	name string
}

func (m *MyReader) Name() string {
	return m.name
}

r := &MyReader{Reader: strings.NewReader("hello world"), name: "hello.txt"}

```

It would me nice if this sort of helper was exported by the sdk.

**Comment by dsinghvi** [comment]
This is resolved in Go SDK [0.29.0](https://buildwithfern.com/learn/sdks/introduction/changelog/go#0290)! I
