### ISSUE TITLE
[Fern's Documentation] Broken images in Fast API boilerplate page

### ISSUE THREAD

**Issue by minaelee** [fern-api/fern#2747]
### What can be improved

Broken images in https://docs.buildwithfern.com/server-boilerplate/server-boilerplate/fast-api#step-4--compile

### Relevant Screenshots

![image](https://github.com/fern-api/fern/assets/4936954/0f6ee204-b66b-4419-9f1c-95f3473670a8)

The screenshot image PNG names are:
```
![Invalid return value](../images/invalid_return_value.png)
![Invalid signature](../images/invalid_signature.png)
```

I searched the repo and didn't find either PNG so they likely need to be recreated.

**Comment by dannysheridan** [comment]
Here are the PNGs hosted from a Fern S3 bucket:

https://fern-image-hosting.s3.amazonaws.com/fern/invalid_return_value.png
https://fern-image-hosting.s3.amazonaws.com/fern/invalid_signature.png
