### ISSUE TITLE
[Feature] Support file uploads in Postman Collection

### ISSUE THREAD

**Issue by Swimburger** [fern-api/fern#2752]
**Is your feature request related to a problem? Please describe.**
The postman generator doesn't support file uploads and thus the file upload endpoints are skipped.

**Describe the solution you'd like**
Add support for file upload endpoints.

**Comment by dannysheridan** [comment]
@Swimburger I haven't received another request for this from a Fern user, so closing this out. Can re-engage if others run into this down the road!
