### ISSUE TITLE
Specify API key variable name in Postman Collection

### ISSUE THREAD

**Issue by Swimburger** [fern-api/fern#2753]
**Is your feature request related to a problem? Please describe.**
The name for the API key variable currently defaults to `apiKey`.
I'd like to change this name so the name is more self-describing.
In my case, I'd like to change it to `ASSEMBLYAI_API_KEY` as that's usually the env variable name we use in our documentation.

**Describe the solution you'd like**
Let us configure the name of the API key variable name via the generator or via an extension in the OpenAPI spec.

Kindly guide me to an existing solution if I missed it :)

**Comment by dannysheridan** [comment]
@Swimburger I haven't received another request for this from a Fern user, so closing this out. Can re-engage if others run into this down the road!
