### ISSUE TITLE
Missing support for deprecated annotations

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2758]
We need to add support for recognizing the `Deprecated` [AvailabilityStatus](https://github.com/fern-api/fern/blob/c30dc1c8250ddcebee1f946e6c805cbef61dded1/fern/apis/ir-types-v32/definition/commons.yml#L74) so that we can include a `Deprecated: ...` comment according to Go's documentation [style guide](https://github.com/golang/go/wiki/Deprecated).

Along with this change, we should incorporate changes into `seed` (i.e. via a `seed publish` command) so that generators start revealing what features they've implemented. That way we can host a feature matrix of all the generators and quickly recognize where the gaps are. We imagine the structure will be something as simple as the following:

```yaml
Features: 
  properties: 
    supportsAvailability: boolean
    ...
```

**Comment by dannysheridan** [comment]
closing and moving https://linear.app/fern-api/issue/FER-656/[feature]-support-deprecated-annotations
