### ISSUE TITLE
[Bug] Few CI steps does not pass

### ISSUE THREAD

**Issue by zdunecki** [fern-api/fern#2763]
### Describe the bug
It looks like an issue in CI process. For two steps (docs and ete-tests) looks like a fern token is invalid or missing (I guess). It's not my local machine, it's a Github server so it should work remotely.

### To reproduce
Make PR where docs or ete-tests are needed.

### Expected behavior
This CI steps should be passed. 

### Screenshots

<img width="1776" alt="Screenshot 2024-01-24 at 01 06 47" src="https://github.com/fern-api/fern/assets/18244904/25b0b1f1-25b9-4b1d-9508-e3c9ce25ab6e">

<img width="1773" alt="Screenshot 2024-01-24 at 01 04 34" src="https://github.com/fern-api/fern/assets/18244904/90009971-71cc-43c2-9850-283f3e1fc88b">

**Comment by dannysheridan** [comment]
+1 

example of ETE tests failing elsewhere: https://github.com/fern-api/fern/pull/2639
example of preview docs failing elsewhere: https://github.com/fern-api/fern/pull/2762

**Comment by minaelee** [comment]
Looks like preview-docs fails for anyone not in fern org:
https://github.com/fern-api/fern/actions/workflows/preview-docs.yml

**Comment by dannysheridan** [comment]
@minaelee I think this stems from the use `FERN_TOKEN` in the workflow. github secrets may not be accessible to workflows triggered by pull requests from forks.

do you think we can use `workflow_dispatch` to allow a core maintainer to trigger the GitHub Action?

**Comment by zdunecki** [comment]
@dannysheridan @minaelee 

I see few solutions to solve that. 

You can add notice into CONTRIBUTING.md that contributors must add a secret with a fern token inside the forked repo. You could share these tokens in Discord or elsewhere (maybe in some automated way). 

If the above solution is not possible or you don't like that maybe you could add some script inside GitHub workflows to fetch tokens internally on behalf of contribution - then you don't have to share your tokens with folks.

Manual dispatch looks fine but probably you'll need more manual effort for you.

If you see another solution to fix that, great to discuss that.

**Comment by dannysheridan** [comment]
I'd prefer not to share the fern token secret. Let's do the manual effort approach for now! Would take a PR to include in our github actions if either of y'all are up for it.

**Comment by dannysheridan** [comment]
Allowing `fern generate --docs --preview` to work in `fern-api/fern` is enabled with this PR: https://github.com/fern-api/fern/commit/ddfbac3b642d328f9b5da424fb706fdfb1e0c517
