### ISSUE TITLE
[Feature] Validate integers/doubles in the client

### ISSUE THREAD

**Issue by drizco** [fern-api/fern#2778]
**Is your feature request related to a problem? Please describe.**
defining a request body property as an `integer` does not prevent floats from being sent

**Describe the solution you'd like**
typescript does not have an integer type, so the request type is `number`. I was hoping it was possible to validate the request body in the client?

**Comment by dannysheridan** [comment]
@drizco more information would be helpful for me to be clear what you're looking for. Mind opening a new issue (with a more detailed template) if this is important for you still? Thanks!

https://github.com/fern-api/fern/issues/new?assignees=dsheridan&labels=product%2Fsdk-generator%2Cfeature&projects=&template=sdk-feature.yml
