### ISSUE TITLE
[Feature] Serde errors should include some tracing information

### ISSUE THREAD

**Issue by coltondotio** [fern-api/fern#2779]
Our back-end recently returned a null value where fern was expecting a list. The Fern SDK threw an error during deserialization, but the error did not include any information that pointed me in the direction of the failing endpoint -> field.

**Comment by dannysheridan** [comment]
closing this out as we've added many more validation rules into the `fern check` experience in the last year. if this becomes an issue again in the future, please re-engage so we can prioritize.
