### ISSUE TITLE
[Fern's Documentation] Screenshots too small to see

### ISSUE THREAD

**Issue by minaelee** [fern-api/fern#2788]
### What can be improved

The screenshots on this page:
https://docs.buildwithfern.com/generate-docs/configurations/endpoint-errors
are too small to be useful. 

### Relevant Screenshots

A screenshot of a screenshot? So meta.

### Link a PR (optional)

Recommend replacing with screenshots that are zoomed in/cropped.

**Comment by dannysheridan** [comment]
We now zoom into images upon being clicked by a user. Fixed!
