### ISSUE TITLE
[Python] Root cause why `update_forward_refs()` doesn't work when inheriting

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2900]
## Describe the Bug
When circular dependencies are incurred through inheritance, Pydantic doesn't like it. 

## Information to Reproduce
See this commit on Vellum's Python SDK (https://github.com/vellum-ai/vellum-client-python/pull/16) 

There are a couple options: 
- Inline union properties directly instead of inheriting (so this never happens)
- Support OpenAPI friendly unions (which contain the discriminant)

**Comment by armandobelardo** [comment]
Tracking in Linear!
