### ISSUE TITLE
User reports high CPU utilization on cohere-typescript

### ISSUE THREAD

**Issue by billytrend-cohere** [fern-api/fern#2918]
### Describe the bug
User report:

> After debugging for some time, we finally decided to make requests directly using the axios library and things went smoothly after that.
> Unfortunately I didn't record the errors but I'll try my best to describe them in case it's helpful to your team:
> - cpu was unusually elevated when using the cohere sdk (v7.2.0) vs axios - pegged at 100% vs 20-30% with axios
> - we also saw strange ssl connection timeout issues which would hang up requests unpredictably
> - i believe we also had some issues with elevated memory

**Comment by dannysheridan** [comment]
Closing in favor of https://github.com/cohere-ai/cohere-typescript/issues/211 tracked on the `cohere-ai/cohere-typescript` repo.
