### ISSUE TITLE
[Feature] Specify request timeouts on client SDKs

### ISSUE THREAD

**Issue by thesandlord** [fern-api/fern#2922]
Currently with the Java SDK, the default timeout is 10 seconds. Some API requests take much longer, so the SDK is timing out. Having an optional parameter either per API call or when initializing the SDK to set the timeout would alleviate this issue.

Not sure if the other SDKs have this option already, but if not, they all should!

**Comment by dsinghvi** [comment]
Thanks for filing @thesandlord, this is currently configurable in TypeScript, Go, and Ruby but not in Java or Python. cc @armandobelardo

**Comment by dannysheridan** [comment]
This is now live!
