### ISSUE TITLE
[Feature] support pass `abortSignal` into options

### ISSUE THREAD

**Issue by himself65** [fern-api/fern#2980]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dannysheridan** [comment]
From @billey-trend


> I guess through request options https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

**Comment by tomtobac** [comment]
+1 on this

**Comment by armandobelardo** [comment]
This is now available on version `0.20.0-rc1` of the Typescript generator: https://github.com/fern-api/fern/blob/main/generators/typescript/sdk/CHANGELOG.md#0200-rc1---2024-05-20
