### ISSUE TITLE
Support code sample generation for bytes requests

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#3016]
## Describe the Bug
Generate request code samples for bytes endpoints. 

## Information to Reproduce
See the ElevenLabs Issue https://github.com/elevenlabs/elevenlabs-python/issues/185

**Comment by dannysheridan** [comment]
From https://github.com/elevenlabs/elevenlabs-python/issues/185#issuecomment-1992320242 

> @bryanhpchiang this is now fixed with our latest beta release v1.0.0b0. Please re-open the issue if you still have any problems!
