### ISSUE TITLE
[Bug] Manifest unknown for fern-typescript-express 0.9.7

### ISSUE THREAD

**Issue by Danwakeem** [fern-api/fern#3058]
### Describe the bug
When I was trying out the server boiler plate I was not able to generate typescript server boiler plate with `0.9.7`.

### To reproduce

1. Init fern `fern init`
2. Change default generator from `fernapi/fern-typescript-node-sdk` 👉  `fernapi/fern-typescript-express`
3. Change generator version from `0.9.5` 👉 `0.9.7`
4. Generate default definitions `fern generate --local`
5. See error message

### Expected behavior
I expected the generation to work for the default definitions

### Screenshots
<img width="1433" alt="Screenshot 2024-02-25 at 8 25 14 PM" src="https://github.com/fern-api/fern/assets/1753824/7e6422d5-b586-4163-999c-9e3cb202437a">

### Version
Fern Version: `0.18.3`

### Additional context

- I copied the generator definition from the [docs page here](https://docs.buildwithfern.com/server-boilerplate).
- If I use the previous version `0.9.6` it generates alright 😈 
- Your README mentions `fernapi/fern-express-server` not `fernapi/fern-typescript-express` 🤷‍♂️  I am assuming this was a mistake so I opend a [PR](https://github.com/fern-api/fern/pull/3057) 😈

**Comment by armandobelardo** [comment]
Fixed by https://github.com/fern-api/fern/pull/3084
