### ISSUE TITLE
[Bug] Inconsistencies between Fern Definition availability and x-fern-availability extension

### ISSUE THREAD

**Issue by minaelee** [fern-api/fern#3080]
### Describe the bug

For the Fern Definition `availability` property to produce the `Beta` tag in Fern Docs, you must use `in-development` or `pre-release`. You cannot use `beta`.

For the `x-fern-availability` openapi extension to produce the `Beta` tag in Fern Docs, you must use `in-development` or `beta`. You cannot use `pre-release`.

### Expected behavior
These should be consistent with each other. 

### Version
Fern Version: 0.18.4

### Additional context
Note; The Fern component of Availability has a yet another set of options:
```type: 'beta' | 'GA' | 'deprecated'```
I find this less relevant though as that just echoes the tag that's created.

**Comment by dannysheridan** [comment]
nice find of an inconsistency!  cc: @dsinghvi for awareness

**Comment by minaelee** [comment]
Closing per tracking internally.
