### ISSUE TITLE
[Bug] Colon's in Meta Tags Break Formatting in Docs

### ISSUE THREAD

**Issue by noanflaherty** [fern-api/fern#3133]
Since front matter is essentially YAML, using a colon in front matter like this will cause the page to break:

```
---
title: Welcome to Vellum: AI product development platform
---
```

This can be fixed by using a `>` character, like this:

```
---
title: >
  Welcome to Vellum: AI product development platform
---
```

Will add this to the docs for front matter. However, a user (from Vellum) requested that `fern check` should look for and warn about this.  

Discussed here: [https://github.com/fern-api/fern/issues/3133](https://github.com/fern-api/fern/issues/3133)

**Comment by minaelee** [comment]
Thanks for the report, Noah. Front matter is essentially YAML and you can escape the `:` by using a `>` character like this:

```yaml
title: >
  Welcome to Vellum: AI product development platform
```

Please try it and let us know if it works for you. We'll get that into the documentation!

**Comment by noanflaherty** [comment]
Thanks @minaelee – We'll do this. Adding to the docs would be great, but would still love for `fern check` to warn me of this given how easy of a mistake it is to make.
