### ISSUE TITLE
TypeScript generator docs list wrong latest version

### ISSUE THREAD

**Issue by mstade** [fern-api/fern#3256]
## Describe the Bug

The latest TypeScript browser generator version according to the docs is `0.9.5`, see: https://docs.buildwithfern.com/generate-sd-ks/generators/type-script-browser-sdk

The same is true for the node generator. Furthermore, the link to the source is wrong: https://github.com/fern-api/fern-typescript

Meanwhile, the Fern repo readme lists these versions: https://github.com/fern-api/fern?tab=readme-ov-file#sdk-generators

In that table (and at the time of writing this issue) the latest version is `0.12.8`. This version does not seem correct either, here's the output of trying to run that version:

```sh
[management]: ✓ All checks passed
[management]: fernapi/fern-typescript-browser-sdk (HTTP code 404) unexpected - manifest for fernapi/fern-typescript-browser-sdk:0.12.8 not found: manifest unknown: manifest unknown 
┌─
│ x  fernapi/fern-typescript-browser-sdk
└─
```

It does seem to work with `0.12.7` however.

### CLI Version

`0.19.18`

### Actual Behavior

The docs list the wrong latest version and the link to the generator source is wrong.

### Expected Behavior

The docs should list the correct latest versions and not have broken links.

### API Definition (if relevant)

n/a

## Additional Context

n/a

**Comment by abvthecity** [comment]
Hey @mstade thanks for the bug report. looks like 0.12.8 failed to publish. And that's a great point, we'll update the docs soon with the right versions.

**Comment by mstade** [comment]
So it turns out it looks like you link to two different deployments of your docs:

- Clicking the `Get Started` link on your website goes to: https://docs.buildwithfern.com/overview/welcome/quickstart
- clicking the `Documentation` link on your website goes to: https://buildwithfern.com/learn/overview/introduction

The latter seems to be more updated, but not 100% in line with actual changelogs in the generators it seems – the [TypeScript generator page](https://buildwithfern.com/learn/sdks/sdk-generators/typescript) for example states `0.12.6` as the latest version but in actuality it's `0.12.9` [as stated in the changelog](https://github.com/fern-api/fern/blob/main/generators/typescript/sdk/CHANGELOG.md).

I'm sure I'm not the only one who's gotten turned around a few times by this.

**Comment by dannysheridan** [comment]
all docs links now 404, so this info has moved. closing this out as unresolved.
