### ISSUE TITLE
[Bug] Using `require` to import `node-fetch` breaks when output is ESM

### ISSUE THREAD

**Issue by mstade** [fern-api/fern#3260]
## Describe the Bug

When generating a TypeScript SDK locally it's possible to have greater control over how the project is built, including providing both CJS and ESM module formats. Using ESM however breaks without further processing, due to the use of `require` in the core `Fetcher`:

https://github.com/fern-api/fern/blob/3eabb82533f4334fac829e2412ea168e71db0891/generators/typescript/utils/core-utilities/fetcher/src/fetcher/Fetcher.ts#L82-L89

This should probably use dynamic `import()` instead, and rely on the build process to translate this to `require()` calls where relevant.

### CLI Version

`0.19.18`

### Generator Version

`0.12.7`

### API Definition

The minimal OpenAPI specification or Fern definition required to reproduce the bug.

```yaml
types:
  Pet:
    name: string
    age: double
```

### Actual SDK

The buggy SDK that is produced:

https://github.com/fern-api/fern/blob/3eabb82533f4334fac829e2412ea168e71db0891/generators/typescript/utils/core-utilities/fetcher/src/fetcher/Fetcher.ts#L82-L89

### Expected SDK

I would expect something like this:

```typescript
    const fetchFn =
        RUNTIME.type === "node"
            ? // `.default` is required due to this issue:
              // https://github.com/node-fetch/node-fetch/issues/450#issuecomment-387045223
              (await import("node-fetch")).default
            : typeof fetch == "function"
            ? fetch
            : (await import("node-fetch")).default;
```

But perhaps this should just always check for `fetch` first, given it's available in recent Node runtimes. Makes it a little less complex:

```typescript
    const fetchFn =
        typeof fetch === "function"
            ? fetch
            : // `.default` is required due to this issue:
              // https://github.com/node-fetch/node-fetch/issues/450#issuecomment-387045223
              (await import("node-fetch")).default
```

**Comment by joemckenney** [comment]
I'm also running into this when upgrading our clients generators to the latest version.
