### ISSUE TITLE
Update "Publish a Java SDK to Maven Central" Registration Process

### ISSUE THREAD

**Issue by amy-keibler** [fern-api/fern#3294]
### What can be improved

Hello, I'm opening this on behalf of the Maven Central team. We just wanted to let you know that our [Account Registration](https://central.sonatype.org/register/central-portal/) and [Namespace / `groupId` Registration](https://central.sonatype.org/register/central-portal/) processes have changed, so the [`fern/docs/pages/fern-sdks/guides/publish-to-maven-central.mdx`](https://github.com/fern-api/fern/blob/main/fern/docs/pages/fern-sdks/guides/publish-to-maven-central.mdx) documentation is no longer accurate. We got a support request by a user that mentioned that documentation, so we thought it would be a good idea to reach out.

(if you're curious about the details, we [deprecated `issues.sonatype.org` due JIRA on-prem reaching its end-of-life](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/))

### Relevant Screenshots

The content to be reworked would be steps 2-5, but we can provide screenshots if that is desired.

**Comment by dannysheridan** [comment]
Hey @amy-keibler thanks for letting us know! This is really helpful.

Would you be up to make a contribution? Here's the Markdown behind that page: https://github.com/fern-api/fern/blob/main/fern/docs/pages/fern-sdks/guides/publish-to-maven-central.mdx

**Comment by dannysheridan** [comment]
We're updated the documentation about [Publishing your Java SDK with Maven](
https://buildwithfern.com/learn/sdks/guides/publish-to-package-managers/maven-central)
