### ISSUE TITLE
How to remove a generated doc url from my account? 

### ISSUE THREAD

**Issue by mb-suhailc** [fern-api/fern#3353]
### Problem description
I had created a doc instance using Fern CLI. How do I delete this instance from my account and also the organization so that I could use the same URL with a different GitHub account. Is there a way this can be done since I need to use a specific GitHub account as a part of organizing our project?

**Comment by dannysheridan** [comment]
This can't be done self-service yet. Please reach out to support (at) buildwithfern.com to request the deletion of an instance.
