### ISSUE TITLE
Incorrect Sizing on Custom Icons on Callout Component

### ISSUE THREAD

**Issue by mgregerson** [fern-api/fern#3357]
## Describe the Bug

Custom Icons are coming in too large when you provide a custom Icon to the `Callout` component. 

## Information to Reproduce

```
<Callout intent="note" icon="fa-light fa-circle-info">
If you’re not on Nest.js, remember to set `experimentalDecorators` to `true` in your `tsconfig.json`.
</Callout>
```

This renders:

<img width="700" alt="Screenshot 2024-04-10 at 1 55 14 PM" src="https://github.com/fern-api/fern/assets/105083434/b70ee4f7-6bf8-4b16-bd22-b4636fe64712">

### CLI Version

0.20.0

**Comment by chdeskur** [comment]
![Screenshot 2024-11-30 at 5 42 04 PM](https://github.com/user-attachments/assets/88985ff5-a2d4-4a4a-ac18-e92055e2bf3e)

This is resolved on Fern `v0.45.1`
