### ISSUE TITLE
ts-morph exception using PayPal OpenAPI spec

### ISSUE THREAD

**Issue by johnpyp** [fern-api/fern#3415]
## Describe the Bug

Failure when generating from public paypal OpenAPI specs.
```
# .... Lots of logs
Generating /src/serialization/types/SubscriptionsCreate422DetailsItem.ts
Sent error event to coordinator
/nodeCli.cjs:179343
            throw new common2.errors.NotImplementedError(`Unexpected! Inserting syntax kind of ${common2.getSyntaxKindName(expectedKind)}, but ${child.getKindName()} was inserted.`);
                  ^

NotImplementedError: Unexpected! Inserting syntax kind of InterfaceDeclaration, but ExpressionStatement was inserted.
    at getRangeWithoutCommentsFromArray (/nodeCli.cjs:179343:19)
    at insertIntoBracesOrSourceFileWithGetChildren (/nodeCli.cjs:180859:14)
    at ModuleDeclaration._insertChildren (/nodeCli.cjs:189483:18)
    at ModuleDeclaration.insertInterfaces (/nodeCli.cjs:189297:23)
    at ModuleDeclaration.addInterfaces (/nodeCli.cjs:189291:23)
    at ModuleDeclaration.addInterface (/nodeCli.cjs:189288:23)
    at _GeneratedUnionSchema.generateRawTypeDeclaration (/nodeCli.cjs:277148:34)
    at _GeneratedUnionSchema.generateModule (/nodeCli.cjs:277112:10)
    at _GeneratedUnionSchema.writeSchemaToFile (/nodeCli.cjs:277095:10)
    at _GeneratedUnionSchema.writeSchemaToFile (/nodeCli.cjs:277227:11)

Node.js v18.1.0
```

Seems to be related to some unexpected ts-morph invariant being broken, but I'm not sure.

### CLI Version

The version of the Fern CLI you are
using (found in `fern.config.json`).

Local build, latest commit https://github.com/fern-api/fern/commit/079a084cd98cb6f8e2a34bf784f71210cda32a4b

### Generator Version

The version of the generator you are using (found in `generators.yml`). Plus any custom configuration required to reproduce the bug (found in `generators.yml`).

Bug happens on Typescript generators 0.13.0 / 0.15.0-rc0 / any I've tested

```
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-typescript-node-sdk
        version: 0.13.0
        output:
          location: local-file-system
          path: ../generated/sdks/typescript
```

I also tried the Python generator, and it generated successfully.

### API Definition

Here's the spec that causes the issue: https://github.com/paypal/paypal-rest-api-specifications/raw/main/openapi/billing_subscriptions_v1.json

I'm not sure what the minimal reproduction is unfortunately, I'm not even sure what causes the issue. However, running generate on this api should cause the issue pretty easily.

### Actual SDK

The buggy SDK that is produced: N/A  (errors out)

### Expected SDK

N/A

## Additional Context

To reproduce, I'd just try the minimal init / generate from the above using `--openapi`, it should happen pretty easily.

**Comment by dannysheridan** [comment]
Closing as stale. Now that the typescript generator version is [0.42.5](https://github.com/fern-api/fern/blob/main/generators/typescript/sdk/VERSION), lots has changed since this report was filed.

If anyone runs into this and finds it to still be an issue, please let me know and I can re-open this issue.
