### ISSUE TITLE
How to set user-agent string in generated SDKs

### ISSUE THREAD

**Issue by Arkessler** [fern-api/fern#3453]
### What can be improved

I'm trying to figure out if it's currently possible to set a user-agent string in generated SDKs. 

I found this Issue about it: https://github.com/fern-api/fern/issues/2264. Hard to tell from the history on that Issue whether support was added, and if it was I can't find "user-agent" anywhere in the docs.

If this is supported, could somebody advise on how to set it?

**Comment by mstade** [comment]
@dannysheridan you closed #2264 that this ticket references – any chance you can provide any guidance on this? Thank you! 🙏

**Comment by dannysheridan** [comment]
Howdy @Arkessler and @mstade! Sending a `user-agent` string (e.g., `User-Agent: ${package}/${version}`) is not currently supported.

Today Fern includes the following request headers for the same purpose:
```ts
"X-Fern-Language": "${language}",
"X-Fern-SDK-Name": "${package}",
"X-Fern-SDK-Version": "${version}",
```

A user of Fern has added a UserAgent themselves. If helpful, here's a link the PR: https://github.com/AssemblyAI/assemblyai-java-sdk/pull/105/files

**Comment by dannysheridan** [comment]
@amckinney do you plan to support this feature? If not, let's close this issue as `not planned`.

**Comment by amckinney** [comment]
This feature is being rolled out now that its part of Fern's IR ([PR](https://github.com/fern-api/fern/pull/4232)). For example, this is available in [TypeScript](https://github.com/fern-api/fern/pull/4234) and [C#](https://github.com/fern-api/fern/pull/4380). 

Fern SDKs will send the `User-Agent` header in the `<package>/<version>` format. If you want to send a custom `User-Agent` header, you can set an arbitrary HTTP header using the specific language's mechanism. 

For example, consider the following Go use case:

```go
header := make(http.Header)
header.Add("User-Agent", "your/custom/user-agent")
client := acmeclient.NewClient(
  option.WithHTTPHeader(header), // These headers are sent on every request.
)
```
