### ISSUE TITLE
[Bug] Incorrect Redirect from "Fern Definition" Link on OpenAPI Overview Page

### ISSUE THREAD

**Issue by last-developer** [fern-api/fern#3566]
## Describe the Bug
There is a navigation issue on the [OpenAPI Overview page](https://buildwithfern.com/learn/api-definition/openapi/overview) under the API Definition section. Currently, when users click on the "Fern Definition" link, they are redirected to the homepage (https://buildwithfern.com/learn/home) instead of the specific page for Fern Definition.
![Screenshot 2024-05-08 140849](https://github.com/fern-api/fern/assets/128787057/e5679ec0-9b20-4c82-b311-4c068771f270)

Expected behavior:
The "Fern Definition" link should redirect users to the Fern Definition overview page at https://buildwithfern.com/learn/api-definition/fern/overview.

## Steps to Reproduce
1)Go to https://buildwithfern.com/learn/api-definition/openapi/overview.
2)Click on "Fern Definition" link.
3)Observe the redirection to the homepage rather than the expected Fern Definition overview page.

### CLI Version
version: 0.23.1-rc6

## Proposed solution:
Please update the "Fern Definition" link to correctly point to https://buildwithfern.com/learn/api-definition/fern/overview.

This adjustment will improve navigation and user experience, ensuring that users can easily access the correct documentation for Fern Definition.

**Comment by last-developer** [comment]
Please assign this to me, i got the solution

**Comment by last-developer** [comment]
hey @abvthecity are you there??

**Comment by dsinghvi** [comment]
Hey @last-developer, thanks for the fix! feel free to tag @dsinghvi in the future
