### ISSUE TITLE
[Bug] local generate and token

### ISSUE THREAD

**Issue by Amenocy** [fern-api/fern#3790]
### Describe the bug

since local docker-based generation, doesn't need Token,  

in packages/cli/cli/src/commands/generate/generateAPIWorkspaces.ts , generation type should be checked to throw askToLogin error.
unless you want to force users to work with Github! or give their repo access to Fern in any case!

**Comment by Amenocy** [comment]
there is a PR regarding this problem : https://github.com/fern-api/fern/pull/2551

**Comment by dsinghvi** [comment]
Fixed here https://github.com/fern-api/fern/pull/4239
