### ISSUE TITLE
UX for multiple workspaces

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#385]
- workspaces should be aliased in `fern.config.json`
I could see fern.config.json changing to 
```json
{
  "workspaces": {
     "coordinator-api": "/path/to/coordinator"
  }
}
```
We can get rid of the "auto find all your .fernrcs" which also creates problems for us in this repo when we add a ton of nested fern api workspaces for testing. 

- fern init asks you for an api name and will add to the `fern.config.json` and initialize a new workspace

- fern generate asks you what workspace you want to generate for if you forget to specify!

**Comment by dsinghvi** [comment]
@zachkirsch curious for your thoughts

**Comment by zachkirsch** [comment]
Can we use the name from the `.fernrc` rather than specifying it in fern.config.json?

**Comment by zachkirsch** [comment]
Or is the idea we get rid of `.fernrc` in general?

**Comment by zachkirsch** [comment]
this is onde
