### ISSUE TITLE
Authentication failed with CLI Command fern token

### ISSUE THREAD

**Issue by vincebrechbuehl** [fern-api/fern#3867]
### Describe the bug
I want to use the Fern CLI inside of a VMWare with Ubuntu 22.04.

1. I have setup my project and cloned the starter template how it was described in the [Quickstart](https://buildwithfern.com/learn/docs/getting-started/quickstart). 
2.  When i try to generate a token with the debug option I get a error 'Failed to authenticate' for details look the the screenshot above.
3. I have also tried 'fern login', which opens a Google Chrome browser, where I could login against Github with success but on the terminal I get the same error like with the previous step.

### To reproduce

1. Go to Terminal
2. Run the command 'fern login' or 'fern token'
3. See error

### Expected behavior
Normally it should create a secret.

### Screenshots
<img width="1146" alt="Screenshot 2024-06-18 124451" src="https://github.com/fern-api/fern/assets/34165172/aff13119-28b4-4d13-b721-77777d7ad268">

### CLI Version
- The version of the Fern CLI you are using (found in `fern.config.json`).
"version": "0.29.6"
- Node v20.14.0

**Comment by dannysheridan** [comment]
Haven't received other requests for this. If it blocks you from using Fern and you'd like to, please feel free to drop me a message in our [Community Slack](https://join.slack.com/t/fern-community/shared_invite/zt-2dpftfmif-MuAegl8AfP_PK8s2tx350Q)!
