### ISSUE TITLE
Rename Workspace and WorkspaceDefinition to more descriptive names

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#397]
https://www.notion.so/usebirch/Fern-Workspace-Terminology-dae519a16ce1421fac15f377c0c82550

```
repo/
  api/
    .fernrc
    src/
      imdb.yml
```

1. What do we call the `api` folder, which contains the Fernrc and the definition?
    1. `Workspace`
2. What do we call the .fernrc?
    1. `Workspace Configuration`
3. What do we call the the `src/` folder?
    1. `API Definition`

**Comment by dsinghvi** [comment]
would love to have users not know about `workspace`. Are you thinking of this more for us ?

**Comment by dsinghvi** [comment]
could 1i be `api`, 2i be `api configuration` and 3i be `api definition` ?

**Comment by zachkirsch** [comment]
yeah just for us, in the code it was getting really confusing for me
