### ISSUE TITLE
Duplicate generator messages in terminal

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#403]
When I resize the terminal window in VS Code my messages duplicate from the Fern CLI

Example of doing so during `fern generate`: 
<img width="926" alt="Screen Shot 2022-07-19 at 11 29 34 AM" src="https://user-images.githubusercontent.com/83524670/179823229-746cd08a-f32e-40c8-a68f-18dc0ef7e0aa.png">
.

**Comment by dannysheridan** [comment]
<img width="716" alt="Screen Shot 2022-08-02 at 11 37 13 AM" src="https://user-images.githubusercontent.com/83524670/182427492-65a4fb4a-b2a7-4359-a534-8d7d67dc974b.png">

**Comment by zachkirsch** [comment]
This is actually a limitation of the terminal, agree it’s very annoying

https://github.com/sindresorhus/log-update/issues/36

**Comment by dannysheridan** [comment]
closing without resolution. ^ is true.
