### ISSUE TITLE
[Feature] File support for spring generator

### ISSUE THREAD

**Issue by ammubhave** [fern-api/fern#4141]
### Problem description

For a file data type the generator gives this error

```
fernapi/fern-java-spring File upload not supported
fernapi/fern-java-spring Failed.
```

### Why would it be useful?

Currently needs ugly workaround by using audiences to exclude these endpoints from the spring generator. Also need to implement the interface methods manually.

```
  @PutMapping("/{param}/logo")
  public ResponseEntity<Void> updateLogo(
      @PathVariable("param") String param,
      @RequestPart(value = "file", required = false) MultipartFile logo) {
    ...
  }
```

**Comment by dannysheridan** [comment]
One day we'd love to support this. Unfortunately this request is not on the roadmap to be fixed because we're not actively developing the `java-spring` generator (and instead focusing on SDK language support)
