### ISSUE TITLE
Allow ignoring generation of the BearerAuth, Principal, and headers parameters in spring generator

### ISSUE THREAD

**Issue by ammubhave** [fern-api/fern#4154]
### Problem description

Currently the spring generator adds in parameters for BearerAuth, Principal, and HTTP headers inside each handler method, and requires that they be present.

### Why would it be useful?

Use cases where the authorization is done in a middleware suffer from having these parameters unnecessarily included, and needing the corresponding headers required to be provided even if they are not going to use it.

### Describe the solution (optional)

Ability to ignore generation of these extra params.

### Additional context

Add any other context or screenshots.

**Comment by dannysheridan** [comment]
Closing as we're not prioritizing improvements to the spring generator for the next few months. Focusing on the output SDKs!
