### ISSUE TITLE
Add a "default" in Fern Definition

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#419]
we always put `defaults to X` in our query params

**Comment by dannysheridan** [comment]
https://birchsolutions.slack.com/archives/C02AR20BL7P/p1664479131012489

**Comment by dannysheridan** [comment]
Something that I see often is a message like `defaults to true` or `defaults to 10`.

**Comment by dannysheridan** [comment]
+1

**Comment by mstoeckel** [comment]
big +1 to be able to specify the default value

**Comment by armandobelardo** [comment]
For us (Mammoth), we'd love to be able to get defaults in the object you get from the request itself, e.g. defaulting the fields in the pydantic model itself
The specific example we have right now is that we have an object with an optional start and end date, i'd like to be able to access the start and end date with defaulted values if they're not set by the caller
