### ISSUE TITLE
[Bug] doc generation fails if api.yml is missing

### ISSUE THREAD

**Issue by ammubhave** [fern-api/fern#4212]
## Describe the Bug

We use fern to generate docs for a site which does not have any api. Previously if there is no api.yml file, the doc generation would still succeed. Now the cli exits without non-zero status code, and needs a dummy definition/api.yml file with a name key.

### CLI Version

0.37.6

### Actual Behavior

exits with non-zero code and doc generation fails

```
[docs]: Found 0 errors and 1 warnings. Run fern check --warnings to print out the warnings.
[docs]: Missing file: api.yml
```

### Expected Behavior

doc generation suceeds

**Comment by dsinghvi** [comment]
https://github.com/fern-api/fern/pull/4206 @ammubhave this is being fixed in the linked PR!

**Comment by dsinghvi** [comment]
@ammubhave this is released in the [latest CLI ](https://github.com/fern-api/fern/releases/tag/0.37.11)
