### ISSUE TITLE
fern init naming (files and folders) changes

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#425]
Easy to forget to change it, e.g. https://github.com/fern-api/fern-cloud/blob/5d5d8ffd4aacac48f30244e079fd9b5a4939f90b/api/src/api.yml

We should ask for a name instead of default to _api_

We should not name the API folder `api/` and instead ask for a name or default to something good

**Comment by dannysheridan** [comment]
previous title: Maybe _don't_ start with IMDB stuff in fern init

**Comment by dannysheridan** [comment]
previous title: Maybe _don't_ start with IMDB stuff in fern init
