### ISSUE TITLE
[Feature] Support for Mermaid.js diagrams

### ISSUE THREAD

**Issue by ammubhave** [fern-api/fern#4305]
### Problem description

Easy way to include diagrams in the generated docs.

### Why would it be useful?

Mermaid JS is a popular diagramming library that let's users write diagram descriptions directly in the markdown.

### Describe the solution (optional)

Either of these would work.

1. Mermaid component - https://sjwall.github.io/mdx-mermaid/docs/examples/#component
OR
2. Mermaid codeblock that renders the mermaid graph - https://sjwall.github.io/mdx-mermaid/docs/examples/#code-block
OR
3. Support this workflow https://mermaid.js.org/config/usage.html#installing-and-hosting-mermaid-on-a-webpage. I tried adding <pre> tag in the mdx but that broke the rendering.

### Additional context

We are trying to add architecture diagrams to our docs and the current path of creating a separate PNG and embedding in as an image is too painful.

**Comment by dannysheridan** [comment]
This is now supported! https://buildwithfern.com/learn/docs/content/write-markdown#diagrams

Please run `fern upgrade` to get the latest CLI.
