### ISSUE TITLE
[Bug] `fern check` doesn’t say which file the error is in

### ISSUE THREAD

**Issue by cwcowell** [fern-api/fern#4740]
### Describe the bug

`fern check` correctly reports errors, but doesn’t report which file the error is in. See screenshot below.

### To reproduce

1.  Run `fern check` on a repo with a problematic file, such as an `.mdx` file that closes an `<img>` tag with `</span>`

### Expected behavior

The output of `fern check` includes the name of the file where the problem occurs.

### Screenshots

<img width="787" alt="image" src="https://github.com/user-attachments/assets/4c456f20-3146-4170-b587-d5a370b368fc">

### CLI Version

0.42.15

### Additional context

n/a

**Comment by cwcowell** [comment]
Here’s another example.

<img width="1288" alt="image" src="https://github.com/user-attachments/assets/c83e2632-86dc-4fe0-92a6-a0de4779f4e1">

**Comment by cwcowell** [comment]
<img width="1172" alt="image" src="https://github.com/user-attachments/assets/c2b62bbf-89ea-450d-b875-2992dbdd9ff8">
 
Another example.

**Comment by cwcowell** [comment]
@abvthecity Special plea to tackle this one soon — it’s turning out to be a big thorn in our side. Thank you!

**Comment by dsinghvi** [comment]
@cwcowell https://github.com/fern-api/fern/pull/4771 should address your concern

**Comment by dsinghvi** [comment]
@cwcowell this is now merged and released in the latest Fern CLI. Please run `fern upgrade` to see!

**Comment by cwcowell** [comment]
That works, thank you! And the reported line number for the error is more accurate too. :boom:
