### ISSUE TITLE
Postman integration

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#48]
- Postman has first class support for socket io: https://blog.postman.com/postman-now-supports-socket-io/

**Comment by dsinghvi** [comment]
`fern-postman` has been added

**Comment by zachkirsch** [comment]
@dannysheridan @dsinghvi  are we tracking the "live updating postman" somehwere?

**Comment by dannysheridan** [comment]
Yes.  https://github.com/fern-api/fern/issues/284
