### ISSUE TITLE
Organization names with invalid characters generate invalid code. 

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#491]
having an `@` and/or `/` caused an error with publishing to np
m
<img width="530" alt="Screen Shot 2022-07-29 at 5 50 08 PM" src="https://user-images.githubusercontent.com/83524670/181855236-cf578781-8334-47ce-8485-d5c16a096171.png">
###

**Comment by dsinghvi** [comment]
Closing because stale
