### ISSUE TITLE
Get rid of service-utils

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#499]
Just codegen everything in the package

**Comment by dsinghvi** [comment]
why is this better? should i be following the same thing in java?

**Comment by zachkirsch** [comment]
The click through is annoying in that it takes you to a different package. Also imo preferable for an external SDK that clicking through on a type like “Response” doesn’t take you into some “fern” package the user doesn’t know about

**Comment by dsinghvi** [comment]
this is now done
