### ISSUE TITLE
Allow boolean discriminants

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#500]
// came up with PA meeting on July 29

In certain cases where there will only ever been two options, a boolean discriminant (i.e. `{isSuccess: true}`) would be nicer than string discriminants, where you have to handle unknown.

**Comment by dsinghvi** [comment]
prevents you from ever adding a third -- why Stripe actually disallows using `booleans` in their api at all and prefers using enums

**Comment by zachkirsch** [comment]
Yes yes but also sometimes it just makes sense

**Comment by zachkirsch** [comment]
https://github.com/fern-api/fern-propelauth/blob/0fc6ca40688ead74c2f21dcc553fc37e2b8b2117/api/src/profile.yml#L15-L18

**Comment by dsinghvi** [comment]
Closing because this hasn't been requested by the community.
