### ISSUE TITLE
FastAPI support for file upload

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#5270]
### Feature Description

> We have an endpoint where we upload an image, and another endpoint where we retrieve an image. Can I do that with fern? How do I define that?

**Comment by dsinghvi** [comment]
This is now supported in the latest fastapi generator (`v1.6.0`). Here is an example of the generated code: https://github.com/fern-api/fern/blob/ca780cc0b961879c5f4211c60424738e66acd88d/seed/fastapi/file-upload/resources/service/service/service.py#L34-L35
