### ISSUE TITLE
Support for Icons in href Side nav items

### ISSUE THREAD

**Issue by noanflaherty** [fern-api/fern#5307]
### Feature Description

I'd like to be able to specify that an icon appear to the left of side nav items, even if that side nav item is a simple href.

### Use Case

I have sidenav items that are hrefs, but want to style them like any other sidenav item.

**Comment by dannysheridan** [comment]
@noanflaherty up to provide an example of how you'd want `docs.yml`to read?

**Comment by noanflaherty** [comment]
Yeah I'm imagining this:
<img width="637" alt="2024-11-30_09-43-04" src="https://github.com/user-attachments/assets/6d4948ed-0bdd-4eff-af22-5d0073fa211a">

**Comment by dannysheridan** [comment]
Awesome, this is helpful! Is this something that you'd like to use immediately? Looking to get a sense of priority. Makes sense for us to support this.

**Comment by noanflaherty** [comment]
If it was available, we’d use it immediately.
