### ISSUE TITLE
Inaccurate Error Message for Markdown Components w/ Invalid Snippet  Path

### ISSUE THREAD

**Issue by noanflaherty** [fern-api/fern#5308]
### Issue Description

Using `Markdown` components with an invalid snippet path results in a misleading error message:

<img width="319" alt="2024-11-30_09-02-40" src="https://github.com/user-attachments/assets/a68cb1c3-fc56-46de-bc7f-dac13993ce72">

### Suggested Improvement

It'd be more helpful if this said something like "Unable to find markdown snippet at path {path}`

**Comment by dannysheridan** [comment]
I went ahead and tested this with a component `<Tooltip tip="Testing tooltip">Does this appear with an error?</Tooltip>` and found that it does not show this error message. It now fails silently and doesn't show the component at all in the docs. I've opened this issue to track the request for a warning to be thrown when this happens: https://github.com/fern-api/fern/issues/5496
