### ISSUE TITLE
Document `default-language` configuration option in API reference setup guide

### ISSUE THREAD

**Issue by emrgnt-cmplxty** [fern-api/fern#5334]
### Documentation Page URL

https://github.com/cohere-ai/cohere-developer-experience/blob/72ae51169c2cc288139e78890d9ac502c9def401/fern/docs.yml#L14

## Description
Currently, the ability to configure the default programming language shown in the API reference (via `default-language` in docs.yml) is not documented. This setting is important for teams who want to customize the initial SDK example language their users see.

### Current Status
- The configuration option exists and works (`default-language: python` in docs.yml)
- This functionality is not mentioned in our documentation

### Proposed Changes
Add documentation explaining:
- Where to set the default language (docs.yml)
- Available language options
- Example configuration
- Default value if not specified

### Example Documentation Section
```markdown
## Configuring Default SDK Language

You can specify which programming language's SDK examples are shown by default in the API reference by setting `default-language` in your `docs.yml`:

```yaml
default-language: python
```

Available options include:
- python
- curl
- [other supported languages]
```

## Labels
- documentation
- enhancement

### Steps to Reproduce (Optional)

_No response_

### Suggested Improvement

_No response_

**Comment by dannysheridan** [comment]
Relevant docs page: https://buildwithfern.com/learn/docs/getting-started/global-configuration

**Comment by dannysheridan** [comment]
Live and available in Fern's documentation as the parameter `default-language` at https://buildwithfern.com/learn/docs/getting-started/global-configuration#top-level-properties 

Not being able to share an anchor link to the `default-language` param directly inspired https://github.com/fern-api/fern/issues/5508
