### ISSUE TITLE
Use Fern definitions and OpenAPI spec together?

### ISSUE THREAD

**Issue by lsegal** [fern-api/fern#5389]
### Issue Description

I would like to borrow components defined in an OpenAPI spec (.json) inside of a Fern definition file (.yml). I could not find any specific documentation on the topic but assumed this would "just work":

```yaml
imports:
  common: common.openapi.json

service:
  ...
```

Running `fern generate` yields this error:

```
[api]: service.yml -> imports -> common
       Import common points to non-existent path common.openapi.json.
```

The file does exist in the same directory as the .yml file. Note that this is an abridged example, my other example has other `imports` definitions from yml files in the same directory which all resolve correctly.

What am I doing wrong?

**Comment by dsinghvi** [comment]
@lsegal unfortunately this does not exist, but sounds like an amazing feature

**Comment by dsinghvi** [comment]
One option is to import the OpenAPI into a fern definition by running `fern init --openapi <path/to/openapi>` and then running `fern write-definition`

**Comment by lsegal** [comment]
I was able to convert the OpenAPI definition with a bit of massaging, thanks.

Note that those two commands worked but importing it was not a no-op, it needed manual fixes to the imported yml, so it's not exactly an automatable action. In particular I was getting these errors (repeated for a bunch of different enums and types):

```
common.yml -> types -> ServiceResult
Unexpected key
Encountered unexpected key default
Unexpected key
Encountered unexpected key source
common.yml -> types -> ComponentType
```

Seems like maybe the OpenAPI -> Fern conversion might need some updating. This was on:

```sh
$ fern --version
0.45.3
```

Going to mark this as closed since I have what I need.
