### ISSUE TITLE
GET operations cannot have a request

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#546]
Semantic error at the path (e.g. "paths./v2/link/provider/oauth/{oauth_provider}.get.requestBody")
GET operations cannot have a requestBody.

**Comment by dannysheridan** [comment]
<img width="724" alt="Screen Shot 2022-08-08 at 3 56 50 PM" src="https://user-images.githubusercontent.com/83524670/183503475-30efd365-9d56-435f-9f3c-6bf7ae5296f5.png">

**Comment by dannysheridan** [comment]
caught by swagger editor!

**Comment by dsinghvi** [comment]
https://github.com/swagger-api/swagger-ui/issues/2136 check out this issue, i don't think we should actually validate against this

**Comment by dsinghvi** [comment]
https://github.com/OAI/OpenAPI-Specification/pull/2117 maybe we can warn instead

**Comment by zachkirsch** [comment]
From MDN:

> Note: Sending body/payload in a GET request may cause some existing implementations to reject the request — while not prohibited by the specification, the semantics are undefined. It is better to just avoid sending payloads in GET requests.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

**Comment by zachkirsch** [comment]
Happy to disallow it like conjure?

**Comment by dannysheridan** [comment]
I'm in favor of warning but allowing.

**Comment by zachkirsch** [comment]
Is there a use case where someone needs it?  If certain server implementations don’t allow get bodies (per MDN) this could cause issues. Also a good place to encode an opinion.

**Comment by dannysheridan** [comment]
+1 to warn against having a Request in a GET body.

**Comment by dannysheridan** [comment]
+1 to this.
