### ISSUE TITLE
Vellum’s SDK documentation (from showcase) doesn’t look good on mobile

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#5502]
### Documentation Page URL

https://buildwithfern.com/learn/docs/getting-started/customer-showcase

### Issue Description

Vellum’s SDK Documentation (which is linked from the showcase) looks meh on mobile. imo all the pages linked from the showcase should look super good

### Steps to Reproduce (Optional)

![IMG_0746](https://github.com/user-attachments/assets/a571d723-5194-4908-b3ab-2fb96951bc29)
![IMG_0745](https://github.com/user-attachments/assets/01f0b82e-b1d5-4a88-bc0c-7da63175dfe4)

### Suggested Improvement

On mobile the code example should probably be below the API reference since there isn’t enough space for side-by-side

**Comment by dannysheridan** [comment]
Thanks for opening this issue @zachkirsch 🙏

**Comment by chdeskur** [comment]
https://docs.vellum.ai/developers/workflows-sdk/api-reference/nodes#search-node

@zachkirsch - the styling has been updated, feel free to open another issue if you have more recommendations for improvements!
