### ISSUE TITLE
improve cli error message for file structure mishaps

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#599]
got the following error when the problem was an erroneous `src` folder inside of the `api` directory. let me to check generators.yml, but that wasn't the issue. when I deleted the erroneous `src` folder, `fern check` worked again.

```
[Error: ENOENT: no such file or directory, open '/Users/dsheridan/Coding/fern-hookdeck/.fern/src/generators.yml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/dsheridan/Coding/fern-hookdeck/.fern/src/generators.yml'
}
```

**Comment by dannysheridan** [comment]
deep: fern cli should be more descriptive if there is a malformed api definition

**Comment by dsinghvi** [comment]
this is outdated
