### ISSUE TITLE
Remove references to "workspaces" in CLI

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#664]
If my api.yml reads:
```
name: IMDb
auth: bearer
```

Upon `fern check` I get the error:
```
[IMDb]: Workspace name is not valid.
```

Workspace is a deprecated title and should just read "[IMDb]: Name is not valid."

**Comment by dannysheridan** [comment]
+1 got an error in the CLI: `[Gigs Core API]: Workspace name is not valid.`

https://github.com/fern-gigs/gigs-api/actions/runs/3770307813/jobs/6410064714

**Comment by dannysheridan** [comment]
The error `Workspace name is not valid.` doesn't tell me why it isn't valid. Would be helpful to have more help to resolve.

**Comment by dannysheridan** [comment]
In my case, I had capital letters `Gigs-Core-API`

**Comment by dsinghvi** [comment]
Closing because this is no longer valid
