### ISSUE TITLE
Add tests for changing wire format in IR

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#673]
If we change the wire format, we should know before we merge in the PR.

Plan of attack:
1. [P0] Add snapshot testing for `yaml-to-ir` with example exhaustive APIs. We can manually review these for now.
1. [P1] We can be smart about which fields in the IR affect wire format (e.g. `wireValue`), so we should have a special check that ensures that we didn't break wire format,

**Comment by dsinghvi** [comment]
Closing because we won't be doing this work.
