### ISSUE TITLE
fern init should not `find up` 

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#677]
<img width="1063" alt="Screen Shot 2022-09-05 at 10 42 14 AM" src="https://user-images.githubusercontent.com/10870189/188419631-8f96fdec-2717-42cb-9881-24ccfa5c2f4c.png">

`fern init` should just create a fern directory at that level

**Comment by zachkirsch** [comment]
Already fixed https://github.com/fern-api/fern/pull/668
