### ISSUE TITLE
FernFilepath should specify directories + file

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#686]
Rather than just a list of strings, so we don't have to do stuff like https://github.com/fern-api/fern-typescript/blob/2e47b67011b5493ed39cd3e861d02ca047a6a730/packages/cli/src/v2/client/utils/getExportedDirectoriesForFernFilepath.ts#L19-L21

**Comment by zachkirsch** [comment]
+ maybe it should be a union between `api.yml` and a regular file?

**Comment by dsinghvi** [comment]
Closing because we won't be doing this work.
