### ISSUE TITLE
Fern visualize

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#70]
It would be cool if `fern visualize` would fire up a local ui where you can edit and changes are written back to your yaml files. 
No code UI at the edge

**Comment by hpx7** [comment]
I've really wanted this for Hathora too! Surprisingly to us, one of the biggest pieces of feedback we've gotten from our users is that they've hated the yml editing experience. It's too error prone and difficult to do from scratch.

A friend prototyped a hathora.yml generator at https://github.com/varunm/hathora-yml-generator, it looks something like this:
![image](https://user-images.githubusercontent.com/5400947/165792508-4340c086-83e6-46cc-9838-427d0e7834bc.png)

**Comment by dsinghvi** [comment]
Closing this issue since we aren't planning to support visualization of the API definition. We will be focusing more on visualizing SDK Releases and Documentation.
