### ISSUE TITLE
Add fern-check rule that properties in extensions don't overlap

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#713]
- if `A` extends `B`, then they can't have the same property (name or value)
- if `A` is a union type, then its discriminant can't overlap with any properties in the subtypes (the ones that that extend objects)
- if `A` is a union type, then its discriminant can't be `"value"` since that's the string we use for primitive/union/enum subtypes

**Comment by dsinghvi** [comment]
Closing because this is now done.
