### ISSUE TITLE
Excluding API endpoints from generated SDKs

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#714]
There are a couple of different usecases for varying the access level of different endpoints: 
- "I am adding an endpoint that noone else should be able to hit (i.e. a health endpoint)" 
- "I am adding an endpoint that my internal clients (i.e. a frontend) should have access to but customers cant"
- "I am adding an endpoint that customers can hit"

Fern should support declaring these access levels: maybe (private, internal, public) and generating SDKs with varying degree of access.

**Comment by dannysheridan** [comment]
added with support for `audiences`
