### ISSUE TITLE
[decomp] Remove 'no-circular-dependencies' fern-check rule

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#730]
It may be that https://github.com/fern-api/fern/issues/729 is the only thing we need to check re circular dependencies, and it might be totally fine to have circular imports.

I think the reason we added this rule is that without it, Python codegen was infeasible. So let's make sure that Python will be okay before we delete the rule.

**Comment by dsinghvi** [comment]
this is removed now
