### ISSUE TITLE
Ambiguous warn message from fern check -- conflicting properties

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#739]
<img width="1165" alt="Screen Shot 2022-09-21 at 6 47 59 PM" src="https://user-images.githubusercontent.com/83524670/191640453-1f4cd7f6-37d7-4e77-9155-53104cd97f51.png">

Same issue is duplicated twice for each of the 3 (thus shows 6 messages). 
Hard to understand what to do as the user.

**Comment by zachkirsch** [comment]
I don't see any duplicates in the above screenshot. Pushing a change now that should hopefully make the messages better. Once that releases, wanna try again and see if they seem better?

**Comment by dsinghvi** [comment]
Closing bc issue is not clear
