### ISSUE TITLE
Declare filename with Unexpected key error

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#740]
<img width="847" alt="Screen Shot 2022-09-21 at 7 39 25 PM" src="https://user-images.githubusercontent.com/83524670/191646903-e519bdff-9c49-404a-8bfa-256e50de28c2.png">

Repro by adding `foo: bar` to api.yml which is not supposed to be there.

Request: tell me the file name that I should look for to find the problem.

**Comment by zachkirsch** [comment]
Fixing to include filename
