### ISSUE TITLE
Don't always codegen "unknown" visitors

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#751]
In some cases, "unknown" is not necessary and annoying to have to deal with. Some examples:
1. When implementing a server, you shouldn't have to deal with unknown. Only clients need to handle unknown. (Assuming server is always ahead of client).
2. When using `model` mode. e.g. for `db-api`.
3. When the type is only used in requests. Since they're always constructed client side, the client never will receive a maybe-unknown value.
4. When you just _know_ the list won't grow, e.g. for `State` (`AL`, `AK`, `AZ`, ...). Ofc if we ever did add a 51st state, you'd just have to make a `StateV2`.

(1) and (2) can't be in the IR because it depends on which generator is being run.
(3) the generator _could_ do but it should probably live in the IR to avoid repeated work in the generators.
(4) would require YAML + IR changes.

**Comment by dsinghvi** [comment]
this is now fixed
