### ISSUE TITLE
Circular imports don't make sense to me

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#756]
I want to keep my `Id` with the relevant resource. Because I have imports in both directions, I get a `fern check` error that I feel is erroneous. 

<img width="969" alt="Screen Shot 2022-09-26 at 3 42 31 PM" src="https://user-images.githubusercontent.com/83524670/192394287-e4b188b3-5e43-49b4-b675-ad00e8160bc9.png">

**Comment by dsinghvi** [comment]
Closing because this is done.
