### ISSUE TITLE
Support for Literal

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#763]
As a user, I can specify a static value that my API will return for a property.

**Comment by dannysheridan** [comment]
Can this solve the problem? https://github.com/fern-api/fern/issues/466

**Comment by zachkirsch** [comment]
+1 good feature

no defaults are different. this ticket is saying "the number HAS to be `42`" while defaults are saying "if you don't give me a number, i'll assume `42`"

**Comment by dannysheridan** [comment]
<img width="589" alt="Screenshot 2022-12-17 at 6 59 48 AM" src="https://user-images.githubusercontent.com/83524670/208243064-c2feee37-a317-42f9-a4f8-5ac990952f73.png">

example of an API using a literal string

**Comment by dsinghvi** [comment]
@dannysheridan in the example you shared can you use `union` with the discriminant `deviceModel` ?

**Comment by kafkas** [comment]
+1

**Comment by dsinghvi** [comment]
This now exists
