### ISSUE TITLE
Validation: Only objects are allowed to be extended

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#8]
It doesn't make sense to extend `union`, `enum`, or an `alias` because it is unclear what the extended type would look like (i.e. why would I ever extend a union instead of adding it as a field). 
We should validate that only `objects` are allowed to be extended.

**Comment by dannysheridan** [comment]
we now support extending unions. closing

**Comment by dsinghvi** [comment]
@dannysheridan fyi we don't support extending unions
