### ISSUE TITLE
Document declaring discriminants in Union types

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#810]
```
Foo:
  union:
    bar1: Object1
    bar2: Object2
  discriminant: myString
```

**Comment by Giriraj-Roy** [comment]
Hello Sir,

I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by dannysheridan** [comment]
I've added this to the docs. Thanks @Giriraj-Roy for the offer!
