### ISSUE TITLE
Configuration page not appearing in Docusaurus search results

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#829]
[Auth page that doesn't appear when x-api-key is searched ](https://github.com/fern-api/fern/blob/b5bfb7233b1f1c9539c01c6d089d19bdf9fb15a0/packages/docs/docs/configuration/api.md)

**Comment by dannysheridan** [comment]
<img width="565" alt="Screen Shot 2022-10-17 at 9 15 42 AM" src="https://user-images.githubusercontent.com/83524670/196229355-342ce52d-c932-42cb-bdc6-410299df5990.png">

**Comment by dsinghvi** [comment]
stale
