### ISSUE TITLE
Example spec

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#93]
Add an example spec to the Fern repo. It should include Rest + Websockets.

**Comment by dsinghvi** [comment]
Features we may want to show: 
- Model flexibility (Union, Enum, Primitives, Containers (sets/map), Optional, Extending another Object)
- Rest Api (auth header, grouping endpoints as a service, path parameters, query parameters, headers)
- Websocket Api

**Comment by dannysheridan** [comment]
Food Delivery

CartService
- addItem (POST)
- changeRestaurant (will clear cart, add to Docs)
- removeItem

OrderService
- placeOrder
- getOrderStatus
- getOrderItems
- cancelOrder
